<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.33">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>10&nbsp; Transformers – Business Forecasting</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/Lecture10_BayesianFoundations.html" rel="next">
<link href="../chapters/Lecture09_Part1_RNN_LSTM.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-c1b08d31956f1824f457e0b6984faaea.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/Lecture09_Part2_Transformers.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Transformers</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Business Forecasting</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture01_ETS_Eval.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction, Exponential Smoothing &amp; Forecast Evaluation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture02_ARIMA_VAR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">ARIMA, VAR &amp; Multivariate Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture03_GAMs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Generalized Additive Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture04_DecisionTrees.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Decision Trees</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture05_TreeEnsembles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Tree Ensembles: Random Forests &amp; Boosted Trees</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture06_Regularization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Regularization &amp; Model Selection</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture07_NeuralNets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Introduction to Neural Networks</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture08_CNNs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">CNN Architectures</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture09_Part1_RNN_LSTM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">RNNs and LSTMs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture09_Part2_Transformers.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Transformers</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture10_BayesianFoundations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Bayesian Statistics I — Foundations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture11_Part1_BayesianTS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Bayesian Statistics II — Time Series</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture11_Part2_Hierarchical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Bayesian Statistics II — Hierarchical Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture12_BayesianRegression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Bayesian Statistics III — Bayesian Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture13_Synthesis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Synthesis — What the Semester Measured</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#lecture-outline" id="toc-lecture-outline" class="nav-link active" data-scroll-target="#lecture-outline"><span class="header-section-number">10.1</span> Lecture Outline</a></li>
  <li><a href="#what-recurrence-could-not-do" id="toc-what-recurrence-could-not-do" class="nav-link" data-scroll-target="#what-recurrence-could-not-do"><span class="header-section-number">10.2</span> What Recurrence Could Not Do</a>
  <ul class="collapse">
  <li><a href="#two-problems-built-into-recurrence" id="toc-two-problems-built-into-recurrence" class="nav-link" data-scroll-target="#two-problems-built-into-recurrence"><span class="header-section-number">10.2.1</span> Two Problems Built Into Recurrence</a></li>
  </ul></li>
  <li><a href="#the-attention-mechanism" id="toc-the-attention-mechanism" class="nav-link" data-scroll-target="#the-attention-mechanism"><span class="header-section-number">10.3</span> The Attention Mechanism</a>
  <ul class="collapse">
  <li><a href="#scaled-dot-product-attention" id="toc-scaled-dot-product-attention" class="nav-link" data-scroll-target="#scaled-dot-product-attention"><span class="header-section-number">10.3.1</span> Scaled Dot-Product Attention</a></li>
  <li><a href="#what-that-buys-a-forecaster" id="toc-what-that-buys-a-forecaster" class="nav-link" data-scroll-target="#what-that-buys-a-forecaster"><span class="header-section-number">10.3.2</span> What That Buys a Forecaster</a></li>
  <li><a href="#multi-head-attention" id="toc-multi-head-attention" class="nav-link" data-scroll-target="#multi-head-attention"><span class="header-section-number">10.3.3</span> Multi-Head Attention</a></li>
  </ul></li>
  <li><a href="#the-transformer-encoder" id="toc-the-transformer-encoder" class="nav-link" data-scroll-target="#the-transformer-encoder"><span class="header-section-number">10.4</span> The Transformer Encoder</a>
  <ul class="collapse">
  <li><a href="#the-encoder-block" id="toc-the-encoder-block" class="nav-link" data-scroll-target="#the-encoder-block"><span class="header-section-number">10.4.1</span> The Encoder Block</a></li>
  <li><a href="#positional-encoding-attention-cannot-tell-time" id="toc-positional-encoding-attention-cannot-tell-time" class="nav-link" data-scroll-target="#positional-encoding-attention-cannot-tell-time"><span class="header-section-number">10.4.2</span> Positional Encoding: Attention Cannot Tell Time</a></li>
  <li><a href="#why-transformers-took-over" id="toc-why-transformers-took-over" class="nav-link" data-scroll-target="#why-transformers-took-over"><span class="header-section-number">10.4.3</span> Why Transformers Took Over</a></li>
  </ul></li>
  <li><a href="#transformers-for-time-series" id="toc-transformers-for-time-series" class="nav-link" data-scroll-target="#transformers-for-time-series"><span class="header-section-number">10.5</span> Transformers for Time Series</a>
  <ul class="collapse">
  <li><a href="#transformer-encoder-in-pytorch" id="toc-transformer-encoder-in-pytorch" class="nav-link" data-scroll-target="#transformer-encoder-in-pytorch"><span class="header-section-number">10.5.1</span> Transformer Encoder in PyTorch</a></li>
  <li><a href="#does-it-work" id="toc-does-it-work" class="nav-link" data-scroll-target="#does-it-work"><span class="header-section-number">10.5.2</span> Does It Work?</a></li>
  <li><a href="#reading-that-result-honestly" id="toc-reading-that-result-honestly" class="nav-link" data-scroll-target="#reading-that-result-honestly"><span class="header-section-number">10.5.3</span> Reading That Result Honestly</a></li>
  </ul></li>
  <li><a href="#key-takeaways" id="toc-key-takeaways" class="nav-link" data-scroll-target="#key-takeaways"><span class="header-section-number">10.6</span> Key Takeaways</a>
  <ul class="collapse">
  <li><a href="#sequence-architecture-comparison" id="toc-sequence-architecture-comparison" class="nav-link" data-scroll-target="#sequence-architecture-comparison"><span class="header-section-number">10.6.1</span> Sequence Architecture Comparison</a></li>
  <li><a href="#lecture-9-part-2-key-takeaways" id="toc-lecture-9-part-2-key-takeaways" class="nav-link" data-scroll-target="#lecture-9-part-2-key-takeaways"><span class="header-section-number">10.6.2</span> Lecture 9 Part 2: Key Takeaways</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">10.6.3</span> References</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Transformers</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><em>Lecture 9, Part 2 of ECON 8310.</em></p>
<section id="lecture-outline" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="lecture-outline"><span class="header-section-number">10.1</span> Lecture Outline</h2>
<ol type="1">
<li>What Recurrence Could Not Do</li>
<li>The Attention Mechanism</li>
<li>The Transformer Encoder</li>
<li>Transformers for Time Series</li>
<li>Key Takeaways</li>
</ol>
<p>Five parts. What recurrence could not do — two specific constraints. Then attention itself, which is a weighted lookup and much less mysterious than the formula makes it look. Then the encoder block, which is attention plus three things you already know. Then the implementation and an honest measurement. And finally where all six sequence architectures sit relative to each other.</p>
</section>
<section id="what-recurrence-could-not-do" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="what-recurrence-could-not-do"><span class="header-section-number">10.2</span> What Recurrence Could Not Do</h2>
<p>Two constraints that are built into reading a sequence one step at a time.</p>
<section id="two-problems-built-into-recurrence" class="level3" data-number="10.2.1">
<h3 data-number="10.2.1" class="anchored" data-anchor-id="two-problems-built-into-recurrence"><span class="header-section-number">10.2.1</span> Two Problems Built Into Recurrence</h3>
<p>Part 1 ended with a working recurrent forecaster. Both of its remaining problems come from the same source — it reads strictly left to right.</p>
<p><strong>The information bottleneck.</strong> Everything the model knows about step 3 must survive being squeezed through every hidden state between 3 and <span class="math inline">\(T\)</span>. An LSTM’s gates make that survival more likely, but the whole history is still compressed into one fixed-size vector.</p>
<p><strong>The sequential bottleneck.</strong> Step <span class="math inline">\(t\)</span> cannot be computed until step <span class="math inline">\(t-1\)</span> is finished. That is a hard constraint: a 1,000-step sequence takes 1,000 sequential operations no matter how many GPUs you own. Convolutions parallelize; recurrence does not.</p>
<div class="keybox">
<p><strong>Attention removes both at once.</strong> Let every position look directly at every other position, in one operation. No compression through intermediate states, and no ordering constraint on the computation.</p>
</div>
<p>Part 1 left us with a working recurrent forecaster. Both of its remaining problems come from the same source: it reads strictly left to right.</p>
<p><strong>The information bottleneck.</strong> Everything the model knows about step three has to survive being squeezed through every hidden state between three and the end of the window. An LSTM’s gates make that survival more likely — that’s what they’re for — but the entire history is still being compressed into one fixed-size vector, over and over.</p>
<p><strong>The sequential bottleneck.</strong> Step t cannot be computed until step t minus one is finished. That is a hard constraint, not an implementation detail. A thousand-step sequence takes a thousand sequential operations no matter how many GPUs you own. Convolutions parallelize beautifully; recurrence cannot.</p>
<p>Attention removes both at once, and the idea is almost aggressively simple: let <strong>every position look directly at every other position</strong>, in one operation.</p>
<p>No compression through intermediate states — position twenty-six reads position three directly. And no ordering constraint on the computation — all positions are computed simultaneously.</p>
</section>
</section>
<section id="the-attention-mechanism" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="the-attention-mechanism"><span class="header-section-number">10.3</span> The Attention Mechanism</h2>
<p>A learned, weighted lookup — which is a more useful way to read it than the formula suggests.</p>
<section id="scaled-dot-product-attention" class="level3" data-number="10.3.1">
<h3 data-number="10.3.1" class="anchored" data-anchor-id="scaled-dot-product-attention"><span class="header-section-number">10.3.1</span> Scaled Dot-Product Attention</h3>
<div class="definitionbox">
<div class="definitionbox-title">
<p>The whole mechanism</p>
</div>
<p><span class="math display">\[\text{Attention}(Q, K, V) = \text{softmax}\!\left(\frac{QK^\top}{\sqrt{d_k}}\right) V\]</span></p>
<p><span class="math inline">\(Q\)</span> = queries, <span class="math inline">\(K\)</span> = keys, <span class="math inline">\(V\)</span> = values, <span class="math inline">\(d_k\)</span> = key dimension.</p>
</div>
<p>Read it as a <strong>lookup table with soft matching</strong> <span class="citation" data-cites="Vaswani2017">[@Vaswani2017]</span>. Each position emits a <strong>query</strong>: <em>“what am I looking for?”</em> Every position also offers a <strong>key</strong>: <em>“here is what I have”</em> — and a <strong>value</strong>: <em>“here is what I would contribute.”</em></p>
<p><span class="math inline">\(QK^\top\)</span> scores every query against every key. The softmax turns those scores into weights that sum to one. The output is a weighted average of the values, with more weight where query and key matched.</p>
<p><strong>Why divide by <span class="math inline">\(\sqrt{d_k}\)</span>?</strong> Dot products grow with dimension, and large inputs push the softmax toward one-hot, where its gradient nearly vanishes. The scaling keeps it trainable.</p>
<p>Here’s the formula. Attention of Q, K, V equals softmax of Q K-transpose over root d-k, times V. That’s the whole mechanism. Every Transformer in the world is that line, repeated.</p>
<p>Now let me translate it, because the formula makes it look more exotic than it is. Read it as a <strong>lookup table with soft matching.</strong></p>
<p>Each position emits a <strong>query</strong> — that’s the “what am I looking for?” vector. Every position also offers a <strong>key</strong>, which says “here’s what I have.” And a <strong>value</strong>, which says “here’s what I would contribute if you pick me.”</p>
<p>So: Q times K-transpose scores every query against every key. That’s a big matrix of similarity scores — every position against every position. The softmax turns each row of those scores into weights that sum to one. And then you multiply by V, which gives you a weighted average of the values, with more weight wherever query and key matched well. That’s it. Score, normalize, average.</p>
<p>And it’s worth noticing you have built something very close to this already, by hand. In Homework 4, a rolling mean is a weighted average over recent positions — with weights you fixed in advance, equal across the window. A Fourier term is a weighted combination too, with weights set by a formula.</p>
<p>Attention is the same <em>shape</em> of operation with the weights <strong>learned</strong>, and recomputed for every input. That’s the whole upgrade. Not a new kind of mathematics — a new source for the numbers.</p>
<p>Why divide by root d-k? Because dot products grow with dimension. In high dimensions the raw scores get large, and large inputs push the softmax toward a one-hot distribution — all the weight on one position — where its gradient is nearly zero and nothing trains. Dividing by root d-k keeps the scores in a range where the softmax stays soft. It’s a numerical fix, not a conceptual one, but leave it out and the model doesn’t learn.</p>
</section>
<section id="what-that-buys-a-forecaster" class="level3" data-number="10.3.2">
<h3 data-number="10.3.2" class="anchored" data-anchor-id="what-that-buys-a-forecaster"><span class="header-section-number">10.3.2</span> What That Buys a Forecaster</h3>
<p>Concretely: predicting units for the first week of December, the model can place high weight on <em>last</em> December and on the surrounding weeks, and near-zero weight on an unremarkable Tuesday in March.</p>
<p>Two properties make that different from anything so far.</p>
<p><strong>The weights are learned, not specified.</strong> You do not tell the model that lag 52 matters. Compare that with LASSO in Lecture 6, where you built <code>lag52</code> by hand and the penalty decided whether to keep it.</p>
<p><strong>The path is direct.</strong> Attention reaches week <span class="math inline">\(t-52\)</span> in <em>one</em> operation, where a recurrent model needs 52 successive state updates and a CNN needs a receptive field that wide. Distance costs attention nothing.</p>
<div class="warningbox">
<p>The price is quadratic: scoring every position against every other is <span class="math inline">\(O(T^2)\)</span> in time and memory — fine at <span class="math inline">\(T = 26\)</span>, painful at <span class="math inline">\(T = 10{,}000\)</span>.</p>
</div>
<p>Let me make that concrete for our problem.</p>
<p>You’re predicting units for the first week of December. With attention, the model can place high weight on <strong>last</strong> December, and on the weeks around it, and near-zero weight on an unremarkable Tuesday in March. It looks where the information is. Two properties make that genuinely different from anything we’ve built.</p>
<p><strong>The weights are learned, not specified.</strong> You do not tell the model that lag fifty-two matters. Contrast that with Lecture 6, where you built the <code>lag52</code> column by hand and the LASSO penalty merely decided whether to keep it. Here the model discovers which positions to consult.</p>
<p><strong>And the path is direct.</strong> Attention reaches week t minus fifty-two in <strong>one</strong> operation. A recurrent model needs fifty-two successive state updates to get there — and we saw last week what survives fifty-two multiplications. A CNN needs a receptive field that wide, which it doesn’t have. Distance costs attention nothing. That’s the headline.</p>
<p>There’s a third property worth naming, because it matters for how you’d sell this to a stakeholder. Attention weights are <strong>inspectable</strong>. You can pull out the matrix and look at which weeks the model consulted when it made a given forecast.</p>
<p>That is not the same as an explanation — a high attention weight tells you where the model looked, not why it decided what it decided, and there’s a real literature arguing about how much to read into them. But compared with an LSTM’s hidden state, which is sixty-four numbers with no interpretation whatsoever, it’s a meaningful step toward a model whose reasoning you can interrogate.</p>
<p>And here’s the price, which is real. Scoring every position against every other position is <strong>quadratic</strong> — order T-squared in both time and memory. At T equals twenty-six, that’s irrelevant. At T equals ten thousand, it is the central engineering constraint of the entire field, and there’s a whole literature on approximating it.</p>
</section>
<section id="multi-head-attention" class="level3" data-number="10.3.3">
<h3 data-number="10.3.3" class="anchored" data-anchor-id="multi-head-attention"><span class="header-section-number">10.3.3</span> Multi-Head Attention</h3>
<p>One attention operation produces one set of weights — one notion of what is relevant. That is limiting, because different kinds of relevance coexist.</p>
<p><strong>Multi-head attention</strong> runs <span class="math inline">\(h\)</span> attention operations in parallel on different learned projections of the same input, then concatenates:</p>
<p><span class="math display">\[\text{MultiHead}(Q,K,V) = \text{concat}(\text{head}_1, \ldots, \text{head}_h)\, W^O\]</span></p>
<p>Each head can specialize. In a forecasting model one head might track weekly position, another the annual cycle, another the effect of promotional flags — all attending over the same window at once.</p>
<p><strong>The cost is not what you would guess.</strong> Each head works in a lower-dimensional subspace of size <span class="math inline">\(d_{\text{model}}/h\)</span>, so eight heads cost about the same as one head at full width. You buy the diversity nearly for free.</p>
<p><span class="neutral smaller">Our model below uses <code>nhead=4</code> with <code>d_model=64</code> — four heads of 16 dimensions each.</span></p>
<p>One attention operation produces one set of weights — one notion of what is relevant. That’s limiting, because different kinds of relevance coexist in the same sequence.</p>
<p><strong>Multi-head attention</strong> runs h attention operations in parallel, on different learned projections of the same input, then concatenates the results.</p>
<p>Each head can specialize. In a forecasting model, one head might track position within the month, another the annual cycle, another the effect of promotional flags — all attending over the same window simultaneously. And the cost is not what you’d guess.</p>
<p>You might expect eight heads to cost eight times one head. They don’t. Each head works in a <strong>lower-dimensional subspace</strong> — d-model divided by h. So eight heads of sixteen dimensions each cost about the same as one head of one hundred twenty-eight.</p>
<p>You’re not adding capacity. You’re partitioning the capacity you already had, and letting different partitions specialize. The diversity is close to free, which is why nobody uses a single head. Our model below uses four heads with d-model of sixty-four — four heads of sixteen dimensions.</p>
</section>
</section>
<section id="the-transformer-encoder" class="level2" data-number="10.4">
<h2 data-number="10.4" class="anchored" data-anchor-id="the-transformer-encoder"><span class="header-section-number">10.4</span> The Transformer Encoder</h2>
<p>Attention, plus the three pieces that make it trainable.</p>
<section id="the-encoder-block" class="level3" data-number="10.4.1">
<h3 data-number="10.4.1" class="anchored" data-anchor-id="the-encoder-block"><span class="header-section-number">10.4.1</span> The Encoder Block</h3>
<p>A Transformer encoder layer is four components in a fixed arrangement.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Multi-head attention</strong></td>
<td>Every position attends to every position.</td>
</tr>
<tr class="even">
<td><strong>Residual + LayerNorm</strong></td>
<td><span class="math inline">\(\mathbf{z} = \text{LayerNorm}(\mathbf{x} + \text{MultiHead}(\mathbf{x}))\)</span>. The skip connection from Lecture 8, doing the same job.</td>
</tr>
<tr class="odd">
<td><strong>Feed-forward sublayer</strong></td>
<td>A small MLP applied to each position independently — the Lecture 7 network, at every step.</td>
</tr>
<tr class="even">
<td><strong>Residual + LayerNorm</strong></td>
<td>Again, around the feed-forward block.</td>
</tr>
</tbody>
</table>
<p>Stack <span class="math inline">\(N\)</span> of those and you have the encoder. Nothing in the block is new to you except attention itself — the residual connections are ResNet’s, and the feed-forward sublayer is the network from Lecture 7.</p>
<p><strong>One thing is conspicuously missing, and it is not an oversight.</strong> Nothing above depends on the <em>order</em> of the input.</p>
<p>A Transformer encoder layer is four components in a fixed arrangement, and the good news is that you already know three of them. <strong>Multi-head attention</strong> — every position attends to every position. That’s the new part.</p>
<p><strong>Residual plus LayerNorm</strong> — z equals LayerNorm of x plus MultiHead of x. That’s the ResNet skip connection from Lecture 8, doing exactly the same job: giving the gradient an additive path home.</p>
<p><strong>A feed-forward sublayer</strong> — a small MLP applied to each position independently. That is literally the network from Lecture 7, run at every time step. <strong>Residual and LayerNorm again</strong>, this time around the feed-forward block.</p>
<p>Stack N of those and you have the encoder. Nothing in the block is new to you except attention itself.</p>
<p>That is genuinely worth pausing on. The architecture that reorganized machine learning is one new mechanism, wrapped in a residual connection from 2015 and a two-layer network from the 1980s.</p>
<p>Progress in this field often looks like that from the inside — not a wholesale reinvention, but one new component slotted into scaffolding that already worked. It’s a reason to learn components rather than model names.</p>
<p>And one thing is conspicuously missing. It is not an oversight, and I want you to spot it before I say it.</p>
<p>Look at every operation in that block. Attention: a weighted average over positions. Feed-forward: applied to each position independently. LayerNorm: per position. Residual: per position. <strong>Nothing in there depends on the <em>order</em> of the input.</strong></p>
</section>
<section id="positional-encoding-attention-cannot-tell-time" class="level3" data-number="10.4.2">
<h3 data-number="10.4.2" class="anchored" data-anchor-id="positional-encoding-attention-cannot-tell-time"><span class="header-section-number">10.4.2</span> Positional Encoding: Attention Cannot Tell Time</h3>
<p>Attention computes a weighted average over positions. Averaging does not care about order — shuffle the input sequence and every attention output is unchanged.</p>
<p><strong>Attention is permutation-invariant.</strong> For language that is fatal, and for forecasting it is worse: a model that cannot distinguish last week from thirty weeks ago is not forecasting at all.</p>
<p>The fix is to add position information to the input itself, before attention sees it. The original paper uses fixed sinusoids of different frequencies:</p>
<p><span class="math display">\[PE_{(t, 2i)} = \sin\!\left(\frac{t}{10000^{2i/d}}\right), \qquad PE_{(t, 2i+1)} = \cos\!\left(\frac{t}{10000^{2i/d}}\right)\]</span></p>
<p>Each position gets a distinct pattern across dimensions, and nearby positions get similar patterns — so the model can learn relative distance, not just absolute index.</p>
<p><strong>We measure what removing it costs on the next slide but one.</strong></p>
<p>Let’s make that precise, because it’s the most important slide in the lecture.</p>
<p>Attention computes a weighted average over positions. Averaging does not care about order. Shuffle the input sequence, and every attention output is <strong>unchanged</strong>. The technical term is that attention is <strong>permutation-invariant</strong>.</p>
<p>For language that’s fatal — “dog bites man” and “man bites dog” would be identical inputs. For forecasting it’s arguably worse. A model that cannot distinguish last week from thirty weeks ago is not forecasting at all; it’s computing a weighted average of an unordered bag of numbers. So the fix is to add position information <strong>to the input itself</strong>, before attention ever sees it.</p>
<p>The original paper uses fixed sinusoids at different frequencies — sines on the even dimensions, cosines on the odd ones, with wavelengths that grow geometrically.</p>
<p>Two properties make that work. Each position gets a <strong>distinct</strong> pattern across dimensions, so the model can tell positions apart. And <strong>nearby positions get similar patterns</strong>, so the model can learn relative distance rather than just absolute index. You can also learn the position vectors instead of fixing them; both are used in practice. We measure exactly what removing this costs, on the slide after next. Hold the question.</p>
</section>
<section id="why-transformers-took-over" class="level3" data-number="10.4.3">
<h3 data-number="10.4.3" class="anchored" data-anchor-id="why-transformers-took-over"><span class="header-section-number">10.4.3</span> Why Transformers Took Over</h3>
<p>Three properties, in the order they mattered commercially.</p>
<p><strong>Parallelism.</strong> Every position is computed at once, so training scales across hardware in a way recurrence never could. This, more than accuracy, is why the architecture won — it could absorb far more data and compute per unit of wall-clock time.</p>
<p><strong>Direct long-range paths.</strong> Any position reaches any other in one step, so there is no distance at which information degrades.</p>
<p><strong>Scale.</strong> The architecture kept improving as parameters and data grew, well past the point where earlier architectures plateaued. BERT <span class="citation" data-cites="Devlin2019">[@Devlin2019]</span> is an encoder stack used for understanding; GPT is a decoder stack used for generation. Both are this block, repeated.</p>
<div class="warningbox">
<p>Every one of those advantages is about <strong>large data and long sequences</strong>. Hold that thought against a 26-week window and 5,940 training examples.</p>
</div>
<p>Three properties, in the order they actually mattered commercially.</p>
<p><strong>Parallelism.</strong> Every position is computed at once. Training scales across hardware in a way recurrence never could. And I want to be clear that this — more than accuracy — is why the architecture won. It could absorb far more data and far more compute per unit of wall-clock time than an RNN. When your competitive advantage is training on more data, the architecture that trains faster wins by default.</p>
<p><strong>Direct long-range paths.</strong> Any position reaches any other in one step. There is no distance at which information degrades. Compare the ten-to-the-minus-nine we computed last week.</p>
<p><strong>Scale.</strong> The architecture kept getting better as parameters and data grew, well past the point where earlier architectures plateaued. That property is the entire foundation of the last five years of AI. BERT is an encoder stack used for understanding; GPT is a decoder stack used for generation. Both are this block, repeated. Read that list again with a forecaster’s eye, though. Every single one of those advantages is about <strong>large data and long sequences</strong>.</p>
<p>Hold that against what we actually have: a twenty-six-week window, and five thousand nine hundred forty training examples.</p>
</section>
</section>
<section id="transformers-for-time-series" class="level2" data-number="10.5">
<h2 data-number="10.5" class="anchored" data-anchor-id="transformers-for-time-series"><span class="header-section-number">10.5</span> Transformers for Time Series</h2>
<p>The implementation, the measurement, and an honest reading of it.</p>
<section id="transformer-encoder-in-pytorch" class="level3" data-number="10.5.1">
<h3 data-number="10.5.1" class="anchored" data-anchor-id="transformer-encoder-in-pytorch"><span class="header-section-number">10.5.1</span> Transformer Encoder in PyTorch</h3>
<div class="examplebox">
<div class="examplebox-title">
<p>Minimal forecasting encoder</p>
</div>
<div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>layer <span class="op">=</span> nn.TransformerEncoderLayer(d_model<span class="op">=</span><span class="dv">64</span>, nhead<span class="op">=</span><span class="dv">4</span>,</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>          dim_feedforward<span class="op">=</span><span class="dv">128</span>, dropout<span class="op">=</span><span class="fl">0.1</span>, batch_first<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="va">self</span>.enc <span class="op">=</span> nn.TransformerEncoder(layer, num_layers<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="va">self</span>.inp <span class="op">=</span> nn.Linear(n_features, <span class="dv">64</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="va">self</span>.fc  <span class="op">=</span> nn.Linear(<span class="dv">64</span>, <span class="dv">1</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> forward(<span class="va">self</span>, x):</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    h <span class="op">=</span> <span class="va">self</span>.inp(x) <span class="op">+</span> <span class="va">self</span>.pe      <span class="co"># position must be added</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="va">self</span>.fc(<span class="va">self</span>.enc(h)[:, <span class="op">-</span><span class="dv">1</span>, :]).squeeze(<span class="op">-</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>nn.TransformerEncoderLayer</code> gives you the whole block — but not the positional encoding. You add that yourself, and forgetting is a silent failure.</p>
<p><span class="neutral smaller">Multi-step forecasting also needs a causal mask.</span></p>
<p><code>nn.TransformerEncoderLayer</code> gives you the entire block — multi-head attention, both residuals, both LayerNorms, the feed-forward sublayer. <code>nn.TransformerEncoder</code> stacks N of them. You add a linear layer to project your features up to d-model, and another to project down to one output. Note <code>batch_first=True</code> again, giving <code>(batch, seq_len, features)</code> — same as the LSTM, opposite of <code>Conv1d</code>. And here is the one that will cost someone in this room a weekend.</p>
<p><code>nn.TransformerEncoderLayer</code> gives you the whole block — <strong>but not the positional encoding.</strong></p>
<p>You add that yourself. It’s the <code>+ self.pe</code> on the forward pass. And if you forget it, PyTorch does not complain. There’s no error, no warning, no shape mismatch. The model trains perfectly happily on an unordered bag of weeks and returns a forecast.</p>
<p>It’s a <strong>silent failure</strong>, which by now you should recognize as the most dangerous kind. We’ll quantify it in two slides.</p>
<p>Add it to the catalogue we’ve been building all semester. <code>KFold</code> on a time series. Scaling outside the fold. A rolling feature you forgot to shift. <code>shuffle=True</code> on a DataLoader whose rows are ordered in time. And now a Transformer with no positional encoding.</p>
<p>Not one of those raises an exception. Every one of them returns a plausible number. The only defence is procedural — you check them because they’re on a list, not because something broke.</p>
<p>One aside: for multi-step forecasting you also need a causal mask, so position t can’t attend to positions after it. We’re doing one-step-ahead, so we don’t need it here — but if you extend this in your project, that’s the thing to look up.</p>
</section>
<section id="does-it-work" class="level3" data-number="10.5.2">
<h3 data-number="10.5.2" class="anchored" data-anchor-id="does-it-work"><span class="header-section-number">10.5.2</span> Does It Work?</h3>
<p>Same weekly panel, same 26-week windows, same test block as everything since Homework 3.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Model</th>
<th style="text-align: right;">Test RMSE</th>
<th style="text-align: right;">Parameters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>LASSO, 46 engineered features</td>
<td style="text-align: right;"><strong>744</strong></td>
<td style="text-align: right;">46</td>
</tr>
<tr class="even">
<td>XGBoost</td>
<td style="text-align: right;">781</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="odd">
<td>Vanilla RNN</td>
<td style="text-align: right;"><strong>842</strong></td>
<td style="text-align: right;">4,545</td>
</tr>
<tr class="even">
<td>Random forest</td>
<td style="text-align: right;">899</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="odd">
<td>LSTM</td>
<td style="text-align: right;">987</td>
<td style="text-align: right;">17,985</td>
</tr>
<tr class="even">
<td><strong>Transformer encoder</strong>, 2 layers</td>
<td style="text-align: right;"><strong>990</strong></td>
<td style="text-align: right;">67,329</td>
</tr>
<tr class="odd">
<td>1D CNN, best variant</td>
<td style="text-align: right;">1,032</td>
<td style="text-align: right;">8,161</td>
</tr>
<tr class="even">
<td>Seasonal naive</td>
<td style="text-align: right;">2,152</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p>The Transformer beats the CNN and <strong>ties the LSTM</strong> — 990 against 987, a difference far smaller than the run-to-run spread. It loses to a vanilla RNN holding <strong>one-fifteenth</strong> as many parameters, and to a 46-coefficient linear model.</p>
<p>LASSO with forty-six engineered features: seven forty-four. XGBoost: seven eighty-one. Vanilla RNN: eight forty-two, on four and a half thousand parameters. Random forest: eight ninety-nine. LSTM: nine eighty-seven. <strong>Transformer encoder, two layers: nine ninety</strong> — on sixty-seven thousand parameters. Best CNN: one thousand thirty-two. Seasonal naive: twenty-one fifty-two.</p>
<p>So: the Transformer beats the CNN, and it <strong>ties the LSTM</strong> — nine ninety against nine eighty-seven, a difference far smaller than the run-to-run spread. Calling that a win in either direction would be reading noise.</p>
<p>And it loses to a vanilla RNN holding <strong>one-fifteenth</strong> as many parameters. And to a forty-six-coefficient linear model.</p>
<p>That is the state-of-the-art architecture of the last decade, finishing sixth of eight on our data. Next slide is why, and the reason is not that we implemented it badly.</p>
<p>Look at the parameter column once before we move on, because the trend across the whole table is the real story of these three lectures.</p>
<p>Four and a half thousand parameters bought eight forty-two. Eighteen thousand bought nine eighty-seven. Sixty-seven thousand bought nine ninety. And forty-six coefficients bought seven forty-four.</p>
<p>Model size and accuracy are running in <strong>opposite directions</strong> on this dataset. That is not a universal law — on a large enough corpus the ordering flips entirely, which is precisely why these architectures exist. But on the data in front of you, more capacity has bought worse forecasts every single time.</p>
</section>
<section id="reading-that-result-honestly" class="level3" data-number="10.5.3">
<h3 data-number="10.5.3" class="anchored" data-anchor-id="reading-that-result-honestly"><span class="header-section-number">10.5.3</span> Reading That Result Honestly</h3>
<p>Every advantage on the “why Transformers took over” slide is an advantage <em>at scale</em>, and this problem has none of the scale.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Parallel computation</strong></td>
<td>Real, but irrelevant — the RNN trains in seconds either way.</td>
</tr>
<tr class="even">
<td><strong>Direct long-range paths</strong></td>
<td>Worth little when the signal is dominated by recent weeks.</td>
</tr>
<tr class="odd">
<td><strong>Scales with data</strong></td>
<td>5,940 training windows is not the regime where that pays.</td>
</tr>
</tbody>
</table>
<p><strong>And positional encoding is doing real work, which we can measure.</strong> Remove it and the same model must forecast from an unordered bag of 26 weeks:</p>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td>Transformer <strong>with</strong> positional encoding</td>
<td style="text-align: right;"><strong>990</strong></td>
</tr>
<tr class="even">
<td>Transformer <strong>without</strong> positional encoding</td>
<td style="text-align: right;">1,282</td>
</tr>
</tbody>
</table>
<p><span class="key-result"><strong>292 RMSE</strong></span> — dropping it below even the 1D CNN. That gap is the price of permutation invariance, and the reason the sinusoids exist.</p>
<p>Go back to slide twelve — the three advantages — and take them one at a time against this problem.</p>
<p><strong>Parallel computation.</strong> Completely real. And completely irrelevant here: the RNN trains in seconds either way. Parallelism matters when training time is your binding constraint. Ours is about ninety seconds.</p>
<p><strong>Direct long-range paths.</strong> Real, and worth very little when the signal is dominated by the recent past. Attention’s superpower is reaching week t minus fifty-two cheaply. Our data mostly wants week t minus one.</p>
<p><strong>Scales with data.</strong> True, and five thousand nine hundred forty training windows is simply not the regime where that pays. Transformers overtake other architectures somewhere, but that somewhere is orders of magnitude from here.</p>
<p>But I don’t want you to leave thinking the mechanism did nothing, because one part of it is doing very visible work — and we can measure it.</p>
<p>Take the same model and remove the positional encoding. Now it has to forecast from an unordered bag of twenty-six weeks. With positional encoding: nine ninety. Without: <strong>one thousand two hundred eighty-two.</strong> That’s a penalty of <strong>two hundred ninety-two RMSE</strong> — which drops it below even the 1D CNN.</p>
<p>That gap is the price of permutation invariance, and it’s the reason the sinusoids exist. It also tells you the model genuinely is using temporal position when you give it to it.</p>
<p>And remember: forgetting that one line produces no error message. It produces a model that is twenty-nine percent worse and looks completely normal.</p>
</section>
</section>
<section id="key-takeaways" class="level2" data-number="10.6">
<h2 data-number="10.6" class="anchored" data-anchor-id="key-takeaways"><span class="header-section-number">10.6</span> Key Takeaways</h2>
<p>Six architectures, one series, and what the ranking actually taught us.</p>
<section id="sequence-architecture-comparison" class="level3" data-number="10.6.1">
<h3 data-number="10.6.1" class="anchored" data-anchor-id="sequence-architecture-comparison"><span class="header-section-number">10.6.1</span> Sequence Architecture Comparison</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Architecture</th>
<th>Long range</th>
<th>Parallel</th>
<th>Needs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1D CNN</td>
<td>receptive field only</td>
<td>yes</td>
<td>modest data</td>
</tr>
<tr class="even">
<td>Vanilla RNN</td>
<td>$$10–30 steps</td>
<td>no</td>
<td>modest data</td>
</tr>
<tr class="odd">
<td>LSTM</td>
<td>hundreds of steps</td>
<td>no</td>
<td>more data</td>
</tr>
<tr class="even">
<td>Transformer</td>
<td>unlimited, <span class="math inline">\(O(T^2)\)</span></td>
<td><strong>yes</strong></td>
<td><strong>much more data</strong></td>
</tr>
</tbody>
</table>
<p><strong>Choose by the structure of your problem, not by recency of the architecture.</strong> Short window and recent-lag signal: a plain RNN, or honestly a linear model. Long sequences, abundant data, dependencies at arbitrary distance: a Transformer, and nothing else comes close.</p>
<p>That second case is language, which is why this architecture reshaped that field and has been slower to displace gradient boosting in tabular forecasting — where the M5 competition was won by ensembles of exactly the methods in Lectures 5 and 6.</p>
<p>Four architectures on three axes. Long range: the CNN sees its receptive field only, the RNN about ten to thirty steps, the LSTM hundreds, the Transformer unlimited — at quadratic cost. Parallel: CNN yes, RNN no, LSTM no, Transformer yes. Data needed: modest, modest, more, and much more. Choose by the <strong>structure of your problem</strong>, not by the recency of the architecture.</p>
<p>Short window, signal in recent lags? A plain RNN — or honestly, a linear model with good features, which is what won here. Long sequences, abundant data, dependencies at arbitrary distance? A Transformer, and nothing else comes close.</p>
<p>That second case is language. Which is exactly why this architecture reshaped that field, and why it has been much slower to displace gradient boosting in tabular forecasting — where, notably, the M5 competition itself was won by ensembles of the methods you learned in Lectures 5 and 6. Not by a Transformer. By gradient boosting. Let me anticipate a reasonable objection: if this architecture loses here, why spend an hour on it?</p>
<p>Two answers. The first is that you now have a <em>reason</em> — you can say, before fitting anything, that a twenty-six-week window with recent-lag signal and six thousand training examples is not the regime where attention pays. That prediction-in-advance is worth far more than the fitted number.</p>
<p>The second is that most of you will encounter this architecture outside forecasting, in tools you use daily. Understanding that it is a soft lookup with learned weights, that it is permutation-invariant unless told otherwise, and that its advantages are advantages at scale — that understanding transfers well beyond this course.</p>
</section>
<section id="lecture-9-part-2-key-takeaways" class="level3" data-number="10.6.2">
<h3 data-number="10.6.2" class="anchored" data-anchor-id="lecture-9-part-2-key-takeaways"><span class="header-section-number">10.6.2</span> Lecture 9 Part 2: Key Takeaways</h3>
<div class="keybox">
<ol type="1">
<li><p><strong>Attention</strong> is a learned soft lookup: score every query against every key, softmax the scores, average the values. Distance in the sequence costs nothing.</p></li>
<li><p>The price is <strong>quadratic</strong> in sequence length — fine at 26 steps, the central constraint at 10,000.</p></li>
<li><p><strong>Multi-head</strong> attention runs several notions of relevance in parallel, at roughly the cost of one, by splitting the dimension.</p></li>
<li><p>An encoder block is attention <span class="math inline">\(+\)</span> <strong>residual</strong> <span class="math inline">\(+\)</span> LayerNorm <span class="math inline">\(+\)</span> a feed-forward sublayer. Only attention is new — the residuals are ResNet, the sublayer is Lecture 7.</p></li>
<li><p><strong>Attention is permutation-invariant</strong>, so position must be added explicitly. PyTorch does not do this for you, and omitting it fails silently.</p></li>
<li><p>On our panel the Transformer <strong>tied the LSTM</strong>, beat the CNN, and lost to a vanilla RNN with <strong>one-fifteenth</strong> the parameters. Its advantages are advantages at scale.</p></li>
</ol>
</div>
<p><span class="neutral">Next: Bayesian Statistics I — a different answer to the question of what a forecast should tell you.</span></p>
<p>One. Attention is a learned soft lookup: score every query against every key, softmax the scores, average the values. Distance in the sequence costs nothing.</p>
<p>Two. The price is quadratic in sequence length — irrelevant at twenty-six steps, the central constraint at ten thousand.</p>
<p>Three. Multi-head attention runs several notions of relevance in parallel, at roughly the cost of one, by splitting the dimension rather than adding to it.</p>
<p>Four. An encoder block is attention plus residual plus LayerNorm plus a feed-forward sublayer. Only attention is new — the residuals are ResNet, the sublayer is Lecture 7.</p>
<p>Five. Attention is <strong>permutation-invariant</strong>, so position has to be added explicitly. PyTorch does not do it for you, and omitting it fails silently — two hundred ninety-two RMSE, no error message.</p>
<p>And six. On our panel the Transformer tied the LSTM, beat the CNN, and lost to a vanilla RNN with one-fifteenth the parameters. Its advantages are advantages <strong>at scale</strong>, and this problem has none of the scale.</p>
<p>Next time we change the question entirely. For ten weeks every model has handed you one number per period. Bayesian methods hand you a distribution — and that turns out to answer questions a point forecast simply cannot.</p>
</section>
<section id="references" class="level3" data-number="10.6.3">
<h3 data-number="10.6.3" class="anchored" data-anchor-id="references"><span class="header-section-number">10.6.3</span> References</h3>
<div id="refs" role="list" style="display: none">

</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/Lecture09_Part1_RNN_LSTM.html" class="pagination-link" aria-label="RNNs and LSTMs">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">RNNs and LSTMs</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/Lecture10_BayesianFoundations.html" class="pagination-link" aria-label="Bayesian Statistics I --- Foundations">
        <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Bayesian Statistics I — Foundations</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>