<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.33">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Tree Ensembles: Random Forests &amp; Boosted Trees – Business Forecasting</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/Lecture06_Regularization.html" rel="next">
<link href="../chapters/Lecture04_DecisionTrees.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-c1b08d31956f1824f457e0b6984faaea.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/Lecture05_TreeEnsembles.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Tree Ensembles: Random Forests &amp; Boosted Trees</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Business Forecasting</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture01_ETS_Eval.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction, Exponential Smoothing &amp; Forecast Evaluation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture02_ARIMA_VAR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">ARIMA, VAR &amp; Multivariate Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture03_GAMs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Generalized Additive Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture04_DecisionTrees.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Decision Trees</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture05_TreeEnsembles.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Tree Ensembles: Random Forests &amp; Boosted Trees</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture06_Regularization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Regularization &amp; Model Selection</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture07_NeuralNets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Introduction to Neural Networks</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture08_CNNs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">CNN Architectures</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture09_Part1_RNN_LSTM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">RNNs and LSTMs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture09_Part2_Transformers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Transformers</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture10_BayesianFoundations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Bayesian Statistics I — Foundations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture11_Part1_BayesianTS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Bayesian Statistics II — Time Series</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture11_Part2_Hierarchical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Bayesian Statistics II — Hierarchical Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture12_BayesianRegression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Bayesian Statistics III — Bayesian Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture13_Synthesis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Synthesis — What the Semester Measured</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#lecture-outline" id="toc-lecture-outline" class="nav-link active" data-scroll-target="#lecture-outline"><span class="header-section-number">5.1</span> Lecture Outline</a></li>
  <li><a href="#from-single-trees-to-ensembles" id="toc-from-single-trees-to-ensembles" class="nav-link" data-scroll-target="#from-single-trees-to-ensembles"><span class="header-section-number">5.2</span> From Single Trees to Ensembles</a>
  <ul class="collapse">
  <li><a href="#the-wisdom-of-crowds" id="toc-the-wisdom-of-crowds" class="nav-link" data-scroll-target="#the-wisdom-of-crowds"><span class="header-section-number">5.2.1</span> The Wisdom of Crowds</a></li>
  </ul></li>
  <li><a href="#bagging-bootstrap-aggregating" id="toc-bagging-bootstrap-aggregating" class="nav-link" data-scroll-target="#bagging-bootstrap-aggregating"><span class="header-section-number">5.3</span> Bagging: Bootstrap Aggregating</a>
  <ul class="collapse">
  <li><a href="#bagging-the-big-idea" id="toc-bagging-the-big-idea" class="nav-link" data-scroll-target="#bagging-the-big-idea"><span class="header-section-number">5.3.1</span> Bagging: The Big Idea</a></li>
  <li><a href="#out-of-bag-oob-error-free-cross-validation" id="toc-out-of-bag-oob-error-free-cross-validation" class="nav-link" data-scroll-target="#out-of-bag-oob-error-free-cross-validation"><span class="header-section-number">5.3.2</span> Out-of-Bag (OOB) Error: Free Cross-Validation</a></li>
  </ul></li>
  <li><a href="#random-forests-decorrelating-the-trees" id="toc-random-forests-decorrelating-the-trees" class="nav-link" data-scroll-target="#random-forests-decorrelating-the-trees"><span class="header-section-number">5.4</span> Random Forests: Decorrelating the Trees</a>
  <ul class="collapse">
  <li><a href="#the-problem-bagging-does-not-fully-solve" id="toc-the-problem-bagging-does-not-fully-solve" class="nav-link" data-scroll-target="#the-problem-bagging-does-not-fully-solve"><span class="header-section-number">5.4.1</span> The Problem Bagging Does Not Fully Solve</a></li>
  <li><a href="#random-forest-hyperparameters" id="toc-random-forest-hyperparameters" class="nav-link" data-scroll-target="#random-forest-hyperparameters"><span class="header-section-number">5.4.2</span> Random Forest Hyperparameters</a></li>
  </ul></li>
  <li><a href="#feature-importance-and-interpretation" id="toc-feature-importance-and-interpretation" class="nav-link" data-scroll-target="#feature-importance-and-interpretation"><span class="header-section-number">5.5</span> Feature Importance and Interpretation</a>
  <ul class="collapse">
  <li><a href="#random-forest-feature-importance-molnar2022" id="toc-random-forest-feature-importance-molnar2022" class="nav-link" data-scroll-target="#random-forest-feature-importance-molnar2022"><span class="header-section-number">5.5.1</span> Random Forest Feature Importance <span class="citation" data-cites="Molnar2022">[@Molnar2022]</span></a></li>
  <li><a href="#random-forest-in-python" id="toc-random-forest-in-python" class="nav-link" data-scroll-target="#random-forest-in-python"><span class="header-section-number">5.5.2</span> Random Forest in Python</a></li>
  </ul></li>
  <li><a href="#gradient-boosting" id="toc-gradient-boosting" class="nav-link" data-scroll-target="#gradient-boosting"><span class="header-section-number">5.6</span> Gradient Boosting</a>
  <ul class="collapse">
  <li><a href="#boosting-vs.-bagging-the-core-difference" id="toc-boosting-vs.-bagging-the-core-difference" class="nav-link" data-scroll-target="#boosting-vs.-bagging-the-core-difference"><span class="header-section-number">5.6.1</span> Boosting vs.&nbsp;Bagging: The Core Difference</a></li>
  <li><a href="#the-gradient-boosting-algorithm" id="toc-the-gradient-boosting-algorithm" class="nav-link" data-scroll-target="#the-gradient-boosting-algorithm"><span class="header-section-number">5.6.2</span> The Gradient Boosting Algorithm</a></li>
  </ul></li>
  <li><a href="#xgboost" id="toc-xgboost" class="nav-link" data-scroll-target="#xgboost"><span class="header-section-number">5.7</span> XGBoost</a>
  <ul class="collapse">
  <li><a href="#xgboost-three-advances-chen2016" id="toc-xgboost-three-advances-chen2016" class="nav-link" data-scroll-target="#xgboost-three-advances-chen2016"><span class="header-section-number">5.7.1</span> XGBoost: Three Advances <span class="citation" data-cites="Chen2016">[@Chen2016]</span></a></li>
  <li><a href="#xgboost-key-hyperparameters" id="toc-xgboost-key-hyperparameters" class="nav-link" data-scroll-target="#xgboost-key-hyperparameters"><span class="header-section-number">5.7.2</span> XGBoost: Key Hyperparameters</a></li>
  <li><a href="#xgboost-in-python" id="toc-xgboost-in-python" class="nav-link" data-scroll-target="#xgboost-in-python"><span class="header-section-number">5.7.3</span> XGBoost in Python</a></li>
  </ul></li>
  <li><a href="#key-takeaways-and-roadmap" id="toc-key-takeaways-and-roadmap" class="nav-link" data-scroll-target="#key-takeaways-and-roadmap"><span class="header-section-number">5.8</span> Key Takeaways and Roadmap</a>
  <ul class="collapse">
  <li><a href="#tree-methods-which-one-when" id="toc-tree-methods-which-one-when" class="nav-link" data-scroll-target="#tree-methods-which-one-when"><span class="header-section-number">5.8.1</span> Tree Methods: Which One When</a></li>
  <li><a href="#lecture-5-key-takeaways" id="toc-lecture-5-key-takeaways" class="nav-link" data-scroll-target="#lecture-5-key-takeaways"><span class="header-section-number">5.8.2</span> Lecture 5: Key Takeaways</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">5.8.3</span> References</a></li>
  </ul></li>
  <li><a href="#timing-guide" id="toc-timing-guide" class="nav-link" data-scroll-target="#timing-guide"><span class="header-section-number">5.9</span> Timing guide</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Tree Ensembles: Random Forests &amp; Boosted Trees</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><em>Lecture 5 of ECON 8310.</em></p>
<section id="lecture-outline" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="lecture-outline"><span class="header-section-number">5.1</span> Lecture Outline</h2>
<ol type="1">
<li>From Single Trees to Ensembles</li>
<li>Bagging: Bootstrap Aggregating</li>
<li>Random Forests: Decorrelating the Trees</li>
<li>Feature Importance and Interpretation</li>
<li>Gradient Boosting</li>
<li>XGBoost</li>
<li>Key Takeaways</li>
</ol>
<p>Five parts. From single trees to ensembles. Bagging. Random forests. Feature importance. Then gradient boosting and XGBoost.</p>
</section>
<section id="from-single-trees-to-ensembles" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="from-single-trees-to-ensembles"><span class="header-section-number">5.2</span> From Single Trees to Ensembles</h2>
<p>Averaging many imperfect models can outperform any single model.</p>
<p>Part one, and it starts with an observation that has nothing to do with statistics.</p>
<section id="the-wisdom-of-crowds" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="the-wisdom-of-crowds"><span class="header-section-number">5.2.1</span> The Wisdom of Crowds</h3>
<p>A single expert can be wrong. Average many <em>independent</em> estimates and the errors tend to cancel.</p>
<div class="examplebox">
<div class="examplebox-title">
<p>Classic Example: Guessing the Ox’s Weight</p>
</div>
<p>At a 1907 county fair, 800 people guessed the weight of an ox. No individual was very accurate — but the <strong>average of all 800 guesses</strong> came within one pound of the true weight.</p>
</div>
<p>The same principle transfers directly to models. A single decision tree is unstable and noisy — that was Lecture 4’s closing complaint. Train many trees on different versions of the data and average them, and the noise largely cancels while the signal survives.</p>
<p><strong>Ensembles work because independent errors cancel.</strong> And that word is doing real work: the <em>more independent</em> the individual predictions, the more variance averaging removes. Hold onto it — the entire difference between bagging and random forests turns on it.</p>
<p>In 1907, at a county fair, eight hundred people guessed the weight of an ox.</p>
<p>Francis Galton collected the guesses expecting to show that the crowd was foolish. Individually they were — almost nobody was close. But the <strong>average of all eight hundred guesses</strong> came within one pound of the true weight.</p>
<p>Why does that work? Because the errors were <em>independent</em>. Some people guessed high, some low, for unrelated reasons, and averaging cancelled them.</p>
<p>Now transfer that to models. A single decision tree is noisy — it splits somewhere slightly arbitrary and everything downstream inherits that arbitrariness. But if you train many trees on different versions of the data, each is noisy in a <em>different</em> way. Average them and the noise largely cancels while the signal, which they agree on, survives. I want you to notice the word doing all the work: <strong>independent</strong>.</p>
<p>Galton’s crowd worked because the guesses were unrelated. If eight hundred people had all overheard the same wrong estimate, averaging would have gained nothing.</p>
<p>Hold onto that. The entire difference between bagging and random forests — the whole reason random forests exist — turns on that one word.</p>
</section>
</section>
<section id="bagging-bootstrap-aggregating" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="bagging-bootstrap-aggregating"><span class="header-section-number">5.3</span> Bagging: Bootstrap Aggregating</h2>
<p>Train many trees on bootstrap samples; average their predictions.</p>
<p>Part two. Bootstrap aggregating.</p>
<section id="bagging-the-big-idea" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="bagging-the-big-idea"><span class="header-section-number">5.3.1</span> Bagging: The Big Idea</h3>
<p><strong>Problem from Lecture 4:</strong> a single decision tree has very high variance — change a few training points and you get a completely different tree.</p>
<p><strong>Bagging solution <span class="citation" data-cites="Breiman1996">[@Breiman1996]</span>:</strong></p>
<ol type="1">
<li>Draw <span class="math inline">\(B\)</span> <strong>bootstrap samples</strong> (with replacement, same size as the original)</li>
<li>Fit one deep decision tree on each</li>
<li><strong>Average</strong> all <span class="math inline">\(B\)</span> predictions: <span class="math inline">\(\hat{y}_{\text{bag}} = \tfrac{1}{B}\sum_{b=1}^{B} \hat{f}^{(b)}(\mathbf{x})\)</span></li>
</ol>
<p><strong>Why it works.</strong> The variance of the averaged forecast is</p>
<p><span class="math display">\[\mathrm{Var}(\bar{f}) = \rho\sigma^2 + \tfrac{1-\rho}{B}\sigma^2,\]</span></p>
<p>where <span class="math inline">\(\rho\)</span> is the pairwise correlation between tree predictions. The second term shrinks as <span class="math inline">\(B\)</span> grows — so more trees never hurts. But the first term does not move at all.</p>
<p><strong>That leaves a floor at <span class="math inline">\(\rho\sigma^2\)</span></strong>, set by how alike the trees are rather than by how many you grow. Averaging a thousand nearly identical trees buys you almost nothing, and that is the problem the next section solves.</p>
<p>Three steps.</p>
<p>Draw <strong>B bootstrap samples</strong> — sample your training data with replacement, same size as the original. Because it’s with replacement, each sample gets some observations twice and misses others entirely. That’s the point: each sample is a slightly different view of the data.</p>
<p>Fit one deep tree on each. Deep — we’re not pruning. We <em>want</em> each tree to be low-bias and high-variance, because averaging is about to handle the variance. Then average all B predictions. Now the equation, which is the most important thing on this slide. The variance of the averaged forecast is <strong>rho sigma squared, plus one-minus-rho over B, sigma squared</strong>. Two terms. Look at what happens as B — the number of trees — grows.</p>
<p>The second term has B in the denominator, so it shrinks toward zero. That’s why more trees never hurts. The first term has no B in it at all. It does not move.</p>
<p>So you have a <strong>floor at rho sigma squared</strong>, where rho is the pairwise correlation between the trees’ predictions.</p>
<p>Read what that says. If your trees are highly correlated — rho near one — the floor is near sigma squared, and averaging a thousand of them buys you essentially nothing. You have grown a thousand trees and reproduced one. That’s Galton’s crowd overhearing each other. And it’s exactly the problem the next section solves.</p>
</section>
<section id="out-of-bag-oob-error-free-cross-validation" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="out-of-bag-oob-error-free-cross-validation"><span class="header-section-number">5.3.2</span> Out-of-Bag (OOB) Error: Free Cross-Validation</h3>
<p>Each bootstrap sample draws <span class="math inline">\(n\)</span> observations <em>with replacement</em>, so it contains about <strong>63%</strong> of the distinct training points. The remaining 37% are <strong>out-of-bag</strong> for that tree — a free test set, different for every tree:</p>
<ol type="1">
<li>For each observation <span class="math inline">\(i\)</span>, collect predictions only from the trees where <span class="math inline">\(i\)</span> was out-of-bag</li>
<li>Average them to get <span class="math inline">\(\hat{y}_i^{\text{OOB}}\)</span></li>
<li>Compute the RMSE across all observations</li>
</ol>
<p>Every one of those predictions came from a tree that never saw the observation — so the OOB RMSE is an honest out-of-sample estimate, and it lands close to 5-fold CV without refitting anything. In <code>sklearn</code> it is one argument: <code>RandomForestRegressor(oob_score=True)</code>.</p>
<div class="warningbox">
<p>Below about 1,000 observations the OOB estimate gets noisy, because each observation is out-of-bag for too few trees. On a weekly business series — a few hundred rows — use proper walk-forward CV instead.</p>
</div>
<p>A pleasant side effect of bootstrapping.</p>
<p>Each bootstrap sample draws n observations with replacement, so some get picked more than once and some not at all. Work through the probability and you find each sample contains about <strong>sixty-three percent</strong> of the distinct training points. Which means roughly <strong>thirty-seven percent are left out</strong> of any given tree. Those are the out-of-bag observations.</p>
<p>Here’s the trick. For observation <em>i</em>, collect predictions only from the trees where <em>i</em> was out-of-bag. Average those. Compute the RMSE across all observations.</p>
<p>Every one of those predictions came from a tree that <strong>never saw that observation</strong>. So the OOB error is an honest out-of-sample estimate — and you got it without setting aside a validation set or refitting anything. It falls out of the bootstrapping you were doing anyway. In sklearn it’s one argument: <code>oob_score=True</code>. One caution, and it’s the one that matters for this course.</p>
<p>Below about a thousand observations, OOB gets noisy — each observation is out-of-bag for too few trees, so its OOB prediction is an average over a small, unstable set.</p>
<p>Our weekly series have two hundred seventy-seven observations. That is well under a thousand. So on this data, use proper walk-forward cross-validation. OOB is a genuine convenience on large datasets and a trap on small ones, and business time series are almost always small.</p>
</section>
</section>
<section id="random-forests-decorrelating-the-trees" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="random-forests-decorrelating-the-trees"><span class="header-section-number">5.4</span> Random Forests: Decorrelating the Trees</h2>
<p>Restrict each split to a random subset of features so trees are less alike.</p>
<p>Part three. Decorrelating the trees.</p>
<section id="the-problem-bagging-does-not-fully-solve" class="level3" data-number="5.4.1">
<h3 data-number="5.4.1" class="anchored" data-anchor-id="the-problem-bagging-does-not-fully-solve"><span class="header-section-number">5.4.1</span> The Problem Bagging Does Not Fully Solve</h3>
<p>Recall the variance of the averaged forecast: <span class="math inline">\(\mathrm{Var}(\bar{f}) = \rho\sigma^2 + \tfrac{1-\rho}{B}\sigma^2\)</span>. More trees shrink the second term to nothing. The first term never moves.</p>
<div class="warningbox">
<p><strong>The correlation problem.</strong> If one feature dominates — and in forecasting it always does, because last year’s value is the best single predictor — then nearly every tree splits on it at the root. The trees end up near-identical, <span class="math inline">\(\rho\)</span> stays large, and bagging buys you very little.</p>
</div>
<p><strong>The Random Forest fix <span class="citation" data-cites="Breiman2001">[@Breiman2001]</span></strong> is almost absurdly simple: at each split, consider only a random subset of <span class="math inline">\(m &lt; p\)</span> features, and take the best split among <em>those</em>.</p>
<p>Sometimes the dominant feature is not in the candidate set, so the tree is forced to find its second-best story. Across hundreds of trees that produces genuinely different structures — <span class="math inline">\(\rho\)</span> falls, and the floor falls with it. You deliberately make each individual tree <em>worse</em> in order to make the ensemble better.</p>
<p>Back to the floor.</p>
<p>Why would trees end up correlated? Because of the greedy algorithm from last week. At the root, CART picks the single best split. If one feature is clearly the strongest predictor, then <em>every</em> tree picks it, and every tree starts the same way.</p>
<p>And in forecasting, one feature is essentially always dominant — last year’s value, or last week’s. So this isn’t an edge case. It’s the normal situation. The trees end up near-identical. Rho stays large. Bagging buys you very little. The Random Forest fix, from Breiman in 2001, is almost absurdly simple.</p>
<p>At each split, don’t consider all p features. Consider a random subset of <strong>m</strong>, and take the best split among <em>those</em>. That’s it. That’s the whole method.</p>
<p>Think about what it does. Sometimes the dominant feature simply isn’t in the candidate set. The tree is forced to find its second-best story — and then a third tree finds a different one. Across hundreds of trees you get genuinely different structures. Rho falls, and the floor falls with it.</p>
<p>And here’s the part I find genuinely elegant: <strong>you are deliberately making each individual tree worse in order to make the ensemble better.</strong> Any single random forest tree is a poorer model than a single bagged tree. It was handicapped. But the ensemble beats it, because the handicap bought independence. That is one of the more counterintuitive ideas in applied statistics, and it works.</p>
</section>
<section id="random-forest-hyperparameters" class="level3" data-number="5.4.2">
<h3 data-number="5.4.2" class="anchored" data-anchor-id="random-forest-hyperparameters"><span class="header-section-number">5.4.2</span> Random Forest Hyperparameters</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 33%">
<col style="width: 21%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th>Parameter</th>
<th>sklearn name</th>
<th>Default</th>
<th>Effect</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Number of trees</td>
<td><code>n_estimators</code></td>
<td>100</td>
<td>More = lower variance; plateaus ~500</td>
</tr>
<tr class="even">
<td>Max features/split</td>
<td><code>max_features</code></td>
<td><code>'sqrt'</code></td>
<td>Lower = more decorrelated</td>
</tr>
<tr class="odd">
<td>Max depth</td>
<td><code>max_depth</code></td>
<td>None</td>
<td>Limit only to reduce memory</td>
</tr>
<tr class="even">
<td>Min samples/leaf</td>
<td><code>min_samples_leaf</code></td>
<td>1</td>
<td>Higher = smoother predictions</td>
</tr>
<tr class="odd">
<td>OOB score</td>
<td><code>oob_score</code></td>
<td>False</td>
<td><code>True</code> gives a free CV estimate</td>
</tr>
</tbody>
</table>
<p><strong>Start with</strong> <code>n_estimators=500</code>, <code>max_features='sqrt'</code>, <code>min_samples_leaf=5</code>, <code>oob_score=True</code>. Note how few genuinely need tuning — <code>max_features</code> is the dial controlling <span class="math inline">\(\rho\)</span>, and the rest is close to fire-and-forget. That is most of why random forests make a good default.</p>
<p><span class="neutral smaller">Set <code>random_state=42</code>: a forest is random twice over, in the bootstrap samples and in the feature subsets.</span></p>
<p>Five parameters, and the striking thing is how few need attention.</p>
<p><code>n_estimators</code> — number of trees. More is better and plateaus around five hundred. There is no overfitting risk from adding trees; that’s the first term of the variance equation, which doesn’t care.</p>
<p><code>max_features</code> — <strong>this is the one that matters.</strong> It’s m from the previous slide. It is the dial controlling rho, and therefore the dial controlling the floor. Lower means more decorrelated trees. The <code>'sqrt'</code> default is a reasonable starting guess, not a law. <code>max_depth</code> — leave it at None. We want deep trees. <code>min_samples_leaf</code> — raise it to about five for smoother predictions. <code>oob_score</code> — set True if your dataset is large enough for it to mean anything.</p>
<p>Start with five hundred trees, <code>sqrt</code> features, <code>min_samples_leaf</code> of five.</p>
<p>And note the practical consequence: essentially one parameter needs real tuning. Compare that to what’s coming with XGBoost, where you’ll be juggling six. A large part of why random forests are the right default is that they are very hard to misconfigure.</p>
<p>Set <code>random_state=42</code>. A forest is random twice over — in the bootstrap samples <em>and</em> in the feature subsets — so without a seed your results move between runs and you’ll waste an hour wondering why.</p>
</section>
</section>
<section id="feature-importance-and-interpretation" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="feature-importance-and-interpretation"><span class="header-section-number">5.5</span> Feature Importance and Interpretation</h2>
<p>Which predictors matter most? RF gives a data-driven answer.</p>
<p>Part four. Which predictors matter?</p>
<section id="random-forest-feature-importance-molnar2022" class="level3" data-number="5.5.1">
<h3 data-number="5.5.1" class="anchored" data-anchor-id="random-forest-feature-importance-molnar2022"><span class="header-section-number">5.5.1</span> Random Forest Feature Importance <span class="citation" data-cites="Molnar2022">[@Molnar2022]</span></h3>
<div class="definitionbox">
<div class="definitionbox-title">
<p>Mean Decrease in Impurity (MDI)</p>
</div>
<p>For each feature <span class="math inline">\(j\)</span>, average the total reduction in node impurity across every split on <span class="math inline">\(j\)</span>, weighted by the fraction of observations reaching that node. Normalize to sum to 1.</p>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Feature (CA_1 FOODS, weekly)</th>
<th>Importance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>units_lag4</code></td>
<td>0.45</td>
</tr>
<tr class="even">
<td><code>units_lag1</code></td>
<td>0.18</td>
</tr>
<tr class="odd">
<td><code>units_lag52</code></td>
<td>0.11</td>
</tr>
<tr class="even">
<td><code>snap_days</code></td>
<td>0.08</td>
</tr>
<tr class="odd">
<td><code>units_lag2</code></td>
<td>0.04</td>
</tr>
<tr class="even">
<td><code>avg_price</code></td>
<td>0.04</td>
</tr>
</tbody>
</table>
<p>Read it as a screening device, not an explanation. <strong>MDI is biased</strong> toward features with many split points. <code>permutation_importance</code> — shuffle a column, see how much accuracy falls — is the honest alternative.</p>
<p>Mean decrease in impurity. For each feature, sum the variance reduction across every split where it was used, weighted by how many observations passed through that node. Normalize to one.</p>
<p>On our CA_1 food sales the ranking comes out: <strong>four-week lag at zero point four five</strong>, last week at zero point one eight, same week last year at zero point one one, and <strong>SNAP benefit days at zero point zero eight</strong> — ahead of price.</p>
<p>That SNAP result is worth pausing on. Nobody told the model that food sales spike when benefits are disbursed. It found it, and ranked it above price. That is a real business finding, and no linear specification would have surfaced it unless someone already suspected it. But read this as a screening device, not an explanation, because <strong>MDI is biased</strong>.</p>
<p>The bias is toward features with many possible split points. A continuous variable like price offers hundreds of thresholds to try. A binary flag offers one. The continuous variable gets more chances to look useful — not because it carries more signal, but because it had more opportunities.</p>
<p><code>permutation_importance</code> is the honest alternative: shuffle one column and measure how much accuracy falls. If shuffling it doesn’t hurt, it wasn’t doing anything. That’s a direct measurement rather than an accounting artifact.</p>
<p>Use MDI to narrow forty candidates to eight. Use permutation importance before you put a ranking in front of anyone who’ll act on it.</p>
</section>
<section id="random-forest-in-python" class="level3" data-number="5.5.2">
<h3 data-number="5.5.2" class="anchored" data-anchor-id="random-forest-in-python"><span class="header-section-number">5.5.2</span> Random Forest in Python</h3>
<div class="examplebox">
<div class="examplebox-title">
<p>sklearn Code Template</p>
</div>
<div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.ensemble <span class="im">import</span> RandomForestRegressor</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>rf <span class="op">=</span> RandomForestRegressor(n_estimators<span class="op">=</span><span class="dv">500</span>, max_features<span class="op">=</span><span class="st">'sqrt'</span>,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>                           min_samples_leaf<span class="op">=</span><span class="dv">5</span>, oob_score<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>                           random_state<span class="op">=</span><span class="dv">42</span>).fit(X_tr, y_tr)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(rf.oob_score_)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>importances <span class="op">=</span> rf.feature_importances_</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Model (CA_1 FOODS, 52-week test)</th>
<th>Test RMSE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Seasonal naïve</td>
<td>1,660</td>
</tr>
<tr class="even">
<td>Single deep tree</td>
<td>1,415</td>
</tr>
<tr class="odd">
<td><strong>Random Forest</strong></td>
<td><strong>1,020</strong></td>
</tr>
</tbody>
</table>
<p>The forest cuts RMSE roughly <strong>28%</strong> against a single deep tree, and is the first method in this course to beat the seasonal naive benchmark on this series.</p>
<p><span class="neutral smaller">What changed is not a better model of the series but a richer feature set — lags, price, and SNAP days are information ETS and ARIMA never had.</span></p>
<p>The code is four lines, and the results table is the interesting part.</p>
<p>On CA_1 food sales, fifty-two week test: seasonal naive at <strong>1,660</strong>. A single deep tree at <strong>1,415</strong>. The random forest at <strong>1,020</strong>. Two things.</p>
<p>The forest cuts RMSE about <strong>twenty-eight percent</strong> against the single tree. That’s the variance reduction, bought purely by averaging — same algorithm, same features, five hundred of them instead of one.</p>
<p>And it is the <strong>first method in this course to beat the seasonal naive benchmark on this series.</strong> In Homework 1 you found that exponential smoothing couldn’t. ARIMA couldn’t either. This does, comfortably. Now — be careful about the conclusion you draw, because the obvious one is wrong.</p>
<p>What changed is not that random forests model time series better than ARIMA. It’s that we gave this model <strong>information the others never had</strong>: lags, price, SNAP days, event flags. ETS and ARIMA only ever saw the series’ own history.</p>
<p>That’s the real lesson of the second half of this course. The gains from here are coming substantially from feature engineering, not from model sophistication. A random forest with one lag feature would lose to ARIMA. A random forest with a well-built feature set wins.</p>
</section>
</section>
<section id="gradient-boosting" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="gradient-boosting"><span class="header-section-number">5.6</span> Gradient Boosting</h2>
<p>Instead of averaging independent trees, fit each new tree to the errors of all previous trees.</p>
<p>Part five, and we change direction entirely.</p>
<section id="boosting-vs.-bagging-the-core-difference" class="level3" data-number="5.6.1">
<h3 data-number="5.6.1" class="anchored" data-anchor-id="boosting-vs.-bagging-the-core-difference"><span class="header-section-number">5.6.1</span> Boosting vs.&nbsp;Bagging: The Core Difference</h3>
<div class="columns">
<div class="column" style="width:48%;">
<p><strong>Bagging (Random Forest):</strong></p>
<ul>
<li>Trees built <strong>in parallel</strong>, independently</li>
<li>Each tree predicts <span class="math inline">\(y\)</span> directly</li>
<li>Averaging reduces <em>variance</em></li>
<li>More trees never reduces bias</li>
</ul>
</div><div class="column" style="width:48%;">
<p><strong>Boosting:</strong></p>
<ul>
<li>Trees built <strong>sequentially</strong></li>
<li>Each fits the <em>errors</em> of the ensemble so far</li>
<li>Reduces <em>bias</em> as well as variance</li>
<li>Will overfit if trees are too deep or too many</li>
</ul>
</div>
</div>
<p><strong>The intuition.</strong> Forecast 1 says $50,000; actual is $60,000, so the error is +$10,000. Forecast 2 does not predict sales at all — it predicts <em>that error</em>, and says “the first model was short by $10,000.” Add them: $60,000. Each stage corrects what remains, which is why boosting can fix a systematic bias that averaging never touches.</p>
<p>Bagging builds trees <strong>in parallel</strong> and independently. Each tries to predict y directly. Averaging reduces variance. And critically — adding more trees never reduces bias. If your trees are systematically wrong in the same direction, averaging preserves that exactly.</p>
<p>Boosting builds trees <strong>sequentially</strong>. Each new tree fits the <em>errors</em> of everything built so far. That reduces bias as well as variance — and it can overfit, which bagging essentially cannot. The intuition on the slide is the clearest version I know. Forecast one says fifty thousand dollars. The actual is sixty thousand. The error is plus ten thousand.</p>
<p>Now, forecast two does not try to predict sales at all. It tries to predict <strong>that error</strong>. It says: “the first model was short by about ten thousand.” Add them together: fifty plus ten is sixty.</p>
<p>Each stage corrects what remains. And notice this fixes something averaging cannot touch — if every bagged tree under-predicts December by the same amount, the average under-predicts December. Boosting sees that residual pattern and builds a tree specifically for it. Bagging attacks variance. Boosting attacks bias. That sentence is the whole slide.</p>
</section>
<section id="the-gradient-boosting-algorithm" class="level3" data-number="5.6.2">
<h3 data-number="5.6.2" class="anchored" data-anchor-id="the-gradient-boosting-algorithm"><span class="header-section-number">5.6.2</span> The Gradient Boosting Algorithm</h3>
<div class="definitionbox">
<div class="definitionbox-title">
<p>Gradient Boosting (squared-error loss)</p>
</div>
<p>Initialize <span class="math inline">\(F_0(\mathbf{x}) = \bar{y}\)</span>. For <span class="math inline">\(b = 1, \ldots, B\)</span>:</p>
<ol type="1">
<li>Compute residuals: <span class="math inline">\(r_i^{(b)} = y_i - F_{b-1}(\mathbf{x}_i)\)</span></li>
<li>Fit a shallow tree <span class="math inline">\(T_b\)</span> to <span class="math inline">\(\{(\mathbf{x}_i, r_i^{(b)})\}\)</span></li>
<li>Update: <span class="math inline">\(F_b = F_{b-1} + \eta\, T_b\)</span></li>
</ol>
<p>Final prediction: <span class="math inline">\(\hat{y} = F_B(\mathbf{x})\)</span></p>
</div>
<p>The trees are deliberately <strong>shallow</strong> — depth 3 to 6 — because each one only has to capture a small piece of the remaining error. The ensemble converges slowly and on purpose.</p>
<p><strong>The learning rate <span class="math inline">\(\eta\)</span> is the main dial.</strong> Small values (0.01–0.1) take a tiny step per tree: slower, needs more trees, far more robust. Large values (<span class="math inline">\(&gt; 0.3\)</span>) move fast and risk overshooting. The reliable recipe is a small <span class="math inline">\(\eta\)</span>, many trees, and <strong>early stopping</strong> — without which boosting will happily fit your noise.</p>
<p>Formally, three steps in a loop.</p>
<p>Start with the mean. Then repeatedly: compute the residuals, fit a shallow tree to those residuals, and add a fraction of that tree to the running prediction. Two design choices worth understanding.</p>
<p><strong>The trees are deliberately shallow</strong> — depth three to six. That’s the opposite of bagging, where we grew them deep. Here each tree only needs to capture a small piece of the remaining error, so a small tree is enough. A deep tree would fit the residual noise, and the next iteration would be trying to correct noise.</p>
<p><strong>The learning rate eta is the main dial.</strong> After fitting a tree to the residuals, you don’t add the whole thing — you add eta times it, where eta might be zero point zero five. Which means you deliberately under-correct at every step. Why on earth would you do that?</p>
<p>Because each tree is fitted to the residuals of one particular sample, so part of what it sees is noise. Take the full correction and you bake that noise in. Take five percent of it, five hundred times, and the noise averages out while the signal accumulates.</p>
<p>The reliable recipe is: small eta, many trees, and <strong>early stopping</strong>. Without early stopping, boosting will keep reducing training error until it has fitted your noise perfectly. Unlike bagging, this method genuinely can overfit — and it will if you let it.</p>
</section>
</section>
<section id="xgboost" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="xgboost"><span class="header-section-number">5.7</span> XGBoost</h2>
<p>Three improvements over vanilla boosting: second-order optimization, explicit regularization, and column subsampling.</p>
<p>The version that won everything.</p>
<section id="xgboost-three-advances-chen2016" class="level3" data-number="5.7.1">
<h3 data-number="5.7.1" class="anchored" data-anchor-id="xgboost-three-advances-chen2016"><span class="header-section-number">5.7.1</span> XGBoost: Three Advances <span class="citation" data-cites="Chen2016">[@Chen2016]</span></h3>
<ol type="1">
<li><strong>Newton step (second-order optimization).</strong> Uses the gradient <em>and</em> the curvature of the loss to choose each tree’s direction, so it converges in fewer trees than first-order boosting.</li>
<li><strong>Explicit regularization.</strong> Penalizes the number of leaves (<span class="math inline">\(\gamma\)</span>) and the magnitude of leaf weights (<span class="math inline">\(\lambda\)</span>) directly in the objective — so overfitting is controlled by the loss function rather than only by early stopping.</li>
<li><strong>Column subsampling.</strong> Borrowed straight from random forests: sample features per tree and per split, decorrelating the ensemble.</li>
</ol>
<p>Notice that the second advance is <em>exactly</em> the Ridge and LASSO idea from next week, applied to leaf weights instead of regression coefficients. <code>reg_lambda</code> is an <span class="math inline">\(\ell_2\)</span> penalty; <code>gamma</code> penalizes complexity the way <span class="math inline">\(\ell_1\)</span> does.</p>
<p><span class="neutral smaller">XGBoost dominated Kaggle tabular competitions from 2014–2018. <code>LightGBM</code> is faster on large data; <code>CatBoost</code> handles categoricals natively.</span></p>
<p>Three improvements over vanilla gradient boosting.</p>
<p><strong>The Newton step.</strong> Vanilla boosting uses the gradient — the direction of steepest descent. XGBoost also uses the second derivative, the curvature. Knowing how sharply the loss is bending lets you take a better-sized step, so it converges in fewer trees.</p>
<p><strong>Explicit regularization.</strong> This is the important one. XGBoost puts penalties directly in the objective — gamma on the number of leaves, lambda on the magnitude of the leaf weights. So overfitting is controlled by the loss function itself, not only by stopping early.</p>
<p><strong>Column subsampling.</strong> Borrowed straight from random forests: sample features per tree and per split. The decorrelation idea from slide nine, imported into boosting. Notice what that second advance actually is.</p>
<p><code>reg_lambda</code> penalizes the sum of squared leaf weights. That is an <strong>L2 penalty</strong> — it is Ridge regression, applied to leaf weights instead of regression coefficients. And <code>gamma</code> penalizes the count of leaves, which is what LASSO does to nonzero coefficients. You are seeing next week’s lecture, one week early, wearing different clothes.</p>
<p>That’s not a coincidence. Regularization is not a linear-model topic. It is how <em>every</em> flexible model is kept honest, and you’ll meet it a fourth time in Lecture 7 as weight decay and dropout.</p>
<p>XGBoost dominated Kaggle tabular competitions from 2014 to 2018. LightGBM is faster on large data; CatBoost handles categorical features natively. The ideas are the same.</p>
</section>
<section id="xgboost-key-hyperparameters" class="level3" data-number="5.7.2">
<h3 data-number="5.7.2" class="anchored" data-anchor-id="xgboost-key-hyperparameters"><span class="header-section-number">5.7.2</span> XGBoost: Key Hyperparameters</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Parameter</th>
<th>XGB name</th>
<th>Typical</th>
<th>Effect</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Number of trees</td>
<td><code>n_estimators</code></td>
<td>500–2000</td>
<td>More + small <span class="math inline">\(\eta\)</span> = better</td>
</tr>
<tr class="even">
<td>Learning rate</td>
<td><code>learning_rate</code></td>
<td>0.01–0.1</td>
<td>Smaller = more robust</td>
</tr>
<tr class="odd">
<td>Tree depth</td>
<td><code>max_depth</code></td>
<td>3–6</td>
<td>Shallow preferred</td>
</tr>
<tr class="even">
<td>Row subsample</td>
<td><code>subsample</code></td>
<td>0.7–0.9</td>
<td>Fraction of training rows per tree</td>
</tr>
<tr class="odd">
<td>Col. subsample</td>
<td><code>colsample_bytree</code></td>
<td>0.7–0.9</td>
<td>Feature fraction per tree</td>
</tr>
<tr class="even">
<td>L2 leaf penalty</td>
<td><code>reg_lambda</code></td>
<td>1</td>
<td>Ridge on leaf weights</td>
</tr>
</tbody>
</table>
<div class="keybox">
<p><strong>Practical starting point:</strong> <code>learning_rate=0.05</code>, <code>max_depth=4</code>, <code>n_estimators=1000</code> with early stopping on validation RMSE. Tune <code>max_depth</code> and <code>subsample</code> via <code>TimeSeriesSplit</code>.</p>
</div>
<p>Six parameters, against the random forest’s one that mattered. This is the cost of the extra accuracy.</p>
<p>Number of trees, five hundred to two thousand — high, because you’re pairing it with early stopping. Learning rate zero point zero one to zero point one. Depth three to six, shallow. Row subsample and column subsample around zero point eight. And <code>reg_lambda</code>, the Ridge penalty on leaf weights.</p>
<p>The two that interact most are <code>learning_rate</code> and <code>n_estimators</code>, and they trade off directly. Halve the learning rate and you need roughly twice the trees. Small eta with many trees is almost always better than large eta with few — you’re just paying for it in compute.</p>
<p>Practical starting point: learning rate zero point zero five, depth four, a thousand trees with early stopping on validation RMSE. Then tune depth and subsample by <code>TimeSeriesSplit</code>.</p>
</section>
<section id="xgboost-in-python" class="level3" data-number="5.7.3">
<h3 data-number="5.7.3" class="anchored" data-anchor-id="xgboost-in-python"><span class="header-section-number">5.7.3</span> XGBoost in Python</h3>
<div class="examplebox">
<div class="examplebox-title">
<p>Code Template</p>
</div>
<div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> xgb.XGBRegressor(n_estimators<span class="op">=</span><span class="dv">1000</span>, learning_rate<span class="op">=</span><span class="fl">0.05</span>,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>                         max_depth<span class="op">=</span><span class="dv">4</span>, subsample<span class="op">=</span><span class="fl">0.8</span>, colsample_bytree<span class="op">=</span><span class="fl">0.8</span>,</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>                         early_stopping_rounds<span class="op">=</span><span class="dv">50</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>model.fit(X_train, y_train, eval_set<span class="op">=</span>[(X_val, y_val)], verbose<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>eval_set</code> is what makes <code>early_stopping_rounds</code> work: XGBoost watches validation RMSE and halts when it stops improving, which is how you get away with setting <code>n_estimators</code> far higher than you need.</p>
<p><strong>The validation set must respect time.</strong> Build it with <code>TimeSeriesSplit</code> and hold out the final stretch as a true test set.</p>
<p><span class="neutral smaller">On macOS <code>xgboost</code> also needs OpenMP: <code>brew install libomp</code>, or the import fails.</span></p>
<p>The code, and one argument that matters more than it looks.</p>
<p><code>eval_set</code> is what makes <code>early_stopping_rounds</code> work. XGBoost watches RMSE on that set and halts when it stops improving. That’s how you get away with setting a thousand trees — you’re not committing to a thousand, you’re setting a ceiling and letting the data decide.</p>
<p>And the validation set has to respect time. Build it with <code>TimeSeriesSplit</code>, hold out the final stretch as a true test set, and never let a random split choose which weeks the model sees.</p>
<p>If you use a random split here, early stopping will pick the iteration that best predicts weeks the model has effectively already seen. You’ll stop too late, ship an overfitted model, and your diagnostics will look excellent.</p>
<p>One practical note that will save you an evening. On macOS, <code>xgboost</code> needs the OpenMP runtime. If you get an error about <code>libomp.dylib</code> not loading, run <code>brew install libomp</code>. The Python package installs fine and then fails at import, which makes it look like a code problem when it’s a system library problem.</p>
</section>
</section>
<section id="key-takeaways-and-roadmap" class="level2" data-number="5.8">
<h2 data-number="5.8" class="anchored" data-anchor-id="key-takeaways-and-roadmap"><span class="header-section-number">5.8</span> Key Takeaways and Roadmap</h2>
<p>Bagging reduces variance; boosting reduces bias. Together they cover most of what tabular forecasting needs.</p>
<p>Let’s pull it together.</p>
<section id="tree-methods-which-one-when" class="level3" data-number="5.8.1">
<h3 data-number="5.8.1" class="anchored" data-anchor-id="tree-methods-which-one-when"><span class="header-section-number">5.8.1</span> Tree Methods: Which One When</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Method</th>
<th>Training</th>
<th>Interpretable</th>
<th>Tuning</th>
<th>Accuracy</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Decision Tree</td>
<td>Single tree</td>
<td>High</td>
<td>Low</td>
<td>Baseline</td>
</tr>
<tr class="even">
<td>Random Forest</td>
<td>Parallel (<span class="math inline">\(B\)</span> trees)</td>
<td>Medium</td>
<td>Low</td>
<td>Good</td>
</tr>
<tr class="odd">
<td>XGBoost</td>
<td>Sequential (<span class="math inline">\(B\)</span> trees)</td>
<td>Low</td>
<td>Higher</td>
<td>Best</td>
</tr>
</tbody>
</table>
<p><strong>Random Forest is the better default</strong>: robust, almost no tuning, OOB error for free. <strong>Move to XGBoost</strong> when you can afford to tune and need the last few points — and budget for that tuning, because an untuned XGBoost often loses to a default forest.</p>
<div class="warningbox">
<p>Neither can <strong>extrapolate</strong> beyond the training range. A tree predicts the mean of a leaf, and no leaf contains values it never saw. On a trending series, both will flatten out exactly when you need them to keep climbing.</p>
</div>
<p>Three rows.</p>
<p>Decision tree — single tree, highly interpretable, minimal tuning, baseline accuracy. Random forest — parallel, medium interpretability, low tuning, good accuracy. XGBoost — sequential, low interpretability, higher tuning, best accuracy.</p>
<p>My advice is that <strong>random forest is the better default</strong>, and I want to be clear about why, because “XGBoost is best” is what the accuracy column says.</p>
<p>A random forest is robust, needs almost no tuning, and hands you OOB error for free. It is genuinely hard to make one catastrophically wrong.</p>
<p>Move to XGBoost when you can afford to tune and you need the last few points. And budget for that tuning honestly — an untuned XGBoost frequently loses to a default random forest. The accuracy in that column is the accuracy of a <em>well-tuned</em> XGBoost, and that word is carrying weight. And the warning box applies to every row.</p>
<p>Neither can <strong>extrapolate</strong>. A tree predicts the mean of a leaf, and no leaf contains values it never saw. On a trending series, both flatten out exactly when you need them to keep climbing.</p>
<p>We put a number on that last week: CA_1 food sales grew twenty-nine percent over five years. Train on the first four, and the highest number a tree can output is a leaf mean from the older, lower range.</p>
<p>So the classical methods did not become obsolete today. If your series trends and you need to forecast beyond its historical range, an ARIMA with drift will do something a forest simply cannot.</p>
</section>
<section id="lecture-5-key-takeaways" class="level3" data-number="5.8.2">
<h3 data-number="5.8.2" class="anchored" data-anchor-id="lecture-5-key-takeaways"><span class="header-section-number">5.8.2</span> Lecture 5: Key Takeaways</h3>
<div class="keybox">
<ol type="1">
<li><p><strong>Ensembles</strong> work because independent errors cancel. Averaging many imperfect models beats any single model.</p></li>
<li><p><strong>Bagging</strong> averages <span class="math inline">\(B\)</span> trees fit to bootstrap samples; variance falls as <span class="math inline">\(B\)</span> grows but floors at <span class="math inline">\(\rho\sigma^2\)</span>. <strong>Random Forests</strong> subsample features at each split to cut <span class="math inline">\(\rho\)</span> — the key gain over plain bagging.</p></li>
<li><p><strong>OOB error</strong> is free cross-validation: each observation sits out ~37% of trees, giving an unbiased generalization estimate.</p></li>
<li><p><strong>Boosting</strong> inverts the idea — trees are built sequentially, each fitting the ensemble’s remaining errors. Bagging attacks variance; boosting attacks bias. <strong>XGBoost</strong> adds a Newton step, penalties on leaf count and weights, and column subsampling.</p></li>
<li><p>Tune by cross-validation, always with <code>TimeSeriesSplit</code> — a random split leaks the future into the past — and pair boosting with <strong>early stopping</strong>.</p></li>
</ol>
</div>
<p><em>Next: Regularization &amp; Model Selection — choosing among many predictors by shrinking coefficients rather than counting them.</em></p>
<p>Five things. <strong>One.</strong> Ensembles work because independent errors cancel. The word independent is load-bearing.</p>
<p><strong>Two.</strong> Bagging averages B trees on bootstrap samples. Variance falls as B grows but floors at rho sigma squared. Random forests subsample features at each split to cut rho — the key gain over plain bagging. <strong>Three.</strong> OOB error is free cross-validation — but it needs a large dataset, and ours is not.</p>
<p><strong>Four.</strong> Boosting inverts the idea. Trees built sequentially, each fitting what remains. Bagging attacks variance; boosting attacks bias. XGBoost adds a Newton step, explicit penalties, and column subsampling. <strong>Five.</strong> Tune by cross-validation, always with <code>TimeSeriesSplit</code>, and pair boosting with early stopping.</p>
<p>And one thing that isn’t on the slide. The jump from ARIMA to random forest on our data was large — sixteen sixty down to ten twenty. Most of that came from the feature set, not the algorithm. Remember that when you’re tempted to reach for a more complicated model instead of a better predictor.</p>
</section>
<section id="references" class="level3" data-number="5.8.3">
<h3 data-number="5.8.3" class="anchored" data-anchor-id="references"><span class="header-section-number">5.8.3</span> References</h3>
<div id="refs" role="list" style="display: none">

</div>
<p>Reading is ISLP section 8.2 — bagging, random forests, and boosting — plus the XGBoost “Introduction to Boosted Trees” tutorial, which derives the regularized objective we waved at on slide 18.</p>
<p>Next week: Regularization and Model Selection. We take the penalty idea that showed up inside XGBoost and give it a lecture of its own. See you then.</p>
</section>
</section>
<section id="timing-guide" class="level2" data-number="5.9">
<h2 data-number="5.9" class="anchored" data-anchor-id="timing-guide"><span class="header-section-number">5.9</span> Timing guide</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Segment</th>
<th>Slides</th>
<th style="text-align: right;">Target</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Opening &amp; wisdom of crowds</td>
<td>1–4</td>
<td style="text-align: right;">~4 min</td>
</tr>
<tr class="even">
<td>Bagging &amp; OOB</td>
<td>5–7</td>
<td style="text-align: right;">~6 min</td>
</tr>
<tr class="odd">
<td>Random forests</td>
<td>8–10</td>
<td style="text-align: right;">~6 min</td>
</tr>
<tr class="even">
<td>Feature importance &amp; Python</td>
<td>11–13</td>
<td style="text-align: right;">~6 min</td>
</tr>
<tr class="odd">
<td>Boosting &amp; XGBoost</td>
<td>14–20</td>
<td style="text-align: right;">~9 min</td>
</tr>
<tr class="even">
<td>Close</td>
<td>21–24</td>
<td style="text-align: right;">~4 min</td>
</tr>
</tbody>
</table>
<p>This is the longest deck in the course. If you must compress, slides 10 and 19 — the two hyperparameter tables — survive trimming best. Do <strong>not</strong> compress slides 6, 9, or 15: the variance floor, the decorrelation fix, and the bagging-versus-boosting distinction are what the whole lecture is built on.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/Lecture04_DecisionTrees.html" class="pagination-link" aria-label="Decision Trees">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Decision Trees</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/Lecture06_Regularization.html" class="pagination-link" aria-label="Regularization &amp; Model Selection">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Regularization &amp; Model Selection</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>