<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.33">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>12&nbsp; Bayesian Statistics II — Time Series – Business Forecasting</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/Lecture11_Part2_Hierarchical.html" rel="next">
<link href="../chapters/Lecture10_BayesianFoundations.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-c1b08d31956f1824f457e0b6984faaea.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/Lecture11_Part1_BayesianTS.html"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Bayesian Statistics II — Time Series</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Business Forecasting</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture01_ETS_Eval.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction, Exponential Smoothing &amp; Forecast Evaluation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture02_ARIMA_VAR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">ARIMA, VAR &amp; Multivariate Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture03_GAMs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Generalized Additive Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture04_DecisionTrees.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Decision Trees</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture05_TreeEnsembles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Tree Ensembles: Random Forests &amp; Boosted Trees</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture06_Regularization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Regularization &amp; Model Selection</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture07_NeuralNets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Introduction to Neural Networks</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture08_CNNs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">CNN Architectures</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture09_Part1_RNN_LSTM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">RNNs and LSTMs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture09_Part2_Transformers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Transformers</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture10_BayesianFoundations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Bayesian Statistics I — Foundations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture11_Part1_BayesianTS.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Bayesian Statistics II — Time Series</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture11_Part2_Hierarchical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Bayesian Statistics II — Hierarchical Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture12_BayesianRegression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Bayesian Statistics III — Bayesian Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture13_Synthesis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Synthesis — What the Semester Measured</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#lecture-outline" id="toc-lecture-outline" class="nav-link active" data-scroll-target="#lecture-outline"><span class="header-section-number">12.1</span> Lecture Outline</a></li>
  <li><a href="#why-bayesian-time-series" id="toc-why-bayesian-time-series" class="nav-link" data-scroll-target="#why-bayesian-time-series"><span class="header-section-number">12.2</span> Why Bayesian Time Series</a>
  <ul class="collapse">
  <li><a href="#what-every-model-so-far-gave-you" id="toc-what-every-model-so-far-gave-you" class="nav-link" data-scroll-target="#what-every-model-so-far-gave-you"><span class="header-section-number">12.2.1</span> What Every Model So Far Gave You</a></li>
  <li><a href="#three-things-that-become-possible" id="toc-three-things-that-become-possible" class="nav-link" data-scroll-target="#three-things-that-become-possible"><span class="header-section-number">12.2.2</span> Three Things That Become Possible</a></li>
  </ul></li>
  <li><a href="#the-structural-decomposition" id="toc-the-structural-decomposition" class="nav-link" data-scroll-target="#the-structural-decomposition"><span class="header-section-number">12.3</span> The Structural Decomposition</a>
  <ul class="collapse">
  <li><a href="#structural-time-series-one-equation" id="toc-structural-time-series-one-equation" class="nav-link" data-scroll-target="#structural-time-series-one-equation"><span class="header-section-number">12.3.1</span> Structural Time Series: One Equation</a></li>
  <li><a href="#the-level-a-random-walk-with-a-prior-on-it" id="toc-the-level-a-random-walk-with-a-prior-on-it" class="nav-link" data-scroll-target="#the-level-a-random-walk-with-a-prior-on-it"><span class="header-section-number">12.3.2</span> The Level: A Random Walk With a Prior On It</a></li>
  <li><a href="#seasonality-as-fourier-terms" id="toc-seasonality-as-fourier-terms" class="nav-link" data-scroll-target="#seasonality-as-fourier-terms"><span class="header-section-number">12.3.3</span> Seasonality as Fourier Terms</a></li>
  </ul></li>
  <li><a href="#fitting-it-in-pymc" id="toc-fitting-it-in-pymc" class="nav-link" data-scroll-target="#fitting-it-in-pymc"><span class="header-section-number">12.4</span> Fitting It in PyMC</a>
  <ul class="collapse">
  <li><a href="#the-model-in-pymc" id="toc-the-model-in-pymc" class="nav-link" data-scroll-target="#the-model-in-pymc"><span class="header-section-number">12.4.1</span> The Model in PyMC</a></li>
  <li><a href="#the-first-fit-failed-here-is-what-that-looks-like" id="toc-the-first-fit-failed-here-is-what-that-looks-like" class="nav-link" data-scroll-target="#the-first-fit-failed-here-is-what-that-looks-like"><span class="header-section-number">12.4.2</span> The First Fit Failed — Here Is What That Looks Like</a></li>
  </ul></li>
  <li><a href="#reading-the-forecast" id="toc-reading-the-forecast" class="nav-link" data-scroll-target="#reading-the-forecast"><span class="header-section-number">12.5</span> Reading the Forecast</a>
  <ul class="collapse">
  <li><a href="#does-it-work-the-point-forecast" id="toc-does-it-work-the-point-forecast" class="nav-link" data-scroll-target="#does-it-work-the-point-forecast"><span class="header-section-number">12.5.1</span> Does It Work? The Point Forecast</a></li>
  <li><a href="#the-interval-is-the-product" id="toc-the-interval-is-the-product" class="nav-link" data-scroll-target="#the-interval-is-the-product"><span class="header-section-number">12.5.2</span> The Interval Is the Product</a></li>
  </ul></li>
  <li><a href="#key-takeaways" id="toc-key-takeaways" class="nav-link" data-scroll-target="#key-takeaways"><span class="header-section-number">12.6</span> Key Takeaways</a>
  <ul class="collapse">
  <li><a href="#lecture-11-part-1-key-takeaways" id="toc-lecture-11-part-1-key-takeaways" class="nav-link" data-scroll-target="#lecture-11-part-1-key-takeaways"><span class="header-section-number">12.6.1</span> Lecture 11 Part 1: Key Takeaways</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">12.6.2</span> References</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Bayesian Statistics II — Time Series</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><em>Lecture 11, Part 1 of ECON 8310.</em></p>
<section id="lecture-outline" class="level2" data-number="12.1">
<h2 data-number="12.1" class="anchored" data-anchor-id="lecture-outline"><span class="header-section-number">12.1</span> Lecture Outline</h2>
<ol type="1">
<li>Why Bayesian Time Series</li>
<li>The Structural Decomposition</li>
<li>Fitting It in PyMC</li>
<li>Reading the Forecast</li>
<li>Key Takeaways</li>
</ol>
<p>Five parts. Why you’d do this at all, given that four percent. Then the structural decomposition — writing a series as parts you can name. Then fitting it in PyMC, where our first attempt fails. Then reading the forecast, and the two very different questions you can ask about an interval. And takeaways.</p>
</section>
<section id="why-bayesian-time-series" class="level2" data-number="12.2">
<h2 data-number="12.2" class="anchored" data-anchor-id="why-bayesian-time-series"><span class="header-section-number">12.2</span> Why Bayesian Time Series</h2>
<p>Not a more accurate forecast — a different deliverable.</p>
<section id="what-every-model-so-far-gave-you" class="level3" data-number="12.2.1">
<h3 data-number="12.2.1" class="anchored" data-anchor-id="what-every-model-so-far-gave-you"><span class="header-section-number">12.2.1</span> What Every Model So Far Gave You</h3>
<p>Ten weeks of forecasting, and almost every model returned the same object: <strong>one number per period</strong>. ETS, ARIMA, random forests, XGBoost, LSTMs — a point forecast, and at best an interval derived from asymptotic theory that nobody checked.</p>
<p>For a planner that is often not enough. <em>How much stock do I need so the chance of a stockout is under 5%?</em> is a question about a distribution, and a point forecast cannot answer it however accurate it is.</p>
<div class="keybox">
<p>A Bayesian time series model returns a <strong>full predictive distribution for every future period</strong>, plus a distribution over each component — the trend, the seasonality, and the noise, each with its own uncertainty.</p>
</div>
<p><strong>Set expectations now.</strong> This will not beat XGBoost on RMSE, and on our data it barely beats the seasonal-naive benchmark. The argument for it is what it hands you, not where it ranks — and we will hold it to that standard at the end of this lecture.</p>
<p>Take stock for a second. Ten weeks of forecasting, and almost every model has returned the same object: <strong>one number per period.</strong></p>
<p>ETS, ARIMA, random forests, XGBoost, the LSTM — a point forecast. And at best, an interval derived from asymptotic theory that, let’s be honest, nobody checked.</p>
<p>For a planner, that is often not enough. Consider the question: <em>how much stock do I need so the chance of a stockout is under five percent?</em></p>
<p>That is a question about a <strong>distribution</strong>. A point forecast cannot answer it — not because the point forecast is inaccurate, but because it isn’t the right kind of object. You can’t extract a fifth percentile from a single number.</p>
<p>A Bayesian time series model returns a full predictive distribution for every future period, plus a distribution over each <em>component</em> — the trend, the seasonality, the noise, each with its own uncertainty. And let me set expectations properly, right now.</p>
<p>This will not beat XGBoost on RMSE. On our data it barely beats seasonal naive. The argument for it is what it hands you, not where it ranks.</p>
<p>I’m saying that at the start because at the end of this lecture I’m going to hold it to exactly that standard — and it’s going to partially fail. That’s a more useful hour than one where everything works.</p>
</section>
<section id="three-things-that-become-possible" class="level3" data-number="12.2.2">
<h3 data-number="12.2.2" class="anchored" data-anchor-id="three-things-that-become-possible"><span class="header-section-number">12.2.2</span> Three Things That Become Possible</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Priors carry knowledge</strong></td>
<td>“Weekly growth is very unlikely to exceed 20%” is a sentence you can put in the model, rather than hoping the data implies it.</td>
</tr>
<tr class="even">
<td><strong>Components get error bars</strong></td>
<td>Not just a forecast, but “how confident am I that there is a trend at all?” — separately from the seasonality.</td>
</tr>
<tr class="odd">
<td><strong>Uncertainty compounds honestly</strong></td>
<td>Forecast 52 weeks out and the interval widens as it should, because the model propagates uncertainty forward instead of assuming it away.</td>
</tr>
</tbody>
</table>
<p>That third row is the one people underestimate. A prediction interval from ARIMA widens too, but according to a formula derived under assumptions you did not check. Here the widening is a consequence of the model you actually wrote down.</p>
<p><strong>And the price:</strong> it is slower, it needs priors you have to defend, and — as we will see — it can fail silently in ways a least-squares fit cannot.</p>
<p>Three capabilities you didn’t have before.</p>
<p><strong>Priors carry knowledge.</strong> “Weekly growth is very unlikely to exceed twenty percent” is a sentence you can put <em>into the model</em>, rather than hoping the data implies it. When you have short history, that’s the difference between a usable forecast and a wild one.</p>
<p><strong>Components get error bars.</strong> Not just a forecast, but “how confident am I that there’s a trend at all?” — separately from the seasonality. You can decompose your uncertainty, not just your signal.</p>
<p><strong>Uncertainty compounds honestly.</strong> Forecast fifty-two weeks out and the interval widens, because the model propagates uncertainty forward rather than assuming it away. That third row is the one people underestimate, so let me sharpen it.</p>
<p>An ARIMA prediction interval widens too. But it widens according to a <strong>formula</strong>, derived under assumptions about the error process that you did not check and probably could not check.</p>
<p>Here, the widening is a <em>consequence of the model you wrote down</em>. If you said the level follows a random walk, then fifty-two steps of random walk uncertainty is what you get. You can trace the interval back to a modeling choice and argue about that choice.</p>
<p>That traceability is worth more than it sounds. When a planner tells you the interval is too wide to use — which is exactly what will happen at the end of this lecture — you can point at the specific assumption producing it and propose changing <em>that</em>, rather than shrugging at a formula. An ARIMA interval you can only accept or reject. This one you can negotiate with.</p>
<p>And the price is real: it’s slower, it needs priors you must defend, and — as we’ll see in twenty minutes — it can fail silently in ways a least-squares fit simply cannot.</p>
</section>
</section>
<section id="the-structural-decomposition" class="level2" data-number="12.3">
<h2 data-number="12.3" class="anchored" data-anchor-id="the-structural-decomposition"><span class="header-section-number">12.3</span> The Structural Decomposition</h2>
<p>Write the series as a sum of parts you can name, and put a prior on each.</p>
<section id="structural-time-series-one-equation" class="level3" data-number="12.3.1">
<h3 data-number="12.3.1" class="anchored" data-anchor-id="structural-time-series-one-equation"><span class="header-section-number">12.3.1</span> Structural Time Series: One Equation</h3>
<p>The whole idea is additive, and you have seen the shape before — it is the GAM decomposition from Lecture 3, with priors attached.</p>
<p><span class="math display">\[y_t \;=\; \underbrace{\mu_t}_{\text{level}} \;+\; \underbrace{s_t}_{\text{seasonality}} \;+\; \underbrace{\varepsilon_t}_{\text{noise}}, \qquad \varepsilon_t \sim \mathcal{N}(0, \sigma^2)\]</span></p>
<p><strong>Each piece is a thing a business person can name</strong>, and each gets its own posterior. “Demand is growing” is a statement about <span class="math inline">\(\mu_t\)</span>; “December is our peak” is a statement about <span class="math inline">\(s_t\)</span>; “how noisy is this store?” is <span class="math inline">\(\sigma\)</span>.</p>
<div class="keybox">
<p>This is why the approach is called <em>structural</em>. You are not fitting a black box to a curve — you are stating what you believe the series is made of, and asking the data how much of each part there is.</p>
</div>
<p>Compare ARIMA, where trend and seasonality are handled by differencing and the parameters are correlations rather than quantities anyone can interpret.</p>
<p>The whole idea is additive, and you have seen this shape before. y-t equals mu-t, the level, plus s-t, the seasonality, plus epsilon-t, the noise.</p>
<p>That is the GAM decomposition from Lecture 3, with priors attached. Same additive structure, same named components — now each one is a random variable with a distribution.</p>
<p>And here’s why that matters practically. <strong>Each piece is a thing a business person can name</strong>, and each gets its own posterior.</p>
<p>“Demand is growing” is a statement about mu-t. “December is our peak” is a statement about s-t. “How noisy is this store?” is sigma. Those are three separate questions, and the model answers them separately, with uncertainty on each.</p>
<p>That’s why the approach is called <strong>structural</strong>. You are not fitting a flexible curve to data and hoping. You are stating what you believe the series is <em>made of</em>, and asking the data how much of each part there is.</p>
<p>Contrast ARIMA, which we spent Lecture 2 on. There, trend and seasonality are handled by <em>differencing</em> — you remove them rather than model them — and the parameters that come out are autocorrelation coefficients. Nobody has ever walked into a planning meeting and explained the business implications of an MA(2) coefficient. Here, every parameter is a quantity somebody outside the room can interpret. There’s a real trade being made, though, and I don’t want to sell only one side.</p>
<p>ARIMA’s differencing is <em>automatic</em>. You don’t have to know whether the trend is linear or wandering or damped — you difference, and the trend is gone, whatever shape it had.</p>
<p>Structural modeling makes you <strong>commit</strong>. You have to say what kind of level you believe in before you fit. Commit correctly and you get interpretable components and honest uncertainty. Commit wrongly and you have baked a false assumption into the model, and the posterior will look perfectly confident about it.</p>
<p>That’s the same bargain as the DAG in Lecture 12: stating your assumptions gets you more, and makes you responsible for them.</p>
</section>
<section id="the-level-a-random-walk-with-a-prior-on-it" class="level3" data-number="12.3.2">
<h3 data-number="12.3.2" class="anchored" data-anchor-id="the-level-a-random-walk-with-a-prior-on-it"><span class="header-section-number">12.3.2</span> The Level: A Random Walk With a Prior On It</h3>
<p>The simplest useful trend is a <strong>local level</strong> — the series has a level, and the level itself drifts:</p>
<p><span class="math display">\[\mu_t = \mu_{t-1} + \eta_t, \qquad \eta_t \sim \mathcal{N}(0, \sigma_{\text{level}}^2)\]</span></p>
<p>Read it as a sentence: this week’s level is last week’s level, plus a shock. And <span class="math inline">\(\sigma_{\text{level}}\)</span> — which you put a prior on — controls <strong>how fast the level is allowed to move</strong>.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<tbody>
<tr class="odd">
<td>Small <span class="math inline">\(\sigma_{\text{level}}\)</span></td>
<td>A nearly constant level. Rigid, but stable far into the future.</td>
</tr>
<tr class="even">
<td>Large <span class="math inline">\(\sigma_{\text{level}}\)</span></td>
<td>A level that chases recent data. Fits well, and forecasts wander.</td>
</tr>
</tbody>
</table>
<p><strong>That is a familiar trade in new clothing</strong> — it is the smoothing parameter from Lecture 1’s exponential smoothing, and the penalty strength from Lecture 6, now expressed as a prior you can argue about.</p>
<p>The simplest useful trend is a <strong>local level</strong>: the series has a level, and the level itself drifts over time.</p>
<p>mu-t equals mu-t-minus-one plus a shock. Read as a sentence: <strong>this week’s level is last week’s level, plus a random disturbance.</strong></p>
<p>And that disturbance has a standard deviation, sigma-level, which you put a prior on. That single parameter controls <strong>how fast the level is allowed to move</strong>. Small sigma-level: a nearly constant level. Rigid, but stable far into the future.</p>
<p>Large sigma-level: a level that chases recent data. Fits the training period beautifully, and the forecasts wander off. And that is a familiar trade in new clothing.</p>
<p>It is the smoothing parameter from Lecture 1’s exponential smoothing — alpha, deciding how fast to forget. It is the penalty strength from Lecture 6. Now it’s expressed as a <strong>prior you can argue about</strong>, and — importantly — the data gets a say in it too, because sigma-level is estimated, not fixed. That’s the sixth appearance of this idea coming into view. We’ll name it properly next week.</p>
</section>
<section id="seasonality-as-fourier-terms" class="level3" data-number="12.3.3">
<h3 data-number="12.3.3" class="anchored" data-anchor-id="seasonality-as-fourier-terms"><span class="header-section-number">12.3.3</span> Seasonality as Fourier Terms</h3>
<p>Fifty-two weekly seasonal parameters would be a lot to estimate. Instead, build seasonality out of a few smooth waves:</p>
<p><span class="math display">\[s_t = \sum_{k=1}^{K}\left[a_k \sin\!\left(\tfrac{2\pi k t}{P}\right) + b_k \cos\!\left(\tfrac{2\pi k t}{P}\right)\right]\]</span></p>
<p><span class="math inline">\(P\)</span> is the period — for our weekly data, <span class="math inline">\(P = 52\)</span>. <span class="math inline">\(K\)</span> is how many waves you allow: <span class="math inline">\(K=1\)</span> is a single smooth annual cycle, larger <span class="math inline">\(K\)</span> lets the shape get more detailed. Each <span class="math inline">\(a_k, b_k\)</span> is just a coefficient with a Normal prior.</p>
<div class="keybox">
<p><strong>You have met this exact device twice.</strong> It is how Prophet encodes seasonality in Lecture 3, and it is the Fourier feature block we engineered by hand for Homework 4. The difference now is that <span class="math inline">\(a_k\)</span> and <span class="math inline">\(b_k\)</span> come back as <em>distributions</em>.</p>
</div>
<p><span class="math inline">\(K\)</span> trades flexibility against overfitting, exactly like spline knots. We use <span class="math inline">\(K = 3\)</span> — six coefficients standing in for fifty-two.</p>
<p>Now seasonality. Our data is weekly with an annual cycle, so a naive approach would estimate fifty-two separate seasonal parameters. That’s a lot to estimate, and most of it would be noise. Instead, build the seasonal shape out of a few smooth waves.</p>
<p>s-t is a sum over k of sine and cosine terms at increasing frequencies. P is the period — fifty-two for us. K is how many waves you allow. K equals one is a single smooth annual cycle; larger K lets the shape get more detailed, with sharper peaks. And each a-k and b-k is just a coefficient with a Normal prior. Nothing exotic. You have met this exact construction <strong>twice already</strong>.</p>
<p>It is how Prophet encodes seasonality, in Lecture 3. And it is the Fourier feature block you engineered by hand for Homework 4 — those <code>sin_1</code>, <code>cos_1</code>, <code>sin_2</code> columns.</p>
<p>Same device, third appearance. The difference now is that a-k and b-k come back as <strong>distributions</strong>, so you can ask how confident you are that the seasonal peak is where you think it is.</p>
<p>K trades flexibility against overfitting, exactly like spline knots in Lecture 3. We use K equals three — six coefficients standing in for fifty-two parameters.</p>
<p>Notice what that construction <em>assumes</em>, because it’s an assumption and not a free lunch: it assumes the seasonal shape is <strong>smooth</strong>.</p>
<p>Three sine-cosine pairs can describe a broad annual hump with a couple of gentle bumps. What they cannot describe is a single enormous one-week spike — Black Friday, say — sitting on an otherwise flat year. Fourier terms will smear that spike across neighboring weeks, because smooth curves are all they can make.</p>
<p>If your business has sharp calendar events, the honest answer is to model them as <strong>separate indicator variables</strong> rather than raising K until the waves can approximate a spike. That’s what Prophet does with its holiday regressors, and it’s what you did by hand with the SNAP and event flags in Homework 2.</p>
</section>
</section>
<section id="fitting-it-in-pymc" class="level2" data-number="12.4">
<h2 data-number="12.4" class="anchored" data-anchor-id="fitting-it-in-pymc"><span class="header-section-number">12.4</span> Fitting It in PyMC</h2>
<p>The model in code, and the check you run before believing any of it.</p>
<section id="the-model-in-pymc" class="level3" data-number="12.4.1">
<h3 data-number="12.4.1" class="anchored" data-anchor-id="the-model-in-pymc"><span class="header-section-number">12.4.1</span> The Model in PyMC</h3>
<div class="examplebox">
<div class="examplebox-title">
<p>Local level <span class="math inline">\(+\)</span> Fourier seasonality</p>
</div>
<div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> pm.Model() <span class="im">as</span> model:</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>    sigma_level <span class="op">=</span> pm.Exponential(<span class="st">"sigma_level"</span>, <span class="fl">10.0</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    z           <span class="op">=</span> pm.Normal(<span class="st">"z"</span>, <span class="dv">0</span>, <span class="dv">1</span>, shape<span class="op">=</span>n)     <span class="co"># non-centered</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    level <span class="op">=</span> pm.Deterministic(<span class="st">"level"</span>, pm.math.cumsum(z <span class="op">*</span> sigma_level))</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    beta  <span class="op">=</span> pm.Normal(<span class="st">"beta"</span>, <span class="dv">0</span>, <span class="fl">0.5</span>, shape<span class="op">=</span><span class="dv">2</span><span class="op">*</span>K)    <span class="co"># Fourier</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    sigma <span class="op">=</span> pm.Exponential(<span class="st">"sigma"</span>, <span class="fl">1.0</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    pm.Normal(<span class="st">"obs"</span>, mu<span class="op">=</span>level <span class="op">+</span> pm.math.dot(X, beta),</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>              sigma<span class="op">=</span>sigma, observed<span class="op">=</span>y_scaled)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    idata <span class="op">=</span> pm.sample(<span class="dv">1500</span>, tune<span class="op">=</span><span class="dv">2000</span>, chains<span class="op">=</span><span class="dv">4</span>, target_accept<span class="op">=</span><span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Line for line this is the equations above — <code>cumsum</code> of scaled Normal draws <em>is</em> a random walk. <strong>Standardize <span class="math inline">\(y\)</span> first</strong>: these priors assume unit scale, and on raw units of 20,000 they would be absurdly tight.</p>
<p>Here is everything from the last three slides, in about eight lines.</p>
<p><code>sigma_level</code> with an Exponential prior — it must be positive, so Exponential, not Normal. Then <code>z</code>, a vector of standard Normals. Then the level is the <strong>cumulative sum</strong> of z times sigma_level.</p>
<p>Stop on that line for a second, because it’s the clever bit: <code>cumsum</code> of scaled Normal draws <strong>is</strong> a random walk. That’s the definition. Each step adds a scaled Normal shock to the running total.</p>
<p>Then <code>beta</code>, the Fourier coefficients. Then sigma, the observation noise. Then the likelihood: the observed data is Normal around level plus the Fourier terms. One thing you must do, and it’s bolded for a reason. <strong>Standardize y first.</strong></p>
<p>These priors assume the data is on roughly unit scale. Our weekly units are in the tens of thousands. An Exponential prior with rate ten on <code>sigma_level</code> is a sensible prior for a standardized series and an absurdly tight one for raw units of twenty thousand — you’d be telling the model the level essentially cannot move.</p>
<p>Standardize, fit, then transform the forecasts back. Getting this wrong produces a model that fits terribly for reasons that look mysterious.</p>
<p>This is the same lesson as Lecture 6’s warning about standardizing before Ridge, and it will come back one more time in Lecture 12 with the opposite sign — where standardizing a variable you then <em>interpret</em> silently destroys the interpretation.</p>
<p>So the rule isn’t “always standardize” or “never.” It’s: <strong>know what scale each variable is on, and know what your priors assume about that scale.</strong> A prior is a statement about magnitudes. If you don’t know the magnitudes, you don’t know what you’ve assumed.</p>
</section>
<section id="the-first-fit-failed-here-is-what-that-looks-like" class="level3" data-number="12.4.2">
<h3 data-number="12.4.2" class="anchored" data-anchor-id="the-first-fit-failed-here-is-what-that-looks-like"><span class="header-section-number">12.4.2</span> The First Fit Failed — Here Is What That Looks Like</h3>
<p>Written the obvious way, with <code>pm.GaussianRandomWalk</code>, this model samples badly — even at <code>target_accept=0.95</code>. Lecture 10’s checks caught it:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">First attempt</th>
<th style="text-align: right;">After the fix</th>
<th>Want</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\hat{R}\)</span></td>
<td style="text-align: right;">1.022</td>
<td style="text-align: right;"><strong>1.002</strong></td>
<td><span class="math inline">\(&lt; 1.01\)</span></td>
</tr>
<tr class="even">
<td>ESS (bulk)</td>
<td style="text-align: right;">252</td>
<td style="text-align: right;"><strong>2,376</strong></td>
<td><span class="math inline">\(&gt; 400\)</span></td>
</tr>
<tr class="odd">
<td>Divergences</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td><span class="math inline">\(0\)</span></td>
</tr>
</tbody>
</table>
<p>Nothing crashed. The model returned a forecast, and the forecast looked reasonable. Only the diagnostics said the chains had not agreed with each other.</p>
<div class="warningbox">
<p><strong>The fix was reparameterization, not more samples.</strong> Writing the walk as <code>cumsum(z * sigma)</code> with <span class="math inline">\(z \sim \mathcal{N}(0,1)\)</span> — the <em>non-centered</em> form — gives the sampler a geometry it can navigate. BMCP §4.6.1 covers exactly this, and you will meet it again next week.</p>
</div>
<p>Now something worth your attention.</p>
<p>The obvious way to write this model uses <code>pm.GaussianRandomWalk</code>, which is exactly what it sounds like and exactly what the equation says. We wrote it that way first. And it sampled <strong>badly</strong> — even with <code>target_accept</code> raised to point-nine-five.</p>
<p>R-hat: one-point-oh-two-two, against a threshold of one-point-oh-one. Failed. ESS: two hundred fifty-two, against four hundred. Failed. Divergences: zero — that one passed. After the fix: R-hat one-point-oh-oh-two, ESS two thousand six hundred seventeen. Here is what I want you to take from this.</p>
<p><strong>Nothing crashed.</strong> The model returned a forecast. The forecast, plotted, looked entirely reasonable — a sensible level, a sensible seasonal shape, plausible intervals. If we had not run the diagnostics, we would have shipped it and never known.</p>
<p>The only thing that told us was R-hat saying the four chains had not agreed with each other.</p>
<p>That is precisely why Lecture 10 made those three numbers non-negotiable. This is the failure mode they exist for. And the fix is worth understanding, because you’ll meet it again next week.</p>
<p>The fix was <strong>reparameterization</strong>, not more samples. Not a longer run, not a smaller step size — a different way of writing the <em>same model</em>.</p>
<p>Writing the walk as <code>cumsum(z * sigma)</code>, with z a standard Normal, is called the <strong>non-centered</strong> form. It gives the sampler a geometry it can actually navigate. Identical model, identical posterior in principle, completely different sampling behavior.</p>
<p>BMCP section four-point-six-point-one covers exactly this, and next week we’ll see the same fix applied to a hierarchy — where it will matter even more.</p>
</section>
</section>
<section id="reading-the-forecast" class="level2" data-number="12.5">
<h2 data-number="12.5" class="anchored" data-anchor-id="reading-the-forecast"><span class="header-section-number">12.5</span> Reading the Forecast</h2>
<p>The point estimate, the interval, and whether either is any use.</p>
<section id="does-it-work-the-point-forecast" class="level3" data-number="12.5.1">
<h3 data-number="12.5.1" class="anchored" data-anchor-id="does-it-work-the-point-forecast"><span class="header-section-number">12.5.1</span> Does It Work? The Point Forecast</h3>
<p>CA_1 FOODS, 52 weeks held out, forecast from the fitted model.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Model</th>
<th style="text-align: right;">Test RMSE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Bayesian structural TS</td>
<td style="text-align: right;"><strong>1,589</strong></td>
</tr>
<tr class="even">
<td>Seasonal naive (same week last year)</td>
<td style="text-align: right;">1,660</td>
</tr>
</tbody>
</table>
<p><strong>It beats the benchmark by about 4%.</strong> That is a real improvement and a small one, and after nine weeks of this course you should be suspicious of anyone who reports it as a triumph.</p>
<p>It is also worth remembering what this model was given: the series and a calendar. No lag features, no price, no SNAP flags, no store identity. The XGBoost model in Homework 4 had 46 engineered predictors and thirty series to learn from.</p>
<p><strong>So the point forecast is not the reason to do this.</strong> The next slide is.</p>
<p>CA_1 FOODS, fifty-two weeks held out.</p>
<p>Bayesian structural model: RMSE one thousand five hundred eighty-seven. Seasonal naive — same week last year, one line of code: one thousand six hundred sixty. So we beat the benchmark by about <strong>four percent</strong>.</p>
<p>That is a real improvement and a small one. And I’ll repeat what I said at the start: after ten weeks of this course, you should be suspicious of anyone who reports four percent as a triumph. But let me also be fair to the model, because the comparison isn’t like-for-like.</p>
<p>Look at what this model was <em>given</em>: the series, and a calendar. That’s it. No lag features. No price. No SNAP flags. No store identity. No cross-series information.</p>
<p>The XGBoost model in Homework 4 had forty-six engineered predictors and thirty series to learn from, and beat naive by a much wider margin. It also had a great deal more information.</p>
<p>And there’s nothing stopping you from combining them, which is what a serious production system usually does. Add price and promotion regressors to this structural model and the level has less work to do, so it drifts less, so the interval narrows. You keep the predictive distribution and you buy back some accuracy.</p>
<p>We’re not doing that today because I want the mechanism visible rather than buried under covariates. But it is the obvious next step, and it’s a very reasonable direction for a final project.</p>
<p>So: the point forecast is not the reason to do this. Which brings us to the slide that is.</p>
</section>
<section id="the-interval-is-the-product" class="level3" data-number="12.5.2">
<h3 data-number="12.5.2" class="anchored" data-anchor-id="the-interval-is-the-product"><span class="header-section-number">12.5.2</span> The Interval Is the Product</h3>
<p>Every forecast comes with a 94% predictive interval. Two questions about it, and they are different questions.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Measured</th>
<th>Reading</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Calibrated?</strong></td>
<td>100% of weeks fell inside</td>
<td>Not overconfident — but it should be about 94%, so it is conservative</td>
</tr>
<tr class="even">
<td><strong>Useful?</strong></td>
<td>Width <span class="math inline">\(\approx\)</span> 11,700 units, on a mean of 19,700</td>
<td>About $$30%. Honest, and too wide to order against</td>
</tr>
</tbody>
</table>
<p><strong>Passing the first does not excuse failing the second.</strong> A model saying “somewhere between 14,000 and 26,000” is telling the truth and helping nobody. The cause is structural — a level free to walk for 52 steps drifts, and the model says so. The fix is a model with a stronger opinion: a damped level, or covariates that pin it down.</p>
<p><strong>But notice what just happened.</strong> We could <em>ask</em> whether the uncertainty was honest. For every point-forecast model in this course, that question had no answer.</p>
<p>Every forecast comes with a ninety-four percent predictive interval. And there are <strong>two</strong> questions you can ask about it, which are different questions, and this is the heart of the lecture.</p>
<p><strong>Is it calibrated?</strong> Measured: one hundred percent of held-out weeks fell inside the interval. Reading: not overconfident. Though it should be about ninety-four percent, so it’s actually <em>conservative</em> — a bit too wide.</p>
<p><strong>Is it useful?</strong> Measured: the width is roughly eleven thousand seven hundred units, on a mean of nineteen thousand seven hundred. That’s about <strong>plus or minus thirty percent</strong>. Honest, and far too wide to order against. <strong>Passing the first does not excuse failing the second.</strong></p>
<p>A model that says “demand next week will be somewhere between fourteen thousand and twenty-six thousand” is telling you the truth and helping nobody. You cannot write a purchase order against that.</p>
<p>And the cause is structural, not a bug. A level that is free to random-walk for fifty-two steps <em>drifts</em>, and the accumulated uncertainty is genuinely that large. The model is correctly reporting the consequence of what we told it to believe.</p>
<p>So the fix is a model with a <strong>stronger opinion</strong>: a damped level that reverts rather than wandering, or covariates that pin it down — price, promotions, the things we withheld. But notice what just happened, because this is the argument for the entire lecture.</p>
<p><strong>We could ask whether the uncertainty was honest.</strong> We computed coverage against held-out data, and got an answer.</p>
<p>For every point-forecast model in this course — every single one, from ETS through the Transformer — that question had <strong>no answer at all</strong>. There was nothing to check. You got a number, and the number was right or wrong, and that was the end of the conversation.</p>
<p>A calibrated-but-too-wide interval is a worse forecast and a better <em>deliverable</em>, because it tells you something true about how much you actually know. That is worth paying four percent for.</p>
</section>
</section>
<section id="key-takeaways" class="level2" data-number="12.6">
<h2 data-number="12.6" class="anchored" data-anchor-id="key-takeaways"><span class="header-section-number">12.6</span> Key Takeaways</h2>
<p>What structural models are for.</p>
<section id="lecture-11-part-1-key-takeaways" class="level3" data-number="12.6.1">
<h3 data-number="12.6.1" class="anchored" data-anchor-id="lecture-11-part-1-key-takeaways"><span class="header-section-number">12.6.1</span> Lecture 11 Part 1: Key Takeaways</h3>
<div class="keybox">
<ol type="1">
<li><p>A <strong>structural</strong> model writes the series as named parts — level, seasonality, noise — and gives each one a prior and a posterior.</p></li>
<li><p>The <strong>local level</strong> is a random walk whose step size <span class="math inline">\(\sigma_{\text{level}}\)</span> you put a prior on. Small means rigid, large means it chases the data — the same trade as a smoothing parameter or a penalty.</p></li>
<li><p><strong>Fourier terms</strong> encode seasonality in a few coefficients instead of 52. Same device as Prophet in Lecture 3 and the features you built in Homework 4.</p></li>
<li><p><strong>Check the sampler before the forecast.</strong> Our first fit had <span class="math inline">\(\hat{R}\)</span> = 1.02 and ESS = 252 while returning a plausible-looking answer. Reparameterizing fixed it.</p></li>
<li><p>The point forecast beat seasonal naive by <strong>4%</strong>. That is not the argument.</p></li>
<li><p>The interval was <strong>calibrated but too wide to act on</strong> — and being able to establish that is the actual product.</p></li>
</ol>
</div>
<p><span class="neutral">Next: hierarchical models — what to do when you have thirty series and some of them barely have data.</span></p>
<p>One. A structural model writes the series as named parts — level, seasonality, noise — and gives each one a prior and a posterior.</p>
<p>Two. The local level is a random walk whose step size you put a prior on. Small means rigid, large means it chases the data. Same trade as a smoothing parameter or a penalty.</p>
<p>Three. Fourier terms encode seasonality in a few coefficients instead of fifty-two. Same device as Prophet in Lecture 3 and the features you built in Homework 4 — third appearance.</p>
<p>Four. <strong>Check the sampler before the forecast.</strong> Our first fit had R-hat one-point-oh-two and ESS two fifty-two, while returning a perfectly plausible-looking answer. Reparameterizing fixed it. Five. The point forecast beat seasonal naive by four percent. That is not the argument.</p>
<p>And six. The interval was <strong>calibrated but too wide to act on</strong> — and being able to <em>establish</em> that is the actual product.</p>
<p>Next time: hierarchical models. What to do when you have thirty series and some of them barely have any data — and a question you have to answer <em>before</em> you fit anything.</p>
</section>
<section id="references" class="level3" data-number="12.6.2">
<h3 data-number="12.6.2" class="anchored" data-anchor-id="references"><span class="header-section-number">12.6.2</span> References</h3>
<div id="refs" role="list" style="display: none">

</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/Lecture10_BayesianFoundations.html" class="pagination-link" aria-label="Bayesian Statistics I --- Foundations">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Bayesian Statistics I — Foundations</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/Lecture11_Part2_Hierarchical.html" class="pagination-link" aria-label="Bayesian Statistics II --- Hierarchical Models">
        <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Bayesian Statistics II — Hierarchical Models</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>