<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.33">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Department of Economics">

<title>Hierarchical Models and Partial Pooling</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="Lecture11_Part2_Hierarchical_files/libs/clipboard/clipboard.min.js"></script>
<script src="Lecture11_Part2_Hierarchical_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Lecture11_Part2_Hierarchical_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Lecture11_Part2_Hierarchical_files/libs/quarto-html/popper.min.js"></script>
<script src="Lecture11_Part2_Hierarchical_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Lecture11_Part2_Hierarchical_files/libs/quarto-html/anchor.min.js"></script>
<link href="Lecture11_Part2_Hierarchical_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Lecture11_Part2_Hierarchical_files/libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Lecture11_Part2_Hierarchical_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Lecture11_Part2_Hierarchical_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Lecture11_Part2_Hierarchical_files/libs/bootstrap/bootstrap-81267100e462c21b3d6c0d5bf76a3417.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="Lecture11_Part2_Hierarchical.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Hierarchical Models and Partial Pooling</h1>
<p class="subtitle lead">ECON 8310: Business Forecasting — Lecture 11, Part 2</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Department of Economics </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Nebraska at Omaha
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  


</header>


<section id="lecture-outline" class="level2">
<h2 class="anchored" data-anchor-id="lecture-outline">Lecture Outline</h2>
<ol type="1">
<li>Which Series May Be Pooled</li>
<li>Partial Pooling</li>
<li>Fitting It, and the Trap</li>
<li>Reading the Result</li>
<li>Key Takeaways</li>
</ol>
</section>
<section id="which-series-may-be-pooled" class="level1">
<h1>Which Series May Be Pooled</h1>
<p>Before you pool anything, ask what the groups have in common.</p>
<hr>
<section id="the-question" class="level2">
<h2 class="anchored" data-anchor-id="the-question">The Question</h2>
<p>A concrete one, and you have met it before. <strong>Does demand rise in weeks when SNAP benefits are disbursed, and by how much — store by store?</strong> Homework 3’s memo had you stock up for SNAP weeks store by store, which assumed those differences are real. Today we check.</p>
<p><strong>But one question comes before the model.</strong> SNAP is a <em>food</em> assistance programme. Measure the raw SNAP-week effect on log units in all thirty series, grouped by category:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Category</th>
<th style="text-align: right;">Mean effect</th>
<th style="text-align: right;">Spread across stores</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>FOODS</strong> (10 series)</td>
<td style="text-align: right;"><span class="math inline">\(+0.089\)</span></td>
<td style="text-align: right;">0.058</td>
</tr>
<tr class="even">
<td>HOBBIES (10 series)</td>
<td style="text-align: right;"><span class="math inline">\(+0.006\)</span></td>
<td style="text-align: right;">0.010</td>
</tr>
<tr class="odd">
<td>HOUSEHOLD (10 series)</td>
<td style="text-align: right;"><span class="math inline">\(+0.011\)</span></td>
<td style="text-align: right;">0.014</td>
</tr>
</tbody>
</table>
<p><strong>These are not thirty versions of the same thing.</strong> FOODS responds; the other two barely move. Pooling all thirty would tell the model they are interchangeable.</p>
<hr>
</section>
<section id="exchangeability-the-assumption-under-every-hierarchy" class="level2">
<h2 class="anchored" data-anchor-id="exchangeability-the-assumption-under-every-hierarchy">Exchangeability: the Assumption Under Every Hierarchy</h2>
<p>Partial pooling rests on one assumption, worth naming before we use it.</p>
<div class="definitionbox">
<div class="definitionbox-title">
<p>Exchangeable</p>
</div>
<p>Groups are <strong>exchangeable</strong> when, before seeing the data, you have no reason to expect one to differ from another in a particular direction. Swapping their labels would not change what you believe.</p>
</div>
<p>The ten FOODS series qualify: same category, different stores, and you could not say in advance which store’s SNAP effect should be largest. FOODS against HOBBIES does <strong>not</strong> — you know before looking that a food-assistance programme moves food.</p>
<p><strong>The setup for today.</strong> We work with the <strong>ten FOODS series</strong>, and deliberately thin <strong>five</strong> of them down to <strong>8 weeks</strong>. Five series are data-rich, five are data-poor. That imbalance is the whole point.</p>
<p><span class="neutral smaller">The lab pools all thirty anyway, and measures what it costs.</span></p>
<hr>
</section>
<section id="complete-pooling-and-no-pooling" class="level2">
<h2 class="anchored" data-anchor-id="complete-pooling-and-no-pooling">Complete Pooling and No Pooling</h2>
<p>Within that exchangeable set there are two obvious approaches, and each fails in a different direction.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>What it does</th>
<th>How it fails</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Complete pooling</strong></td>
<td>One SNAP effect for all ten series. <code>b = pm.Normal("b", 0, 1)</code></td>
<td>Denies that stores differ at all. A genuinely different store is averaged away.</td>
</tr>
<tr class="even">
<td><strong>No pooling</strong></td>
<td>A separate effect per series, estimated independently. <code>shape=10</code></td>
<td>A series with 8 weeks gets an estimate built from 8 weeks. Mostly noise, reported as a finding.</td>
</tr>
</tbody>
</table>
<p><strong>You have used both already without naming them.</strong> Homework 3’s random forest pooled all thirty series into one model with store dummies — close to complete pooling. Homework 1 fitted ARIMA to one series at a time — no pooling. The choice has always been made by convenience; partial pooling makes it a modelling decision and lets the data settle it.</p>
</section>
</section>
<section id="partial-pooling" class="level1">
<h1>Partial Pooling</h1>
<p>Let each series have its own effect — drawn from a shared distribution the data also estimates.</p>
<hr>
<section id="the-hierarchy-is-one-extra-line" class="level2">
<h2 class="anchored" data-anchor-id="the-hierarchy-is-one-extra-line">The Hierarchy Is One Extra Line</h2>
<p>Give each series its own effect <span class="math inline">\(b_j\)</span>, but say where those effects come from:</p>
<p><span class="math display">\[b_j \sim \mathcal{N}(\mu_b,\ \sigma_b), \qquad j = 1, \ldots, 10\]</span></p>
<p><span class="math inline">\(\mu_b\)</span> is the typical SNAP effect across FOODS, and <span class="math inline">\(\sigma_b\)</span> is <strong>how much stores genuinely differ</strong>. Crucially, both are estimated from the data rather than assumed.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\sigma_b \rightarrow 0\)</span></td>
<td>The model concludes stores do not differ, and reproduces complete pooling.</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\sigma_b\)</span> large</td>
<td>The model concludes they differ a lot, and approaches no pooling.</td>
</tr>
<tr class="odd">
<td>In between</td>
<td>Each <span class="math inline">\(b_j\)</span> is pulled toward <span class="math inline">\(\mu_b\)</span> — <em>how far</em> depending on how much data that series has.</td>
</tr>
</tbody>
</table>
<p><strong>That last row is the whole idea.</strong> A series with 277 weeks barely moves; one with 8 weeks moves a long way. Nobody chose those weights — they fall out of the model.</p>
<hr>
</section>
<section id="why-this-is-the-right-answer-not-a-compromise" class="level2">
<h2 class="anchored" data-anchor-id="why-this-is-the-right-answer-not-a-compromise">Why This Is the Right Answer, Not a Compromise</h2>
<p>Partial pooling sounds like splitting the difference between two bad options. It is better than that, and the reason is worth stating.</p>
<p>When a series has 8 observations, its unpooled estimate is mostly sampling noise. The hierarchy’s pull toward <span class="math inline">\(\mu_b\)</span> is not a fudge — it is the correct response to a noisy measurement. You already believe this in another form: it is why you would not conclude a coin is biased after three flips.</p>
<div class="keybox">
<p><strong>This is regularization again, for the sixth time.</strong> A hierarchical prior shrinks per-group estimates toward a common value exactly as Ridge shrinks coefficients toward zero — and here the shrinkage strength <span class="math inline">\(\sigma_b\)</span> is <em>estimated</em> rather than tuned by cross-validation.</p>
</div>
<p><span class="neutral smaller">GAM smoothing penalty (L3) <span class="math inline">\(\rightarrow\)</span> tree pruning (L4) <span class="math inline">\(\rightarrow\)</span> <code>reg_lambda</code> (L5) <span class="math inline">\(\rightarrow\)</span> Ridge and LASSO (L6) <span class="math inline">\(\rightarrow\)</span> weight decay (L7) <span class="math inline">\(\rightarrow\)</span> hierarchical priors (today).</span></p>
</section>
</section>
<section id="fitting-it-and-the-trap" class="level1">
<h1>Fitting It, and the Trap</h1>
<p>The obvious code does not work, and the reason is geometry rather than statistics.</p>
<hr>
<section id="the-model-in-pymc" class="level2">
<h2 class="anchored" data-anchor-id="the-model-in-pymc">The Model in PyMC</h2>
<div class="examplebox">
<div class="examplebox-title">
<p>Non-centred hierarchical model</p>
</div>
<div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> pm.Model() <span class="im">as</span> model:</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>    mu_b <span class="op">=</span> pm.Normal(<span class="st">"mu_b"</span>, <span class="dv">0</span>, <span class="fl">0.5</span>)        <span class="co"># typical SNAP effect</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    sd_b <span class="op">=</span> pm.HalfNormal(<span class="st">"sd_b"</span>, <span class="fl">0.25</span>)      <span class="co"># how much stores differ</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    z    <span class="op">=</span> pm.Normal(<span class="st">"z"</span>, <span class="dv">0</span>, <span class="dv">1</span>, shape<span class="op">=</span>J)    <span class="co"># non-centred</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    b    <span class="op">=</span> pm.Deterministic(<span class="st">"b"</span>, mu_b <span class="op">+</span> z <span class="op">*</span> sd_b)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    a <span class="op">=</span> pm.Normal(<span class="st">"a"</span>, y.mean(), <span class="dv">1</span>, shape<span class="op">=</span>J)  <span class="co"># per-series level</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    s <span class="op">=</span> pm.Exponential(<span class="st">"s"</span>, <span class="fl">1.0</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    pm.Normal(<span class="st">"obs"</span>, mu<span class="op">=</span>a[idx] <span class="op">+</span> b[idx]<span class="op">*</span>snap, sigma<span class="op">=</span>s, observed<span class="op">=</span>y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>idx</code> maps each row to its series, so <code>b[idx]</code> picks out the right effect for every observation. That indexing pattern is how every hierarchical model in PyMC is written.</p>
<p><strong>Note what is <em>not</em> here.</strong> No decision about how much to pool, no weighting scheme, no threshold for “enough data.” Those all come out of estimating <span class="math inline">\(\sigma_b\)</span>.</p>
<hr>
</section>
<section id="the-trap-write-it-the-obvious-way-and-it-breaks" class="level2">
<h2 class="anchored" data-anchor-id="the-trap-write-it-the-obvious-way-and-it-breaks">The Trap: Write It the Obvious Way and It Breaks</h2>
<p>The natural way to write the hierarchy is <code>b = pm.Normal("b", mu_b, sd_b, shape=J)</code> — the <em>centred</em> form, which reads exactly like the equation. On our data it produces:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Centred</th>
<th style="text-align: right;">Non-centred</th>
<th>Want</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Divergences</td>
<td style="text-align: right;"><strong>127</strong></td>
<td style="text-align: right;"><strong>1</strong></td>
<td>0</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\hat{R}\)</span></td>
<td style="text-align: right;"><strong>1.044</strong></td>
<td style="text-align: right;">1.002</td>
<td><span class="math inline">\(&lt; 1.01\)</span></td>
</tr>
<tr class="odd">
<td>ESS (bulk)</td>
<td style="text-align: right;">413</td>
<td style="text-align: right;">1,728</td>
<td><span class="math inline">\(&gt; 400\)</span></td>
</tr>
</tbody>
</table>
<p><strong>Why:</strong> when <span class="math inline">\(\sigma_b\)</span> is small, the <span class="math inline">\(b_j\)</span> must crowd into a narrow band, and the posterior takes on a funnel shape — wide where <span class="math inline">\(\sigma_b\)</span> is large, pinched where it is small. A sampler tuned for the wide part cannot navigate the neck, and reports divergences.</p>
<p><strong>Note how the alarms differ in kind.</strong> ESS <em>passes</em> — 413, just over the line, and you would not look twice. <span class="math inline">\(\hat{R}\)</span> at 1.044 fails, but it is the sort of near-miss people talk themselves out of. <strong>127 divergences against a threshold of exactly zero admits no such conversation.</strong> On hierarchical models divergences fire first and least ambiguously; do not wait for <span class="math inline">\(\hat{R}\)</span> to decide for you.</p>
<p><span class="neutral smaller">BMCP §4.6.1, <em>Posterior Geometry Matters</em> — the single most common failure in applied hierarchical modelling.</span></p>
</section>
</section>
<section id="reading-the-result" class="level1">
<h1>Reading the Result</h1>
<p>Shrinkage, measured — and checked against data the model never saw.</p>
<hr>
<section id="shrinkage-measured" class="level2">
<h2 class="anchored" data-anchor-id="shrinkage-measured">Shrinkage, Measured</h2>
<p>Fit both models. Compare each series’ estimated SNAP effect before and after pooling.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Series group</th>
<th style="text-align: right;">Unpooled spread</th>
<th style="text-align: right;">After pooling</th>
<th style="text-align: right;">Mean move</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Thin</strong> — 8 weeks (5 series)</td>
<td style="text-align: right;">0.108</td>
<td style="text-align: right;">0.010</td>
<td style="text-align: right;"><strong>0.120</strong></td>
</tr>
<tr class="even">
<td><strong>Full</strong> — 277 weeks (5 series)</td>
<td style="text-align: right;">0.055</td>
<td style="text-align: right;">0.037</td>
<td style="text-align: right;">0.015</td>
</tr>
</tbody>
</table>
<p><span class="key-result"><strong>The data-poor series moved 8.2 times further toward the group mean than the data-rich ones.</strong></span> Nobody told the model which series were thin. It inferred that from how much each series had to say.</p>
<p>Read the two right-hand columns together. The thin series’ apparent spread of <span class="math inline">\(0.108\)</span> nearly vanishes, while the full series <strong>keep most of theirs</strong> (<span class="math inline">\(0.055 \rightarrow 0.037\)</span>). The hierarchy did not flatten everything: it discarded spread that 8 weeks could not support and kept spread that 277 weeks could.</p>
<p><strong>That is the claim to be sceptical of, so the next slide tests it.</strong></p>
<hr>
</section>
<section id="checked-against-data-the-model-never-saw" class="level2">
<h2 class="anchored" data-anchor-id="checked-against-data-the-model-never-saw">Checked Against Data the Model Never Saw</h2>
<p>We thinned those five series ourselves, so the weeks we removed are still there. Compare each estimate against the SNAP effect actually observed in the held-out weeks.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Thin series</th>
<th style="text-align: right;">Unpooled</th>
<th style="text-align: right;">Hierarchical</th>
<th style="text-align: right;">Held-out truth</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CA_1_FOODS</td>
<td style="text-align: right;">0.286</td>
<td style="text-align: right;">0.097</td>
<td style="text-align: right;">0.087</td>
</tr>
<tr class="even">
<td>CA_3_FOODS</td>
<td style="text-align: right;">0.105</td>
<td style="text-align: right;">0.082</td>
<td style="text-align: right;">0.102</td>
</tr>
<tr class="odd">
<td>TX_1_FOODS</td>
<td style="text-align: right;">0.052</td>
<td style="text-align: right;">0.075</td>
<td style="text-align: right;">0.082</td>
</tr>
<tr class="even">
<td>TX_3_FOODS</td>
<td style="text-align: right;">0.219</td>
<td style="text-align: right;">0.091</td>
<td style="text-align: right;">0.072</td>
</tr>
<tr class="odd">
<td>WI_2_FOODS</td>
<td style="text-align: right;">0.338</td>
<td style="text-align: right;">0.103</td>
<td style="text-align: right;">0.207</td>
</tr>
<tr class="even">
<td><strong>RMSE against truth</strong></td>
<td style="text-align: right;"><strong>0.126</strong></td>
<td style="text-align: right;"><strong>0.049</strong></td>
<td style="text-align: right;">—</td>
</tr>
</tbody>
</table>
<p><strong>Partial pooling was two and a half times more accurate</strong>, beating the unpooled fit on four series out of five. Those estimates were not just noisy — they were confidently wrong, and the confidence came from 8 weeks of data.</p>
<p><span class="neutral smaller">Borrowing strength is not a figure of speech: the thin series were estimated better <em>because</em> the other five existed.</span></p>
<hr>
</section>
<section id="what-the-model-actually-concluded" class="level2">
<h2 class="anchored" data-anchor-id="what-the-model-actually-concluded">What the Model Actually Concluded</h2>
<p>The estimated hierarchy: <span class="math inline">\(\mu_b = 0.077\)</span> with a 94% HDI of <span class="math inline">\([0.016,\ 0.150]\)</span>, and <span class="math inline">\(\sigma_b = 0.066\)</span>.</p>
<p>In words: a SNAP week lifts FOODS units by roughly <strong>8%</strong>, and stores genuinely differ around that by about <strong>7 percentage points</strong>. Both numbers are answers, and the second one is the one no point estimate would have given you.</p>
<div class="warningbox">
<p><strong>It does not license the store-level policy the unpooled fit suggested.</strong> An analyst reading the unpooled numbers would report uplifts from <span class="math inline">\(5\%\)</span> to <span class="math inline">\(40\%\)</span> and stock accordingly. The held-out weeks say that range was mostly noise — but <span class="math inline">\(\sigma_b = 0.066\)</span> says it is not <em>all</em> noise either.</p>
</div>
<p><strong>The defensible recommendation:</strong> plan on an 8% FOODS uplift everywhere, allow real but modest store variation around it, and do not act on a store’s own estimate until that store has the weeks to support one.</p>
</section>
</section>
<section id="key-takeaways" class="level1">
<h1>Key Takeaways</h1>
<p>What hierarchy buys, and what it costs.</p>
<hr>
<section id="lecture-11-part-2-key-takeaways" class="level2">
<h2 class="anchored" data-anchor-id="lecture-11-part-2-key-takeaways">Lecture 11 Part 2: Key Takeaways</h2>
<div class="keybox">
<ol type="1">
<li><p><strong>Ask what may be pooled before you pool it.</strong> Groups must be <strong>exchangeable</strong>. FOODS and HOBBIES are not, and no amount of good sampling fixes a hierarchy built over the wrong set.</p></li>
<li><p><strong>Complete pooling</strong> denies groups differ; <strong>no pooling</strong> lets a group with 8 observations report noise as a finding. You have used both without naming them.</p></li>
<li><p><strong>Partial pooling</strong> gives each group its own parameter drawn from a shared distribution, and estimates how much groups genuinely differ.</p></li>
<li><p><strong>Shrinkage is automatic and proportionate.</strong> Our thin series moved <strong>8.1<span class="math inline">\(\times\)</span></strong> further toward the group mean than data-rich ones, with nobody specifying that — and on held-out weeks it was <strong>2.6<span class="math inline">\(\times\)</span></strong> more accurate.</p></li>
<li><p>This is <strong>regularization for the sixth time</strong> — and the only version where the shrinkage strength is estimated rather than tuned.</p></li>
<li><p><strong>Write it non-centred.</strong> The obvious form gave 127 divergences; the reparameterized form gave 1. Same model, different geometry — and divergences objected loudest, against a threshold that allows no argument.</p></li>
</ol>
</div>
<p><span class="neutral">Next: Bayesian linear regression — coefficients as distributions, and what you can ask them.</span></p>
<hr>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<div id="refs" role="list">

</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>