<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.33">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Lab 6: Regularization — Breaking OLS, Then Rescuing It – Business Forecasting — Workbook</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/Lecture07_lab.html" rel="next">
<link href="../chapters/Lecture05_lab.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-c1b08d31956f1824f457e0b6984faaea.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/Lecture01_lab.html">Labs</a></li><li class="breadcrumb-item"><a href="../chapters/Lecture06_lab.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Lab 6: Regularization — Breaking OLS, Then Rescuing It</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Business Forecasting — Workbook</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Labs</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture01_lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Lab 1: Benchmarks and Exponential Smoothing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture02_lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Lab 2: Stationarity, ARIMA, and Granger Causality</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture03_lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Lab 3: GAMs, Prophet, and Several Seasons at Once</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture04_lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Lab 4: Decision Trees — Reading One, and Finding Where It Breaks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture05_lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Lab 5: Tree Ensembles — Averaging, Then Boosting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture06_lab.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Lab 6: Regularization — Breaking OLS, Then Rescuing It</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture07_lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Lab 7: Your First Network — and Why One Run Proves Nothing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture08_lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Lab 8: Convolutions — What the Filter Can Actually See</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture09_Part1_lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Lab 9 Part 1: Recurrence — and When Gates Are Not Worth It</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture09_Part2_lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Lab 9 Part 2: Attention — and the Line You Cannot Forget</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture10_lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Lab 10: Priors, Posteriors, and Checking the Sampler</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture11_Part1_lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Lab 11 Part 1: Structural Time Series — and Two Ways to Get the Interval Wrong</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture11_Part2_lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Lab 11 Part 2: Partial Pooling — and the Question That Comes Before It</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture12_lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Lab 12: Elasticity — What the Coefficient Means, and What It Costs to Get Wrong</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Assignments</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/HW01_Part1_ETS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Homework 1, Part 1: Exponential Smoothing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/HW01_Part2_ARIMA_VAR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Homework 1, Part 2: ARIMA, VAR &amp; Method Comparison</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/HW02_GAMs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Homework 2: Generalized Additive Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/HW03_Trees_RF.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Homework 3: Decision Trees and Random Forests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/HW04_XGBoost_Regularization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Homework 4: Boosted Trees and Regularization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/HW05_Part1_FFN_CNN.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Homework 5: Deep Learning for Time Series</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/HW05_Part2_Sequence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Homework 5: Deep Learning for Time Series</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/HW05_Part3_Comparison.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Homework 5: Deep Learning for Time Series</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/HW06_Part1_Foundations_TS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Homework 6: Bayesian Foundations, Time Series, and Hierarchical Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/HW06_Part2_Hierarchical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Homework 6: Bayesian Foundations, Time Series, and Hierarchical Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/HW07_Bayesian_Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Homework 7: Bayesian Linear Regression</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#what-we-are-doing" id="toc-what-we-are-doing" class="nav-link active" data-scroll-target="#what-we-are-doing"><span class="header-section-number">6.1</span> What we are doing</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup"><span class="header-section-number">6.2</span> Setup</a></li>
  <li><a href="#step-1-break-it" id="toc-step-1-break-it" class="nav-link" data-scroll-target="#step-1-break-it"><span class="header-section-number">6.3</span> Step 1 — Break it</a></li>
  <li><a href="#step-2-two-penalties-two-behaviors" id="toc-step-2-two-penalties-two-behaviors" class="nav-link" data-scroll-target="#step-2-two-penalties-two-behaviors"><span class="header-section-number">6.4</span> Step 2 — Two penalties, two behaviors</a></li>
  <li><a href="#step-3-the-path-and-the-order-features-die-in" id="toc-step-3-the-path-and-the-order-features-die-in" class="nav-link" data-scroll-target="#step-3-the-path-and-the-order-features-die-in"><span class="header-section-number">6.5</span> Step 3 — The path, and the order features die in</a></li>
  <li><a href="#step-4-choosing-alpha-and-the-one-standard-error-rule" id="toc-step-4-choosing-alpha-and-the-one-standard-error-rule" class="nav-link" data-scroll-target="#step-4-choosing-alpha-and-the-one-standard-error-rule"><span class="header-section-number">6.6</span> Step 4 — Choosing alpha, and the one-standard-error rule</a></li>
  <li><a href="#step-5-why-your-cv-number-looks-worse-than-the-truth" id="toc-step-5-why-your-cv-number-looks-worse-than-the-truth" class="nav-link" data-scroll-target="#step-5-why-your-cv-number-looks-worse-than-the-truth"><span class="header-section-number">6.7</span> Step 5 — Why your CV number looks worse than the truth</a></li>
  <li><a href="#before-you-leave" id="toc-before-you-leave" class="nav-link" data-scroll-target="#before-you-leave"><span class="header-section-number">6.8</span> Before you leave</a></li>
  <li><a href="#what-your-run-should-produce" id="toc-what-your-run-should-produce" class="nav-link" data-scroll-target="#what-your-run-should-produce"><span class="header-section-number">6.9</span> What your run should produce</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/Lecture01_lab.html">Labs</a></li><li class="breadcrumb-item"><a href="../chapters/Lecture06_lab.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Lab 6: Regularization — Breaking OLS, Then Rescuing It</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Lab 6: Regularization — Breaking OLS, Then Rescuing It</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><em>Run this one live: <a href="../../labs/Lecture06_lab.html">the executable lab</a>.</em></p>
<section id="what-we-are-doing" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="what-we-are-doing"><span class="header-section-number">6.1</span> What we are doing</h2>
<p>Lecture 6 claimed that ordinary least squares breaks when you have many predictors relative to observations — coefficient variance grows with <span class="math inline">\(k\)</span>, correlated predictors produce wild offsetting estimates, and past <span class="math inline">\(k &gt; n\)</span> there is no unique solution at all.</p>
<p>Today you will break it on purpose, watch exactly how it fails, and then fix it with one line.</p>
<p>Same series as Labs 4 and 5: daily units for CA_1 FOODS. But we now engineer the feature set an analyst would actually build — 28 consecutive lags, weekly and annual lags, rolling statistics, Fourier terms, day-of-week dummies — which is how you end up with more predictors than you meant to have.</p>
<p><strong>Suggested time:</strong> ~40 minutes · <strong>You will need:</strong> <code>pandas</code>, <code>numpy</code>, <code>matplotlib</code>, <code>scikit-learn</code>, and <code>data/processed/m5_daily.csv</code>.</p>
<hr>
</section>
<section id="setup" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="setup"><span class="header-section-number">6.2</span> Setup</h2>
<div id="031ccf36" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression, Lasso, Ridge</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> StandardScaler</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.pipeline <span class="im">import</span> make_pipeline</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> TimeSeriesSplit, cross_val_score</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">'ignore'</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pathlib <span class="im">import</span> Path</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> data_path(name):</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> base <span class="kw">in</span> (Path.cwd(), <span class="op">*</span>Path.cwd().parents):</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>        p <span class="op">=</span> base <span class="op">/</span> <span class="st">"data"</span> <span class="op">/</span> <span class="st">"processed"</span> <span class="op">/</span> name</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> p.exists():</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>            <span class="cf">return</span> p</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">raise</span> <span class="pp">FileNotFoundError</span>(</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"Could not find data/processed/</span><span class="sc">{</span>name<span class="sc">}</span><span class="ss">. "</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Run `python scripts/prep_m5.py` from the repository root first."</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>RANDOM_STATE <span class="op">=</span> <span class="dv">42</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>daily <span class="op">=</span> pd.read_csv(data_path(<span class="st">"m5_daily.csv"</span>), parse_dates<span class="op">=</span>[<span class="st">"date"</span>]).sort_values(<span class="st">"date"</span>)</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>u <span class="op">=</span> daily.set_index(<span class="st">"date"</span>)[<span class="st">"units"</span>]</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> L <span class="kw">in</span> <span class="bu">list</span>(<span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">29</span>)) <span class="op">+</span> [<span class="dv">35</span>, <span class="dv">42</span>, <span class="dv">49</span>, <span class="dv">56</span>, <span class="dv">364</span>, <span class="dv">365</span>, <span class="dv">366</span>]:</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>    daily[<span class="ss">f"lag</span><span class="sc">{</span>L<span class="sc">}</span><span class="ss">"</span>] <span class="op">=</span> u.shift(L).values</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> W <span class="kw">in</span> (<span class="dv">7</span>, <span class="dv">14</span>, <span class="dv">28</span>, <span class="dv">91</span>, <span class="dv">364</span>):</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>    daily[<span class="ss">f"roll</span><span class="sc">{</span>W<span class="sc">}</span><span class="ss">_mean"</span>] <span class="op">=</span> u.shift(<span class="dv">1</span>).rolling(W).mean().values</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>    daily[<span class="ss">f"roll</span><span class="sc">{</span>W<span class="sc">}</span><span class="ss">_std"</span>]  <span class="op">=</span> u.shift(<span class="dv">1</span>).rolling(W).std().values</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>daily[<span class="st">"dow"</span>] <span class="op">=</span> daily[<span class="st">"date"</span>].dt.dayofweek</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>daily[<span class="st">"doy"</span>] <span class="op">=</span> daily[<span class="st">"date"</span>].dt.dayofyear</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> k <span class="kw">in</span> (<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>):</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>    daily[<span class="ss">f"sin</span><span class="sc">{</span>k<span class="sc">}</span><span class="ss">"</span>] <span class="op">=</span> np.sin(<span class="dv">2</span><span class="op">*</span>np.pi<span class="op">*</span>k<span class="op">*</span>daily.doy<span class="op">/</span><span class="dv">365</span>)</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>    daily[<span class="ss">f"cos</span><span class="sc">{</span>k<span class="sc">}</span><span class="ss">"</span>] <span class="op">=</span> np.cos(<span class="dv">2</span><span class="op">*</span>np.pi<span class="op">*</span>k<span class="op">*</span>daily.doy<span class="op">/</span><span class="dv">365</span>)</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>daily <span class="op">=</span> pd.concat([daily, pd.get_dummies(daily.dow, prefix<span class="op">=</span><span class="st">"dow"</span>)], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>FEATURES <span class="op">=</span> ([c <span class="cf">for</span> c <span class="kw">in</span> daily.columns <span class="cf">if</span> c.startswith((<span class="st">"lag"</span>, <span class="st">"roll"</span>, <span class="st">"sin"</span>, <span class="st">"cos"</span>, <span class="st">"dow_"</span>))]</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>            <span class="op">+</span> [<span class="st">"snap"</span>, <span class="st">"is_event"</span>, <span class="st">"doy"</span>, <span class="st">"avg_price"</span>])</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> daily.dropna(subset<span class="op">=</span>[c <span class="cf">for</span> c <span class="kw">in</span> FEATURES <span class="cf">if</span> c.startswith((<span class="st">"lag"</span>, <span class="st">"roll"</span>))]).copy()</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>N_TEST <span class="op">=</span> <span class="dv">365</span></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>train, test <span class="op">=</span> df.iloc[:<span class="op">-</span>N_TEST], df.iloc[<span class="op">-</span>N_TEST:]</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>X_train, y_train <span class="op">=</span> train[FEATURES].values.astype(<span class="bu">float</span>), train[<span class="st">"units"</span>].values</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>X_test,  y_test  <span class="op">=</span> test[FEATURES].values.astype(<span class="bu">float</span>),  test[<span class="st">"units"</span>].values</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>rmse <span class="op">=</span> <span class="kw">lambda</span> a, b: <span class="bu">float</span>(np.sqrt(np.mean((np.asarray(a) <span class="op">-</span> np.asarray(b)) <span class="op">**</span> <span class="dv">2</span>)))</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"k = </span><span class="sc">{</span><span class="bu">len</span>(FEATURES)<span class="sc">}</span><span class="ss"> features, n_train = </span><span class="sc">{</span><span class="bu">len</span>(X_train)<span class="sc">}</span><span class="ss">, n/k = </span><span class="sc">{</span><span class="bu">len</span>(X_train)<span class="op">/</span><span class="bu">len</span>(FEATURES)<span class="sc">:.1f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note how easily 62 predictors appeared. Nobody set out to build a 62-parameter model; it is what routine feature engineering produces.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Walkthrough
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Look at what the setup does, because nothing in it is unreasonable.</p>
<p>Twenty-eight consecutive lags, because you don’t know which one matters. A few weekly lags — 35, 42, 49, 56. Last year’s lags, 364, 365, 366. Rolling means and standard deviations at five windows. Three Fourier pairs for annual seasonality. Day-of-week dummies. Then SNAP, events, day-of-year and price.</p>
<pre><code>k = 62 features, n_train = 1210, n/k = 19.5</code></pre>
<p>Sixty-two predictors. Thirty-five lags, ten rolling statistics, six Fourier terms, seven day-of-week dummies, four others.</p>
<p>Nobody sat down and decided to fit a sixty-two-parameter model. Every one of those columns was a defensible small decision, and the total is what routine feature engineering produces. That is the honest version of how this problem arrives: not from ambition, from diligence.</p>
<p>Right now the ratio is comfortable — about twenty observations per parameter. Hold onto that number, because Step 1 is going to take it apart.</p>
</div>
</div>
</div>
</section>
<section id="step-1-break-it" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="step-1-break-it"><span class="header-section-number">6.3</span> Step 1 — Break it</h2>
<p>With 1,210 training rows and 62 features, OLS is fine. Now shrink the training window and watch.</p>
<div id="df763149" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>rows <span class="op">=</span> []</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> n <span class="kw">in</span> (<span class="dv">1210</span>, <span class="dv">400</span>, <span class="dv">200</span>, <span class="dv">120</span>, <span class="dv">80</span>):</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    sub <span class="op">=</span> train.iloc[<span class="op">-</span>n:]</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    sc <span class="op">=</span> StandardScaler().fit(sub[FEATURES].values.astype(<span class="bu">float</span>))</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    Xs <span class="op">=</span> sc.transform(sub[FEATURES].values.astype(<span class="bu">float</span>))</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    Xt <span class="op">=</span> sc.transform(X_test)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    y  <span class="op">=</span> sub[<span class="st">"units"</span>].values</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    ols <span class="op">=</span> LinearRegression().fit(Xs, y)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    rid <span class="op">=</span> Ridge(alpha<span class="op">=</span><span class="dv">100</span>).fit(Xs, y)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    rows.append({<span class="st">"n"</span>: n, <span class="st">"n/k"</span>: <span class="bu">round</span>(n<span class="op">/</span><span class="bu">len</span>(FEATURES), <span class="dv">1</span>),</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"OLS_max_coef"</span>: <span class="ss">f"</span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">abs</span>(ols.coef_)<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:,.0f}</span><span class="ss">"</span>,</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"OLS_test_RMSE"</span>: <span class="ss">f"</span><span class="sc">{</span>rmse(y_test, ols.predict(Xt))<span class="sc">:,.0f}</span><span class="ss">"</span>,</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"Ridge_test_RMSE"</span>: <span class="ss">f"</span><span class="sc">{</span>rmse(y_test, rid.predict(Xt))<span class="sc">:,.0f}</span><span class="ss">"</span>})</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(pd.DataFrame(rows).to_string(index<span class="op">=</span><span class="va">False</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Read that table across, then down.</strong> As the training window shrinks, the largest OLS coefficient grows from about 150 to the hundreds of thousands, and the test RMSE from 280 into the millions. Nothing about the <em>problem</em> changed — same features, same target, same test set. Only the ratio of observations to parameters.</p>
<p>Ridge, with a one-line change, degrades gracefully across the entire range.</p>
<p>That is Lecture 6’s opening argument, and you just measured it.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Walkthrough
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We keep the features and the test set fixed and shrink only the training window. Four years, then about one, then two hundred days, then a hundred and twenty, then eighty. Same problem throughout. Only the ratio changes.</p>
<pre><code>   n  n/k OLS_max_coef OLS_test_RMSE Ridge_test_RMSE
1210 19.5          153           280             278
 400  6.5          636         2,071             323
 200  3.2        1,364         5,874             363
 120  1.9    1,049,739     3,578,141             621
  80  1.3      355,629     2,072,167             770</code></pre>
<p>Read across the OLS columns. At twenty observations per parameter, the largest coefficient is <strong>153</strong> and the test RMSE is <strong>280</strong> — a perfectly respectable model. At six observations per parameter, the coefficient is 636 and the error has multiplied by seven. At three, it is 1,364 and 5,874.</p>
<p>And then the bottom two rows stop being a degradation and become an explosion. The largest coefficient is <strong>over a million.</strong> The test RMSE is <strong>three and a half million</strong> — on a series where a busy day is four thousand units.</p>
<p>Now here is the part I want you to take away, and it is not in the printed table.</p>
<p>At n = 120, that model’s <strong>training</strong> RMSE is about <strong>145.</strong> It looks fine. If you fitted it and looked only at how it fits the data you gave it, you would ship it. It is the best-fitting model on this slide and it is wrong by a factor of a thousand on data it has not seen.</p>
<p>One technical point, because a careful student will ask. We never crossed the line the lecture warned about. Sixty-two features and eighty rows — there are still more observations than parameters, so OLS has a unique solution the whole way down this table. <strong>You do not need k greater than n to get this.</strong> Twenty-eight consecutive lags of a smooth series are nearly collinear with one another, and near-collinearity is enough. The matrix does not have to be singular, only close to it.</p>
<p>Now the right-hand column. Same data, same features, same rows — <code>Ridge(alpha=100)</code> instead of <code>LinearRegression()</code>. One word changed. 278, 323, 363, 621, 770.</p>
<p>It gets worse as data gets scarcer, which it should. But it degrades <em>gracefully</em>, and at the row where OLS is out by three and a half million, Ridge is at 621 — roughly the benchmark. Not good, but the model is still a model. That is Lecture 6’s opening argument, and you just measured it.</p>
</div>
</div>
</div>
</section>
<section id="step-2-two-penalties-two-behaviors" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="step-2-two-penalties-two-behaviors"><span class="header-section-number">6.4</span> Step 2 — Two penalties, two behaviors</h2>
<p>Back to the full training set. Fit Ridge and LASSO at a comparable penalty and count what survives.</p>
<div id="4dd1a73d" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>sc <span class="op">=</span> StandardScaler().fit(X_train)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>Xs, Xts <span class="op">=</span> sc.transform(X_train), sc.transform(X_test)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, model <span class="kw">in</span> [(<span class="st">"OLS"</span>,   LinearRegression()),</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>                    (<span class="st">"Ridge"</span>, Ridge(alpha<span class="op">=</span><span class="dv">100</span>)),</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>                    (<span class="st">"LASSO"</span>, Lasso(alpha<span class="op">=</span><span class="dv">20</span>, max_iter<span class="op">=</span><span class="dv">50000</span>))]:</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    m <span class="op">=</span> model.fit(Xs, y_train)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    nz <span class="op">=</span> <span class="bu">int</span>(np.<span class="bu">sum</span>(m.coef_ <span class="op">!=</span> <span class="dv">0</span>))</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>name<span class="sc">:&lt;6}</span><span class="ss"> test RMSE </span><span class="sc">{</span>rmse(y_test, m.predict(Xts))<span class="sc">:5,.0f}</span><span class="ss">   non-zero coefficients </span><span class="sc">{</span>nz<span class="sc">:3d}</span><span class="ss">/</span><span class="sc">{</span><span class="bu">len</span>(FEATURES)<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Ridge keeps every coefficient and shrinks them. LASSO sets most of them to exactly zero. Neither is “better” — they encode different beliefs about how many predictors genuinely matter.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Walkthrough
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Back to the full training set, where OLS was fine, and now compare the two penalties.</p>
<pre><code>  OLS    test RMSE   280   non-zero coefficients  62/62
  Ridge  test RMSE   278   non-zero coefficients  62/62
  LASSO  test RMSE   286   non-zero coefficients  21/62</code></pre>
<p>I want you to notice the disappointing thing first, because if I skip it you will notice it anyway and trust me less.</p>
<p><strong>On the full training set, regularization buys essentially nothing.</strong> Ridge is two units better than OLS. LASSO is six units worse. With nineteen observations per parameter there was no problem to solve, and the penalty solved it.</p>
<p>That is the correct lesson, not a failed demo. Regularization is <strong>insurance</strong>, and Step 1 is the fire. You do not judge insurance by what it pays out in a year when the house doesn’t burn down.</p>
<p>But look at the last column, because that is where the two penalties differ in kind and not just in degree.</p>
<p>Ridge keeps all sixty-two coefficients and shrinks them toward zero. LASSO sets forty-one of them to <strong>exactly</strong> zero and keeps twenty-one.</p>
<p>So for six units of RMSE — about two percent — LASSO handed you a model with a third as many moving parts. That is not an accuracy trade, it is a <em>communicability</em> trade. Twenty-one coefficients is a model you can print and discuss. Sixty-two is a model you can only run.</p>
<p>Neither penalty is better. They encode different beliefs: Ridge believes many predictors each matter a little, LASSO believes a few matter and the rest are noise. Which belief is right is a question about your data, and in Step 3 you get to see which one this series votes for.</p>
</div>
</div>
</div>
</section>
<section id="step-3-the-path-and-the-order-features-die-in" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="step-3-the-path-and-the-order-features-die-in"><span class="header-section-number">6.5</span> Step 3 — The path, and the order features die in</h2>
<p>Lecture 6 argued that the <strong>order</strong> predictors leave is a more stable finding than any single coefficient table. Produce that ordering.</p>
<div id="f6e9e040" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>alphas <span class="op">=</span> np.logspace(<span class="op">-</span><span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">60</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>paths <span class="op">=</span> []</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> a <span class="kw">in</span> alphas:</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    paths.append(Lasso(alpha<span class="op">=</span>a, max_iter<span class="op">=</span><span class="dv">50000</span>).fit(Xs, y_train).coef_)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>paths <span class="op">=</span> np.array(paths)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="fl">3.6</span>))</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].plot(np.log10(alphas), paths, lw<span class="op">=</span><span class="fl">0.8</span>)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xlabel(<span class="st">"log10(alpha)"</span>)<span class="op">;</span> axes[<span class="dv">0</span>].set_ylabel(<span class="st">"coefficient"</span>)<span class="op">;</span> axes[<span class="dv">0</span>].set_title(<span class="st">"regularization path"</span>)</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].plot(np.log10(alphas), (paths <span class="op">!=</span> <span class="dv">0</span>).<span class="bu">sum</span>(<span class="dv">1</span>), marker<span class="op">=</span><span class="st">"."</span>, ms<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xlabel(<span class="st">"log10(alpha)"</span>)<span class="op">;</span> axes[<span class="dv">1</span>].set_ylabel(<span class="st">"non-zero coefficients"</span>)<span class="op">;</span> axes[<span class="dv">1</span>].set_title(<span class="st">"model size"</span>)</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cb132535" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>survivors, order <span class="op">=</span> <span class="bu">set</span>(FEATURES), []</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> a, coefs <span class="kw">in</span> <span class="bu">zip</span>(alphas, paths):</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    nz <span class="op">=</span> <span class="bu">set</span>(np.array(FEATURES)[coefs <span class="op">!=</span> <span class="dv">0</span>])</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> gone <span class="kw">in</span> survivors <span class="op">-</span> nz:</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>        order.append(gone)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    survivors <span class="op">=</span> nz</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"the last 8 features standing, in reverse order of elimination:"</span>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> f <span class="kw">in</span> <span class="bu">reversed</span>(order[<span class="op">-</span><span class="dv">8</span>:]):</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"   </span><span class="sc">{</span>f<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Look at what survived
</div>
</div>
<div class="callout-body-container callout-body">
<p>Read that list of survivors and find the pattern in the lag numbers before reading on.</p>
<p>Almost all of them are <strong>multiples of 7</strong>. Nobody told the model this series has a weekly cycle, and there is no explicit “week” feature among the lags. Under increasing penalty the LASSO independently kept the lags that align with day-of-week and discarded the ones that do not.</p>
<p>That is what makes the dropout ordering worth reporting: it recovered the structure of the series, not just a ranking of columns.</p>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Walkthrough
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Sixty LASSO fits along a grid of penalties, from 0.1 up to 1,000, and we plot every coefficient’s trajectory.</p>
<p>Each line is one feature. At the left, weak penalty, everything is alive. Move right and lines collapse onto zero one after another. By the right-hand edge — and I checked this — <strong>every single coefficient is zero.</strong> The model at alpha = 1,000 predicts the mean and nothing else.</p>
<p>The right panel is the same thing counted: model size against penalty. It is a staircase down from 62 to 0. At alpha = 100, nine features are left.</p>
<p>Lecture 6 argued that the <strong>order</strong> features leave is a more stable finding than any one coefficient table — coefficients wobble under resampling, the elimination order mostly does not. So let’s read the order.</p>
<pre><code>the last 8 features standing, in reverse order of elimination:
   lag28
   lag7
   lag35
   lag364
   lag14
   lag21
   lag1
   lag56</code></pre>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Try it
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<p>Pause here. Read those eight lag numbers and find the pattern before I say it.</p>
<ol start="28" type="1">
<li><ol start="7" type="1">
<li><ol start="35" type="1">
<li><ol start="364" type="1">
<li><ol start="14" type="1">
<li><ol start="21" type="1">
<li><ol start="56" type="1">
<li>Every one of them is a <strong>multiple of seven</strong> except <code>lag1</code>.</li>
</ol></li>
</ol></li>
</ol></li>
</ol></li>
</ol></li>
</ol></li>
</ol>
<p>Now think about what was available to be chosen. The feature set had twenty-eight consecutive lags — 1, 2, 3, all the way to 28. There is no “week” feature. Nothing in the data told the model that seven days is a meaningful interval. The day-of-week dummies were there as an alternative route to the same information, and the LASSO dropped those too.</p>
<p>Under increasing penalty, forced to give things up, it kept exactly the lags that align with day-of-week and discarded the ones that do not. It also kept <code>lag364</code> — which is fifty-two weeks, so the same-day-last-year lag that is <em>also</em> a multiple of seven, rather than <code>lag365</code>.</p>
<p>That is why the dropout ordering is worth reporting to someone. It did not just rank your columns. It recovered the structure of the series — a weekly cycle plus an annual echo — from a pile of undifferentiated lags. And it agrees with what the tree found on its own in Lab 4, when day-of-week took 79% of the importance. Two completely different model families, same finding.</p>
</div>
</div>
</div>
</section>
<section id="step-4-choosing-alpha-and-the-one-standard-error-rule" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="step-4-choosing-alpha-and-the-one-standard-error-rule"><span class="header-section-number">6.6</span> Step 4 — Choosing alpha, and the one-standard-error rule</h2>
<div id="6349c3a0" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>tscv <span class="op">=</span> TimeSeriesSplit(n_splits<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>grid <span class="op">=</span> np.logspace(<span class="op">-</span><span class="dv">1</span>, <span class="fl">2.5</span>, <span class="dv">30</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>means, ses <span class="op">=</span> [], []</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> a <span class="kw">in</span> grid:</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    s <span class="op">=</span> cross_val_score(make_pipeline(StandardScaler(), Lasso(alpha<span class="op">=</span>a, max_iter<span class="op">=</span><span class="dv">50000</span>)),</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>                        X_train, y_train, cv<span class="op">=</span>tscv, scoring<span class="op">=</span><span class="st">"neg_root_mean_squared_error"</span>)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    means.append(<span class="op">-</span>s.mean())<span class="op">;</span> ses.append(s.std()<span class="op">/</span>np.sqrt(<span class="bu">len</span>(s)))</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>means, ses <span class="op">=</span> np.array(means), np.array(ses)</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>i_min <span class="op">=</span> <span class="bu">int</span>(means.argmin())</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>threshold <span class="op">=</span> means[i_min] <span class="op">+</span> ses[i_min]</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>i_1se <span class="op">=</span> <span class="bu">int</span>(np.where(means <span class="op">&lt;=</span> threshold)[<span class="dv">0</span>].<span class="bu">max</span>())</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> label, i <span class="kw">in</span> [(<span class="st">"CV minimum"</span>, i_min), (<span class="st">"one-SE rule"</span>, i_1se)]:</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>    m <span class="op">=</span> make_pipeline(StandardScaler(), Lasso(alpha<span class="op">=</span>grid[i], max_iter<span class="op">=</span><span class="dv">50000</span>)).fit(X_train, y_train)</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>label<span class="sc">:&lt;12}</span><span class="ss"> alpha </span><span class="sc">{</span>grid[i]<span class="sc">:7.2f}</span><span class="ss">   CV </span><span class="sc">{</span>means[i]<span class="sc">:5,.0f}</span><span class="ss">   "</span></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"test </span><span class="sc">{</span>rmse(y_test, m.predict(X_test))<span class="sc">:5,.0f}</span><span class="ss">   non-zero </span><span class="sc">{</span><span class="bu">int</span>(np.<span class="bu">sum</span>(m[<span class="op">-</span><span class="dv">1</span>].coef_ <span class="op">!=</span> <span class="dv">0</span>))<span class="sc">:3d}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Your turn:</strong> plot the CV curve with its one-standard-error band, and mark both chosen alphas.</p>
<div id="3d907f74" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ---- your turn: uncomment and fill in the blank ----</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="co"># fig, ax = plt.subplots(figsize=(7, 3.4))</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co"># ax.plot(np.log10(grid), means)</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># ax.fill_between(np.log10(grid), means - ses, means + ses, alpha=0.2)</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co"># ax.axvline(np.log10(grid[i_min]), ls="--", label="CV minimum")</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="co"># ax.axvline(np.log10(___), ls=":", label="one-SE")        # &lt;- which index?</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="co"># ax.set_xlabel("log10(alpha)"); ax.set_ylabel("CV RMSE"); ax.legend()</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="co"># plt.tight_layout()</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The one-SE rule roughly halves the number of surviving features. <strong>Decide whether that trade is worth it here</strong> — and say what you would need to know about how the model will be used before you could answer properly.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Walkthrough
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>So far I have been picking penalties by hand. Now do it properly: five-fold <code>TimeSeriesSplit</code>, thirty candidate alphas, and — this matters — the scaler goes <strong>inside</strong> the pipeline, so it is refitted on each fold’s training rows and never sees the validation fold.</p>
<pre><code>  CV minimum   alpha   19.64   CV   323   test   286   non-zero  21
  one-SE rule  alpha   59.68   CV   346   test   309   non-zero  11</code></pre>
<p>Two ways to read the same CV curve.</p>
<p>The <strong>CV minimum</strong> takes the alpha with the best cross-validated score. Standard, and it lands on 21 features.</p>
<p>The <strong>one-standard-error rule</strong> takes the <em>largest</em> alpha — the simplest model — whose CV score is still within one standard error of the best. The argument is that the CV curve is itself an estimate with noise on it, so a model that is statistically indistinguishable from the best but much simpler is the better bet.</p>
<p>Here that means going from <strong>21 features to 11</strong>, and paying <strong>23 units of test RMSE</strong> for it — 286 up to 309, about eight percent.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Try it
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<p>Two things to do. First, uncomment the plot and fill in the blank — the one-SE index — so you can see the band and both verticals. Then answer the question the lab asks: is that trade worth it here?</p>
<p>I’ll give you the shape of the answer rather than the answer, because the honest reply is that <strong>the lab has not told you enough to decide.</strong></p>
<p>If this model is going into a dashboard that a person reads and questions, eleven coefficients against twenty-one is a real gain, and eight percent is cheap. If it is one component inside an automated replenishment system that nobody reads, you just paid eight percent for a property nobody consumes.</p>
<p>It is worth knowing what the eleven survivors are: <code>lag1</code>, <code>lag7</code>, <code>lag14</code>, <code>lag21</code>, <code>lag27</code>, <code>lag28</code>, <code>lag35</code>, <code>lag56</code>, <code>lag364</code>, the 364-day rolling mean, and <code>snap</code>. Nine lags, a level, and the SNAP flag. That is a model you could describe out loud in one sentence — and notice <code>snap</code> survived to the very end, which is the same feature permutation importance rescued in Lab 5.</p>
</div>
</div>
</div>
</section>
<section id="step-5-why-your-cv-number-looks-worse-than-the-truth" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="step-5-why-your-cv-number-looks-worse-than-the-truth"><span class="header-section-number">6.7</span> Step 5 — Why your CV number looks worse than the truth</h2>
<p>The CV RMSE above is noticeably higher than the test RMSE. That is not a mistake, and the reason is sitting in Step 1.</p>
<div id="fd4bbe43" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, (tr_idx, va_idx) <span class="kw">in</span> <span class="bu">enumerate</span>(tscv.split(X_train), <span class="dv">1</span>):</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>    m <span class="op">=</span> make_pipeline(StandardScaler(), Lasso(alpha<span class="op">=</span><span class="dv">20</span>, max_iter<span class="op">=</span><span class="dv">50000</span>)).fit(X_train[tr_idx], y_train[tr_idx])</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  fold </span><span class="sc">{</span>i<span class="sc">}</span><span class="ss">: train n=</span><span class="sc">{</span><span class="bu">len</span>(tr_idx)<span class="sc">:4d}</span><span class="ss"> (n/k=</span><span class="sc">{</span><span class="bu">len</span>(tr_idx)<span class="op">/</span><span class="bu">len</span>(FEATURES)<span class="sc">:4.1f}</span><span class="ss">)   "</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"val n=</span><span class="sc">{</span><span class="bu">len</span>(va_idx)<span class="sc">:3d}</span><span class="ss">   RMSE </span><span class="sc">{</span>rmse(y_train[va_idx], m.predict(X_train[va_idx]))<span class="sc">:5,.0f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Fold 1 trains on about 200 rows — the same data-starved regime that wrecked OLS in Step 1. The final model trains on all 1,210. So walk-forward CV on an expanding window is <strong>structurally pessimistic</strong>: it averages in early folds that are trained on far less data than the model you actually ship.</p>
<p>That is a reason to read the CV number as a conservative estimate, not a reason to abandon it — and emphatically not a reason to switch to random folds, which fix the pessimism by letting the model see the future.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Walkthrough
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>One loose end from Step 4 that you should not let pass. The CV score at the minimum was <strong>323</strong>. The test RMSE of that same model was <strong>286</strong>. Cross-validation was pessimistic by about 13%.</p>
<p>If those had gone the other way you would be worried. This direction has a specific cause, and it is sitting in Step 1.</p>
<pre><code>  fold 1: train n= 205 (n/k= 3.3)   val n=201   RMSE   433
  fold 2: train n= 406 (n/k= 6.5)   val n=201   RMSE   294
  fold 3: train n= 607 (n/k= 9.8)   val n=201   RMSE   325
  fold 4: train n= 808 (n/k=13.0)   val n=201   RMSE   257
  fold 5: train n=1009 (n/k=16.3)   val n=201   RMSE   308</code></pre>
<p>Look at fold 1. It trains on 205 rows — three observations per parameter. That is the row from Step 1’s table where OLS was already at 5,874, and it is scored as though it were the model you are going to ship. It comes in at 433, far worse than any other fold. The model you actually ship trains on all 1,210 rows. No fold ever saw that much data.</p>
<p>So expanding-window cross-validation is <strong>structurally pessimistic</strong>: it averages in early folds fitted on a fraction of your data. And you can put a number on how much that costs. The five folds average to 323. Drop fold 1 alone and the remaining four average to <strong>296</strong> — against a test RMSE of <strong>286.</strong> Almost the entire gap was that one starved fold. Two conclusions, and the second is the one that gets violated in practice.</p>
<p>First: read a walk-forward CV number as a <strong>conservative</strong> estimate. It is a lower bound on your model’s quality, not an unbiased estimate of it, and being conservative is a fine property in a forecast you are going to stake inventory on.</p>
<p>Second, and please do not do this: the pessimism is <strong>not</strong> a reason to switch to random k-fold splits. Random folds would fix the number, and they would fix it by training on Thursday to predict the previous Tuesday. The optimistic number you get back would be measuring your model’s ability to interpolate inside a period it has already seen, which is not the job. A pessimistic estimate of the right quantity beats an accurate estimate of the wrong one.</p>
</div>
</div>
</div>
</section>
<section id="before-you-leave" class="level2" data-number="6.8">
<h2 data-number="6.8" class="anchored" data-anchor-id="before-you-leave"><span class="header-section-number">6.8</span> Before you leave</h2>
<p>Add today’s best linear model to the scoreboard you have been building since Lab 4.</p>
<div id="5ef2675e" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>best <span class="op">=</span> make_pipeline(StandardScaler(), Lasso(alpha<span class="op">=</span>grid[i_min], max_iter<span class="op">=</span><span class="dv">50000</span>)).fit(X_train, y_train)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>board <span class="op">=</span> {</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Benchmark (same day last year)"</span>: rmse(y_test, test.units_lag365.values),</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Single tree (Lab 4)"</span>: <span class="dv">324</span>,</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Random Forest (Lab 5)"</span>: <span class="dv">248</span>,</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"XGBoost (Lab 5)"</span>: <span class="dv">244</span>,</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"LASSO, 62 features (today)"</span>: rmse(y_test, best.predict(X_test)),</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(pd.Series(board).<span class="bu">round</span>(<span class="dv">0</span>).astype(<span class="bu">int</span>).sort_values(ascending<span class="op">=</span><span class="va">False</span>).to_string())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p><strong>Discuss:</strong> The regularized linear model does <strong>not</strong> win here — the tree ensembles beat it on this series. Give one property of daily store sales that favors trees over an additive linear model, however many lags you give it.</p>
<p>Then the counterpoint, which matters for Homework 4: on the <em>weekly, 30-series</em> panel the ranking may not look the same. What is different about that problem that could change the answer?</p>
<p><strong>And the one to argue about:</strong> you have now fitted five model families to this one series. If you had to hand exactly one of them to a store manager who will not be retrained, and who will not retune anything for a year, which do you choose — and is it the one with the lowest RMSE?</p>
</blockquote>
<hr>
<p><em>Solutions posted to Canvas after class.</em></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Walkthrough
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<pre><code>Benchmark (same day last year)    625
Single tree (Lab 4)               324
LASSO, 62 features (today)        286
Random Forest (Lab 5)             248
XGBoost (Lab 5)                   244</code></pre>
<p>Today’s model, with six times as many features as the tree ensembles had, lands <strong>third</strong>.</p>
<p>Say that plainly rather than skating past it. Sixty-two engineered features, a properly cross-validated penalty, and a careful pipeline produced 286 — comfortably better than one tree, and comfortably worse than a Random Forest you fitted in two lines with no feature engineering at all in Lab 5.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Try it
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<p>Three questions for the board.</p>
<p><strong>Why trees win here.</strong> Name one property of daily store sales that favours a tree ensemble over an additive linear model, however many lags you feed it. It is in the tree you read out loud in Lab 4 — think about what happens on a weekend when yesterday was already busy, and whether a model that adds up separate effects can express that.</p>
<p><strong>The counterpoint, and this one matters for Homework 4.</strong> In Homework 4 you run this comparison on the weekly, thirty-series panel with forty-six features. The ranking may not come out the same. What is different about that problem that could change the answer? Think about how many observations per series you get at weekly frequency, and what pooling thirty series does to the noise.</p>
<p><strong>The one to argue about.</strong> You have now fitted five model families to this one series — a GAM in Homework 2, a tree, a forest, boosting, and a regularized linear model. Hand exactly one of them to a store manager who will never retune it and will not be retrained. Which, and is it the one with the lowest RMSE?</p>
<p>Notice the two properties this lab measured that RMSE does not see. The eleven-feature LASSO is the only model of the five you could write on a whiteboard. And Step 1 showed you which models fail <em>loudly</em> versus quietly — OLS at n=120 had a beautiful training fit and was wrong by a factor of a thousand. In a year, if this store’s data collection changes and the model quietly gets less data than it used to, which of your five would you rather be running unattended?</p>
<p>Solutions for the coded parts go up on Canvas after the deadline. Next week we leave linear models behind for good and start on neural networks.</p>
</div>
</div>
</div>
</section>
<section id="what-your-run-should-produce" class="level2" data-number="6.9">
<h2 data-number="6.9" class="anchored" data-anchor-id="what-your-run-should-produce"><span class="header-section-number">6.9</span> What your run should produce</h2>
<p>Your numbers will differ where a model is stochastic; these are the values this lab produces on the pinned environment.</p>
<p>Deterministic; whole lab runs in about 6 seconds.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Quantity</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Feature set</td>
<td><strong>62</strong> — 35 lags, 10 rolling stats, 6 Fourier, 7 dow dummies, 4 other · n/k = 19.5</td>
</tr>
<tr class="even">
<td>OLS as n shrinks (max|coef| / test RMSE)</td>
<td>1210: 153 / 280 · 400: 636 / 2,071 · 200: 1,364 / 5,874 · 120: <strong>1,049,739 / 3,578,141</strong> · 80: 355,629 / 2,072,167</td>
</tr>
<tr class="odd">
<td>Ridge over the same range</td>
<td>278 · 323 · 363 · 621 · 770</td>
</tr>
<tr class="even">
<td>OLS at n=120 — <em>training</em> RMSE</td>
<td><strong>145</strong> (not printed by the lab; worth saying out loud)</td>
</tr>
<tr class="odd">
<td>Full data, three models</td>
<td>OLS 280 (62/62) · Ridge 278 (62/62) · LASSO 286 (<strong>21</strong>/62)</td>
</tr>
<tr class="even">
<td>Last 8 LASSO survivors</td>
<td>lag28, lag7, lag35, lag364, lag14, lag21, lag1, lag56 — all multiples of 7 except <code>lag1</code></td>
</tr>
<tr class="odd">
<td>Coefficients alive at alpha = 1,000</td>
<td><strong>0</strong> (9 at alpha = 100)</td>
</tr>
<tr class="even">
<td>CV minimum</td>
<td>alpha 19.64 · CV 323 · test <strong>286</strong> · 21 features</td>
</tr>
<tr class="odd">
<td>One-SE rule</td>
<td>alpha 59.68 · CV 346 · test <strong>309</strong> · 11 features</td>
</tr>
<tr class="even">
<td>One-SE survivors</td>
<td>lag1, lag7, lag14, lag21, lag27, lag28, lag35, lag56, lag364, roll364_mean, <strong>snap</strong></td>
</tr>
<tr class="odd">
<td>CV folds</td>
<td>433 · 294 · 325 · 257 · 308 → mean <strong>323</strong>; without fold 1, <strong>296</strong> (test 286)</td>
</tr>
<tr class="even">
<td>Scoreboard</td>
<td>benchmark 625 · tree 324 · <strong>LASSO 286</strong> · RF 248 · XGBoost 244</td>
</tr>
</tbody>
</table>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/Lecture05_lab.html" class="pagination-link" aria-label="Lab 5: Tree Ensembles — Averaging, Then Boosting">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Lab 5: Tree Ensembles — Averaging, Then Boosting</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/Lecture07_lab.html" class="pagination-link" aria-label="Lab 7: Your First Network — and Why One Run Proves Nothing">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Lab 7: Your First Network — and Why One Run Proves Nothing</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>