<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.33">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>13&nbsp; Lab 11 Part 2: Partial Pooling — and the Question That Comes Before It – Business Forecasting — Workbook</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/Lecture12_lab.html" rel="next">
<link href="../chapters/Lecture11_Part1_lab.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-c1b08d31956f1824f457e0b6984faaea.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/Lecture01_lab.html">Labs</a></li><li class="breadcrumb-item"><a href="../chapters/Lecture11_Part2_lab.html"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Lab 11 Part 2: Partial Pooling — and the Question That Comes Before It</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Business Forecasting — Workbook</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Labs</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture01_lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Lab 1: Benchmarks and Exponential Smoothing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture02_lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Lab 2: Stationarity, ARIMA, and Granger Causality</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture03_lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Lab 3: GAMs, Prophet, and Several Seasons at Once</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture04_lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Lab 4: Decision Trees — Reading One, and Finding Where It Breaks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture05_lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Lab 5: Tree Ensembles — Averaging, Then Boosting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture06_lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Lab 6: Regularization — Breaking OLS, Then Rescuing It</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture07_lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Lab 7: Your First Network — and Why One Run Proves Nothing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture08_lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Lab 8: Convolutions — What the Filter Can Actually See</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture09_Part1_lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Lab 9 Part 1: Recurrence — and When Gates Are Not Worth It</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture09_Part2_lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Lab 9 Part 2: Attention — and the Line You Cannot Forget</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture10_lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Lab 10: Priors, Posteriors, and Checking the Sampler</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture11_Part1_lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Lab 11 Part 1: Structural Time Series — and Two Ways to Get the Interval Wrong</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture11_Part2_lab.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Lab 11 Part 2: Partial Pooling — and the Question That Comes Before It</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Lecture12_lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Lab 12: Elasticity — What the Coefficient Means, and What It Costs to Get Wrong</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Assignments</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/HW01_Part1_ETS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Homework 1, Part 1: Exponential Smoothing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/HW01_Part2_ARIMA_VAR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Homework 1, Part 2: ARIMA, VAR &amp; Method Comparison</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/HW02_GAMs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Homework 2: Generalized Additive Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/HW03_Trees_RF.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Homework 3: Decision Trees and Random Forests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/HW04_XGBoost_Regularization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Homework 4: Boosted Trees and Regularization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/HW05_Part1_FFN_CNN.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Homework 5: Deep Learning for Time Series</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/HW05_Part2_Sequence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Homework 5: Deep Learning for Time Series</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/HW05_Part3_Comparison.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Homework 5: Deep Learning for Time Series</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/HW06_Part1_Foundations_TS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Homework 6: Bayesian Foundations, Time Series, and Hierarchical Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/HW06_Part2_Hierarchical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Homework 6: Bayesian Foundations, Time Series, and Hierarchical Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/HW07_Bayesian_Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Homework 7: Bayesian Linear Regression</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#what-we-are-doing" id="toc-what-we-are-doing" class="nav-link active" data-scroll-target="#what-we-are-doing"><span class="header-section-number">13.1</span> What we are doing</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup"><span class="header-section-number">13.2</span> Setup</a></li>
  <li><a href="#step-1-build-the-imbalance" id="toc-step-1-build-the-imbalance" class="nav-link" data-scroll-target="#step-1-build-the-imbalance"><span class="header-section-number">13.3</span> Step 1 — Build the imbalance</a></li>
  <li><a href="#step-2-fit-it-and-admire-the-shrinkage" id="toc-step-2-fit-it-and-admire-the-shrinkage" class="nav-link" data-scroll-target="#step-2-fit-it-and-admire-the-shrinkage"><span class="header-section-number">13.4</span> Step 2 — Fit it, and admire the shrinkage</a></li>
  <li><a href="#step-3-grade-it-against-the-weeks-it-never-saw" id="toc-step-3-grade-it-against-the-weeks-it-never-saw" class="nav-link" data-scroll-target="#step-3-grade-it-against-the-weeks-it-never-saw"><span class="header-section-number">13.5</span> Step 3 — Grade it against the weeks it never saw</a></li>
  <li><a href="#step-4-find-out-what-went-wrong" id="toc-step-4-find-out-what-went-wrong" class="nav-link" data-scroll-target="#step-4-find-out-what-went-wrong"><span class="header-section-number">13.6</span> Step 4 — Find out what went wrong</a></li>
  <li><a href="#step-5-do-it-on-the-exchangeable-set" id="toc-step-5-do-it-on-the-exchangeable-set" class="nav-link" data-scroll-target="#step-5-do-it-on-the-exchangeable-set"><span class="header-section-number">13.7</span> Step 5 — Do it on the exchangeable set</a></li>
  <li><a href="#step-6-the-trap-in-the-code" id="toc-step-6-the-trap-in-the-code" class="nav-link" data-scroll-target="#step-6-the-trap-in-the-code"><span class="header-section-number">13.8</span> Step 6 — The trap in the code</a></li>
  <li><a href="#before-you-leave" id="toc-before-you-leave" class="nav-link" data-scroll-target="#before-you-leave"><span class="header-section-number">13.9</span> Before you leave</a></li>
  <li><a href="#what-your-run-should-produce" id="toc-what-your-run-should-produce" class="nav-link" data-scroll-target="#what-your-run-should-produce"><span class="header-section-number">13.10</span> What your run should produce</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/Lecture01_lab.html">Labs</a></li><li class="breadcrumb-item"><a href="../chapters/Lecture11_Part2_lab.html"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Lab 11 Part 2: Partial Pooling — and the Question That Comes Before It</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Lab 11 Part 2: Partial Pooling — and the Question That Comes Before It</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><em>Run this one live: <a href="../../labs/Lecture11_Part2_lab.html">the executable lab</a>.</em></p>
<section id="what-we-are-doing" class="level2" data-number="13.1">
<h2 data-number="13.1" class="anchored" data-anchor-id="what-we-are-doing"><span class="header-section-number">13.1</span> What we are doing</h2>
<p>A hierarchical model lets thirty series share information: each gets its own effect, drawn from a common distribution the data also estimates. Data-poor series borrow from data-rich ones, and nobody has to choose the weights.</p>
<p>That is genuinely powerful, and today you will watch it work. You will also watch it produce a confidently wrong answer — on the same data, with clean diagnostics, textbook shrinkage, and no warning of any kind.</p>
<p>The difference between the two runs is not the code. It is a decision made before any code was written: <strong>which series belong in the same hierarchy.</strong></p>
<p><strong>Time:</strong> ~45 minutes · <strong>You will need:</strong> <code>pandas</code>, <code>numpy</code>, <code>matplotlib</code>, <code>pymc</code>, <code>arviz</code>, and <code>data/processed/m5_weekly.csv</code>. Six model fits, most under 30 seconds.</p>
<hr>
</section>
<section id="setup" class="level2" data-number="13.2">
<h2 data-number="13.2" class="anchored" data-anchor-id="setup"><span class="header-section-number">13.2</span> Setup</h2>
<div id="713607fe" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pymc <span class="im">as</span> pm</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> arviz <span class="im">as</span> az</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">"ignore"</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>RANDOM_STATE <span class="op">=</span> <span class="dv">42</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>weekly <span class="op">=</span> pd.read_csv(<span class="st">"../data/processed/m5_weekly.csv"</span>, parse_dates<span class="op">=</span>[<span class="st">"week_start"</span>])</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>weekly[<span class="st">"series"</span>] <span class="op">=</span> weekly.store_id <span class="op">+</span> <span class="st">"_"</span> <span class="op">+</span> weekly.cat_id</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>weekly[<span class="st">"hi_snap"</span>] <span class="op">=</span> (weekly.snap_days <span class="op">&gt;=</span> <span class="dv">5</span>).astype(<span class="bu">int</span>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> weekly.dropna(subset<span class="op">=</span>[<span class="st">"units"</span>]).copy()</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"ly"</span>] <span class="op">=</span> np.log(df.units.clip(lower<span class="op">=</span><span class="dv">1</span>))</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>df<span class="sc">.</span>series<span class="sc">.</span>nunique()<span class="sc">}</span><span class="ss"> series | </span><span class="sc">{</span><span class="bu">len</span>(df)<span class="sc">:,}</span><span class="ss"> rows | "</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>df<span class="sc">.</span>hi_snap<span class="sc">.</span>mean()<span class="sc">:.1%}</span><span class="ss"> of weeks are high-SNAP"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Our question: <strong>does a high-SNAP week lift units, and by how much in each store?</strong></p>
<p>We will need one helper repeatedly — the SNAP effect actually observed in a set of weeks, with no model involved. It is just the difference in mean log units between high-SNAP weeks and the rest.</p>
<div id="5101eda7" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> empirical_effect(frame, series_name):</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Observed high-SNAP effect on log units for one series."""</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    z <span class="op">=</span> frame[frame.series <span class="op">==</span> series_name]</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> z.hi_snap.nunique() <span class="op">&lt;</span> <span class="dv">2</span>:</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> np.nan</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> z.ly[z.hi_snap <span class="op">==</span> <span class="dv">1</span>].mean() <span class="op">-</span> z.ly[z.hi_snap <span class="op">==</span> <span class="dv">0</span>].mean()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Walkthrough
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<pre><code>30 series | 8,310 rows | 22.1% of weeks are high-SNAP</code></pre>
<p>The question: <strong>does a high-SNAP week lift units, and by how much in each store?</strong></p>
<p>And note this helper, because it is what makes the whole lab possible. It computes the SNAP effect actually observed in a set of weeks — the difference in mean log units between high-SNAP weeks and the rest — with <strong>no model involved.</strong> Later we will hold weeks back, fit a model without them, and then use this function to ask what really happened in those weeks.</p>
<p>Most of the time you cannot grade a model this way. Today you can, because we are going to create the missing data ourselves.</p>
</div>
</div>
</div>
</section>
<section id="step-1-build-the-imbalance" class="level2" data-number="13.3">
<h2 data-number="13.3" class="anchored" data-anchor-id="step-1-build-the-imbalance"><span class="header-section-number">13.3</span> Step 1 — Build the imbalance</h2>
<p>Real panels are lopsided: some series have years of history, others are new stores or newly re-categorized products with a handful of usable weeks. We create that imbalance deliberately so we can check the answer later.</p>
<p>Thin every third series down to 8 weeks. The weeks we remove are not thrown away — they become a held-out set that the model never sees, and that we will use in Step 3 to grade it.</p>
<div id="cad7ff31" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>codes, uniq <span class="op">=</span> pd.factorize(df.series)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"idx"</span>] <span class="op">=</span> codes</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>J <span class="op">=</span> <span class="bu">len</span>(uniq)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.RandomState(RANDOM_STATE)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>keep <span class="op">=</span> []</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(J):</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    rows <span class="op">=</span> df.index[df.idx <span class="op">==</span> j].tolist()</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    n <span class="op">=</span> <span class="dv">8</span> <span class="cf">if</span> j <span class="op">%</span> <span class="dv">3</span> <span class="op">==</span> <span class="dv">0</span> <span class="cf">else</span> <span class="bu">len</span>(rows)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>    keep <span class="op">+=</span> <span class="bu">list</span>(rng.choice(rows, size<span class="op">=</span><span class="bu">min</span>(n, <span class="bu">len</span>(rows)), replace<span class="op">=</span><span class="va">False</span>))</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>train <span class="op">=</span> df.loc[<span class="bu">sorted</span>(keep)].copy()</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>heldout <span class="op">=</span> df.drop(index<span class="op">=</span>keep).copy()</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>thin <span class="op">=</span> np.array([j <span class="op">%</span> <span class="dv">3</span> <span class="op">==</span> <span class="dv">0</span> <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(J)])</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"train </span><span class="sc">{</span><span class="bu">len</span>(train)<span class="sc">:,}</span><span class="ss"> rows | held-out </span><span class="sc">{</span><span class="bu">len</span>(heldout)<span class="sc">:,}</span><span class="ss"> rows"</span>)</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>thin<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">}</span><span class="ss"> thin series (8 weeks each), </span><span class="sc">{</span>(<span class="op">~</span>thin)<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">}</span><span class="ss"> full series"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here is the model. It is the one from lecture, written non-centred, and it takes a flag so we can reuse it for the unpooled fit.</p>
<div id="7ab68586" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> fit(data, kind, n_series, centred<span class="op">=</span><span class="va">False</span>, target_accept<span class="op">=</span><span class="fl">0.9</span>):</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""kind: 'unpooled' or 'hier'. Returns the InferenceData."""</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    i <span class="op">=</span> data.idx.values</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> data.hi_snap.values.astype(<span class="bu">float</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> data.ly.values</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">with</span> pm.Model():</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>        a <span class="op">=</span> pm.Normal(<span class="st">"a"</span>, y.mean(), <span class="dv">1</span>, shape<span class="op">=</span>n_series)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>        s <span class="op">=</span> pm.Exponential(<span class="st">"s"</span>, <span class="fl">1.0</span>)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> kind <span class="op">==</span> <span class="st">"unpooled"</span>:</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>            b <span class="op">=</span> pm.Normal(<span class="st">"b"</span>, <span class="dv">0</span>, <span class="fl">0.5</span>, shape<span class="op">=</span>n_series)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>        <span class="cf">else</span>:</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>            mu_b <span class="op">=</span> pm.Normal(<span class="st">"mu_b"</span>, <span class="dv">0</span>, <span class="fl">0.5</span>)</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>            sd_b <span class="op">=</span> pm.HalfNormal(<span class="st">"sd_b"</span>, <span class="fl">0.25</span>)</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> centred:</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>                b <span class="op">=</span> pm.Normal(<span class="st">"b"</span>, mu_b, sd_b, shape<span class="op">=</span>n_series)</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>            <span class="cf">else</span>:</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>                z <span class="op">=</span> pm.Normal(<span class="st">"z"</span>, <span class="dv">0</span>, <span class="dv">1</span>, shape<span class="op">=</span>n_series)</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>                b <span class="op">=</span> pm.Deterministic(<span class="st">"b"</span>, mu_b <span class="op">+</span> z <span class="op">*</span> sd_b)</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>        pm.Normal(<span class="st">"obs"</span>, mu<span class="op">=</span>a[i] <span class="op">+</span> b[i] <span class="op">*</span> x, sigma<span class="op">=</span>s, observed<span class="op">=</span>y)</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> pm.sample(<span class="dv">1000</span>, tune<span class="op">=</span><span class="dv">1500</span>, chains<span class="op">=</span><span class="dv">4</span>, progressbar<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>                         random_seed<span class="op">=</span>RANDOM_STATE, target_accept<span class="op">=</span>target_accept)</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> b_means(idata, n_series):</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> az.summary(idata, var_names<span class="op">=</span>[<span class="st">"b"</span>], ci_kind<span class="op">=</span><span class="st">"hdi"</span>,</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>                      ci_prob<span class="op">=</span><span class="fl">0.94</span>)[<span class="st">"mean"</span>].values</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Walkthrough
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<pre><code>train 5,620 rows | held-out 2,690 rows
10 thin series (8 weeks each), 20 full series</code></pre>
<p>Real panels are lopsided — some series have years of history, others are new stores with a handful of weeks. We manufacture that imbalance: every third series cut down to <strong>8 weeks</strong>.</p>
<p>The weeks we remove are not discarded. They go into <code>heldout</code>, the model never sees them, and in Step 3 they become the answer key.</p>
<p>Remember the rule: <code>j % 3 == 0</code>. Every third series. It looks arbitrary and it is about to matter enormously.</p>
</div>
</div>
</div>
</section>
<section id="step-2-fit-it-and-admire-the-shrinkage" class="level2" data-number="13.4">
<h2 data-number="13.4" class="anchored" data-anchor-id="step-2-fit-it-and-admire-the-shrinkage"><span class="header-section-number">13.4</span> Step 2 — Fit it, and admire the shrinkage</h2>
<p>Fit both models on all thirty series and measure how far each estimate moved.</p>
<div id="8a703ce1" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>idata_u30 <span class="op">=</span> fit(train, <span class="st">"unpooled"</span>, J)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>idata_h30 <span class="op">=</span> fit(train, <span class="st">"hier"</span>, J)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>bu30, bh30 <span class="op">=</span> b_means(idata_u30, J), b_means(idata_h30, J)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> diag(idata, label):</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    su <span class="op">=</span> az.summary(idata, var_names<span class="op">=</span>[<span class="st">"b"</span>], ci_kind<span class="op">=</span><span class="st">"hdi"</span>, ci_prob<span class="op">=</span><span class="fl">0.94</span>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>label<span class="sc">:&lt;14s}</span><span class="ss"> r_hat </span><span class="sc">{</span>su<span class="sc">.</span>r_hat<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.3f}</span><span class="ss">  "</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"ess </span><span class="sc">{</span>su<span class="sc">.</span>ess_bulk<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:5.0f}</span><span class="ss">  "</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"divergences </span><span class="sc">{</span><span class="bu">int</span>(idata.sample_stats.diverging.<span class="bu">sum</span>())<span class="sc">:4d}</span><span class="ss">"</span>)</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Diagnostics"</span>)</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>diag(idata_u30, <span class="st">"unpooled"</span>)</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>diag(idata_h30, <span class="st">"hierarchical"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="b89ac596" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>move_thin <span class="op">=</span> np.<span class="bu">abs</span>(bh30[thin] <span class="op">-</span> bu30[thin]).mean()</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>move_full <span class="op">=</span> np.<span class="bu">abs</span>(bh30[<span class="op">~</span>thin] <span class="op">-</span> bu30[<span class="op">~</span>thin]).mean()</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">              unpooled spread   after pooling   mean move"</span>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  thin (8w)       </span><span class="sc">{</span>bu30[thin]<span class="sc">.</span>std()<span class="sc">:.3f}</span><span class="ss">           "</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>bh30[thin]<span class="sc">.</span>std()<span class="sc">:.3f}</span><span class="ss">          </span><span class="sc">{</span>move_thin<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  full (277w)     </span><span class="sc">{</span>bu30[<span class="op">~</span>thin]<span class="sc">.</span>std()<span class="sc">:.3f}</span><span class="ss">           "</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>bh30[<span class="op">~</span>thin]<span class="sc">.</span>std()<span class="sc">:.3f}</span><span class="ss">          </span><span class="sc">{</span>move_full<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">  ratio: thin series moved </span><span class="sc">{</span>move_thin <span class="op">/</span> move_full<span class="sc">:.1f}</span><span class="ss">x further"</span>)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>g <span class="op">=</span> az.summary(idata_h30, var_names<span class="op">=</span>[<span class="st">"mu_b"</span>, <span class="st">"sd_b"</span>], ci_kind<span class="op">=</span><span class="st">"hdi"</span>, ci_prob<span class="op">=</span><span class="fl">0.94</span>)</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  mu_b </span><span class="sc">{</span>g<span class="sc">.</span>loc[<span class="st">'mu_b'</span>,<span class="st">'mean'</span>]<span class="sc">:.3f}</span><span class="ss">   sd_b </span><span class="sc">{</span>g<span class="sc">.</span>loc[<span class="st">'sd_b'</span>,<span class="st">'mean'</span>]<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Everything a hierarchical model is supposed to do, it did. Diagnostics are clean. The data-poor series moved an order of magnitude further toward the group mean than the data-rich ones, and nobody told the model which was which.</p>
<p>The shrinkage plot makes it visual.</p>
<div id="c9d17640" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">7</span>, <span class="dv">5</span>))</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(J):</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    c <span class="op">=</span> <span class="st">"crimson"</span> <span class="cf">if</span> thin[j] <span class="cf">else</span> <span class="st">"steelblue"</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    ax.plot([<span class="dv">0</span>, <span class="dv">1</span>], [bu30[j], bh30[j]], <span class="st">"-o"</span>, color<span class="op">=</span>c, alpha<span class="op">=</span><span class="fl">0.7</span>, ms<span class="op">=</span><span class="dv">4</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>ax.axhline(g.loc[<span class="st">"mu_b"</span>, <span class="st">"mean"</span>], ls<span class="op">=</span><span class="st">"--"</span>, c<span class="op">=</span><span class="st">"gray"</span>, lw<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>ax.set_xticks([<span class="dv">0</span>, <span class="dv">1</span>])<span class="op">;</span> ax.set_xticklabels([<span class="st">"unpooled"</span>, <span class="st">"hierarchical"</span>])</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"estimated high-SNAP effect (log units)"</span>)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Shrinkage: thin series (red) collapse onto the group mean"</span>)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()<span class="op">;</span> plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Before you go on
</div>
</div>
<div class="callout-body-container callout-body">
<p>Write down, in one sentence, what you would now tell the business. Keep it — Step 3 will ask whether it was right.</p>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Walkthrough
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<pre><code>Diagnostics
  unpooled       r_hat 1.004  ess  6637  divergences    0
  hierarchical   r_hat 1.001  ess  5203  divergences    0</code></pre>
<p>Both models sampled cleanly. R-hat near one, effective sample sizes in the thousands, not one divergence. If you were checking your work the way Lecture 10 taught you, you would stop here satisfied.</p>
<pre><code>              unpooled spread   after pooling   mean move
  thin (8w)       0.104           0.000          0.110
  full (277w)     0.012           0.001          0.010

  ratio: thin series moved 11.5x further
  mu_b 0.011   sd_b 0.008</code></pre>
<p>And this is textbook. The thin series — 8 weeks each — moved <strong>11.5 times further</strong> toward the group mean than the full series did. Nobody told the model which series were starved. It worked that out from how much each one had to say.</p>
<p>The picture makes it obvious: the red lines, the thin series, collapse onto the dashed group mean. The blue lines barely move.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Try it
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<p>Pause the video and write one sentence: what would you now tell the business about SNAP weeks? Keep it where you can see it. Step 3 is going to ask whether it was right. Before we grade it, look at one number I have not commented on. <strong><code>sd_b</code> is 0.008.</strong></p>
<p>That is the model’s estimate of how much stores differ from one another. Eight thousandths of a log unit — which is to say, the model has concluded that all thirty of these series respond to SNAP <strong>essentially identically</strong>.</p>
<p>Hold that up against what you know about the world. Thirty series spanning three states, three product categories, stores of different sizes. Is “they are all the same” plausible?</p>
<p>It is not a diagnostic. Nothing flags it. But it is a <strong>claim about the world</strong>, and claims about the world can be sanity-checked in a way that R-hat cannot.</p>
</div>
</div>
</div>
</section>
<section id="step-3-grade-it-against-the-weeks-it-never-saw" class="level2" data-number="13.5">
<h2 data-number="13.5" class="anchored" data-anchor-id="step-3-grade-it-against-the-weeks-it-never-saw"><span class="header-section-number">13.5</span> Step 3 — Grade it against the weeks it never saw</h2>
<p>We thinned those ten series ourselves. The weeks we removed are sitting in <code>heldout</code>, and each thinned series has hundreds of them. So we can compute the effect that <em>actually</em> occurred and compare.</p>
<div id="fb8551bf" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>thin_names <span class="op">=</span> [uniq[j] <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(J) <span class="cf">if</span> thin[j]]</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>truth <span class="op">=</span> np.array([empirical_effect(heldout, s) <span class="cf">for</span> s <span class="kw">in</span> thin_names])</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>est_u <span class="op">=</span> np.array([bu30[j] <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(J) <span class="cf">if</span> thin[j]])</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>est_h <span class="op">=</span> np.array([bh30[j] <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(J) <span class="cf">if</span> thin[j]])</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>out <span class="op">=</span> pd.DataFrame({<span class="st">"series"</span>: thin_names, <span class="st">"unpooled"</span>: est_u.<span class="bu">round</span>(<span class="dv">3</span>),</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"hierarchical"</span>: est_h.<span class="bu">round</span>(<span class="dv">3</span>), <span class="st">"held_out_truth"</span>: truth.<span class="bu">round</span>(<span class="dv">3</span>)})</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(out.to_string(index<span class="op">=</span><span class="va">False</span>))</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>rmse <span class="op">=</span> <span class="kw">lambda</span> e: np.sqrt(np.nanmean((e <span class="op">-</span> truth) <span class="op">**</span> <span class="dv">2</span>))</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">  RMSE vs truth:  unpooled </span><span class="sc">{</span>rmse(est_u)<span class="sc">:.3f}</span><span class="ss">   "</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"hierarchical </span><span class="sc">{</span>rmse(est_h)<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  mean held-out effect across these series: </span><span class="sc">{</span>np<span class="sc">.</span>nanmean(truth)<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Read that table before reading on.</p>
<p>The hierarchical model reported an effect near <code>mu_b</code> for every one of these series. The held-out weeks say the true effects average close to 0.09 — several times larger. The model did not merely lose precision on these series; it moved them all to the wrong place, and reported tight intervals around it.</p>
<p>And notice what the RMSE column says: pooling barely improved on the unpooled fit at all. All that shrinkage bought us essentially nothing.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
The diagnostics could never have caught this
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(\hat{R}\)</span>, ESS and divergences ask whether the sampler explored the posterior of <em>the model you wrote</em>. They cannot ask whether that model was the right one. Every diagnostic here passed.</p>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Walkthrough
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<pre><code>    series  unpooled  hierarchical  held_out_truth
CA_1_FOODS     0.294         0.011           0.087
CA_2_FOODS     0.017         0.011           0.011
CA_3_FOODS     0.035         0.011           0.105
CA_4_FOODS     0.132         0.011           0.039
TX_1_FOODS     0.089         0.011           0.082
TX_2_FOODS     0.171         0.011           0.067
TX_3_FOODS     0.132         0.011           0.074
WI_1_FOODS    -0.015         0.011           0.033
WI_2_FOODS     0.289         0.011           0.209
WI_3_FOODS     0.015         0.011           0.177

  RMSE vs truth:  unpooled 0.102   hierarchical 0.097
  mean held-out effect across these series: 0.089</code></pre>
<p>Read the middle column first. <strong>0.011, ten times.</strong> The hierarchical model reported essentially the same effect for every one of these ten series.</p>
<p>Now read the last column. The held-out weeks — hundreds of them per series, weeks the model never saw — say the true effects average <strong>0.089</strong>, and range from 0.011 up to 0.209.</p>
<p>The model was not merely imprecise. It moved all ten series to a number roughly <strong>eight times too small</strong>, and reported tight intervals around it.</p>
<p>And look at the RMSE line, because it takes away the last consolation. Unpooled 0.102, hierarchical 0.097. All of that shrinkage — the beautiful collapsing lines, the 11.5× ratio — bought a <strong>five percent</strong> improvement over just fitting each series separately.</p>
<p>Now the sentence that matters most in this lecture. <strong>The diagnostics could never have caught this.</strong> R-hat, ESS and divergences ask whether the sampler explored the posterior of <em>the model you wrote</em>. They cannot ask whether that was the right model to write. Every diagnostic passed, and every diagnostic was answering a different question from the one you cared about.</p>
</div>
</div>
</div>
</section>
<section id="step-4-find-out-what-went-wrong" class="level2" data-number="13.6">
<h2 data-number="13.6" class="anchored" data-anchor-id="step-4-find-out-what-went-wrong"><span class="header-section-number">13.6</span> Step 4 — Find out what went wrong</h2>
<p>Two things are wrong, and one of them is invisible until you look.</p>
<p>First, look at which series we thinned.</p>
<div id="5a5767b6" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"thinned series:"</span>, thin_names)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="1f0acd76" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Empirical high-SNAP effect by category (all data, no model):"</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> cat, grp <span class="kw">in</span> df.groupby(<span class="st">"cat_id"</span>):</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    effs <span class="op">=</span> [empirical_effect(grp, s) <span class="cf">for</span> s <span class="kw">in</span> grp.series.unique()]</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>cat<span class="sc">:&lt;10s}</span><span class="ss"> n=</span><span class="sc">{</span><span class="bu">len</span>(effs)<span class="sc">:2d}</span><span class="ss">  mean </span><span class="sc">{</span>np<span class="sc">.</span>mean(effs)<span class="sc">:+.3f}</span><span class="ss">  "</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"sd </span><span class="sc">{</span>np<span class="sc">.</span>std(effs)<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Two findings, and they compound.</p>
<p><strong>The groups were not exchangeable.</strong> SNAP is a <em>food</em> assistance programme. FOODS responds; HOBBIES and HOUSEHOLD barely move. Putting all thirty in one hierarchy told the model these are thirty interchangeable draws from one distribution — so it estimated a group mean near zero, dominated by the twenty series with no effect, and pulled the FOODS series down to it.</p>
<p><strong>And <code>j % 3 == 0</code> selected exactly the FOODS series.</strong> The series are ordered store-major with three categories each, so every third one is a FOODS series. We starved precisely the ten series that had something to say, then pooled them toward twenty that did not.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exchangeability is a modelling assumption, and it is yours to defend
</div>
</div>
<div class="callout-body-container callout-body">
<p>Groups are exchangeable when, before seeing the data, you have no reason to expect one to differ from another in a particular direction. Ten FOODS series in ten stores: plausible. FOODS against HOBBIES: you knew the answer before you looked.</p>
<p>Nothing in PyMC checks this. No diagnostic reports it. It is subject-matter knowledge, applied before the model is written.</p>
</div>
</div>
<div id="03bb367c" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ---- your turn: uncomment and answer in the strings ----</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="co"># whose_fault = "..."   # &lt;- would a bigger sample have fixed this? why or why not?</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="co"># print(whose_fault)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Walkthrough
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Two things went wrong, and they compound.</p>
<pre><code>thinned series: ['CA_1_FOODS', 'CA_2_FOODS', 'CA_3_FOODS', 'CA_4_FOODS', 'TX_1_FOODS',
                 'TX_2_FOODS', 'TX_3_FOODS', 'WI_1_FOODS', 'WI_2_FOODS', 'WI_3_FOODS']</code></pre>
<p>Every thinned series is a <strong>FOODS</strong> series. All ten. That is not a coincidence and it is not bad luck — the panel is ordered store-major with three categories each, so <code>j % 3 == 0</code> selects the same category every time.</p>
<pre><code>Empirical high-SNAP effect by category (all data, no model):
  FOODS      n=10  mean +0.089  sd 0.058
  HOBBIES    n=10  mean +0.006  sd 0.010
  HOUSEHOLD  n=10  mean +0.011  sd 0.014</code></pre>
<p>And there it is. <strong>SNAP is a food assistance programme.</strong> FOODS responds at +0.089. HOBBIES and HOUSEHOLD are at +0.006 and +0.011 — indistinguishable from nothing. So put the two together, because neither alone is fatal.</p>
<p>We told the model that thirty series were <strong>thirty interchangeable draws from one distribution.</strong> They are not: twenty of them have no effect and ten do. The group mean therefore landed near zero, dominated by the twenty. And then — the second error — we starved <strong>precisely the ten series that had something to say</strong>, so those ten had almost no data with which to resist being pulled toward a mean built from series unlike them.</p>
<p>That is why <code>sd_b</code> came out at 0.008. Averaged across a group where two thirds genuinely have no effect, “stores are all the same” is the best summary of a badly-posed question.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Try it
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<p>Pause and answer the question in the code cell: <strong>would a bigger sample have fixed this?</strong></p>
<p>No — and this is worth being clear about, because “get more data” is the reflex. More weeks per series would sharpen each estimate, and the hierarchy would still be pulling FOODS series toward a mean computed from HOBBIES and HOUSEHOLD. The error is in the <em>structure</em> we imposed, and no quantity of data corrects a structural mistake. It just makes you more confident about it.</p>
<p><strong>Exchangeability is a modelling assumption and it is yours to defend.</strong> Groups are exchangeable when, before seeing the data, you have no reason to expect one to differ from another in a particular direction. Ten FOODS series across ten stores: plausible. FOODS against HOBBIES: you knew the answer before you looked.</p>
<p>Nothing in PyMC checks this. No diagnostic reports it. It is subject-matter knowledge, applied before the model is written.</p>
</div>
</div>
</div>
</section>
<section id="step-5-do-it-on-the-exchangeable-set" class="level2" data-number="13.7">
<h2 data-number="13.7" class="anchored" data-anchor-id="step-5-do-it-on-the-exchangeable-set"><span class="header-section-number">13.7</span> Step 5 — Do it on the exchangeable set</h2>
<p>Restrict to the ten FOODS series — the set we can actually defend pooling — and rebuild the same imbalance: thin every other one to 8 weeks.</p>
<div id="652cb170" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>foods <span class="op">=</span> df[df.cat_id <span class="op">==</span> <span class="st">"FOODS"</span>].copy()</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>codes_f, uniq_f <span class="op">=</span> pd.factorize(foods.series)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>foods[<span class="st">"idx"</span>] <span class="op">=</span> codes_f</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>Jf <span class="op">=</span> <span class="bu">len</span>(uniq_f)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.RandomState(RANDOM_STATE)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>keep_f <span class="op">=</span> []</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(Jf):</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>    rows <span class="op">=</span> foods.index[foods.idx <span class="op">==</span> j].tolist()</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>    n <span class="op">=</span> <span class="dv">8</span> <span class="cf">if</span> j <span class="op">%</span> <span class="dv">2</span> <span class="op">==</span> <span class="dv">0</span> <span class="cf">else</span> <span class="bu">len</span>(rows)</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>    keep_f <span class="op">+=</span> <span class="bu">list</span>(rng.choice(rows, size<span class="op">=</span><span class="bu">min</span>(n, <span class="bu">len</span>(rows)), replace<span class="op">=</span><span class="va">False</span>))</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>train_f <span class="op">=</span> foods.loc[<span class="bu">sorted</span>(keep_f)].copy()</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>heldout_f <span class="op">=</span> foods.drop(index<span class="op">=</span>keep_f).copy()</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>thin_f <span class="op">=</span> np.array([j <span class="op">%</span> <span class="dv">2</span> <span class="op">==</span> <span class="dv">0</span> <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(Jf)])</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>Jf<span class="sc">}</span><span class="ss"> FOODS series | </span><span class="sc">{</span>thin_f<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">}</span><span class="ss"> thinned to 8 weeks"</span>)</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"train </span><span class="sc">{</span><span class="bu">len</span>(train_f)<span class="sc">:,}</span><span class="ss"> rows | held-out </span><span class="sc">{</span><span class="bu">len</span>(heldout_f)<span class="sc">:,}</span><span class="ss"> rows"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="fe9e5457" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>idata_uf <span class="op">=</span> fit(train_f, <span class="st">"unpooled"</span>, Jf)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>idata_hf <span class="op">=</span> fit(train_f, <span class="st">"hier"</span>, Jf)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>buf, bhf <span class="op">=</span> b_means(idata_uf, Jf), b_means(idata_hf, Jf)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>gf <span class="op">=</span> az.summary(idata_hf, var_names<span class="op">=</span>[<span class="st">"mu_b"</span>, <span class="st">"sd_b"</span>], ci_kind<span class="op">=</span><span class="st">"hdi"</span>, ci_prob<span class="op">=</span><span class="fl">0.94</span>)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(gf.<span class="bu">round</span>(<span class="dv">3</span>).to_string())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="c14367d9" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>mt <span class="op">=</span> np.<span class="bu">abs</span>(bhf[thin_f] <span class="op">-</span> buf[thin_f]).mean()</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>mf <span class="op">=</span> np.<span class="bu">abs</span>(bhf[<span class="op">~</span>thin_f] <span class="op">-</span> buf[<span class="op">~</span>thin_f]).mean()</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"              unpooled spread   after pooling   mean move"</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  thin (8w)       </span><span class="sc">{</span>buf[thin_f]<span class="sc">.</span>std()<span class="sc">:.3f}</span><span class="ss">           "</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>bhf[thin_f]<span class="sc">.</span>std()<span class="sc">:.3f}</span><span class="ss">          </span><span class="sc">{</span>mt<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  full (277w)     </span><span class="sc">{</span>buf[<span class="op">~</span>thin_f]<span class="sc">.</span>std()<span class="sc">:.3f}</span><span class="ss">           "</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>bhf[<span class="op">~</span>thin_f]<span class="sc">.</span>std()<span class="sc">:.3f}</span><span class="ss">          </span><span class="sc">{</span>mf<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">  ratio: thin moved </span><span class="sc">{</span>mt <span class="op">/</span> mf<span class="sc">:.1f}</span><span class="ss">x further"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Compare that middle column to Step 2’s. There, <em>everything</em> collapsed onto the group mean. Here the thin series collapse but the full series <strong>keep most of their spread</strong> — the model discarded variation that 8 weeks could not support and kept variation that 277 weeks could. That is what partial pooling is supposed to look like.</p>
<p>Now grade it the same way.</p>
<div id="b42de393" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>tn <span class="op">=</span> [uniq_f[j] <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(Jf) <span class="cf">if</span> thin_f[j]]</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>truth_f <span class="op">=</span> np.array([empirical_effect(heldout_f, s) <span class="cf">for</span> s <span class="kw">in</span> tn])</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>eu <span class="op">=</span> np.array([buf[j] <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(Jf) <span class="cf">if</span> thin_f[j]])</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>eh <span class="op">=</span> np.array([bhf[j] <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(Jf) <span class="cf">if</span> thin_f[j]])</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(pd.DataFrame({<span class="st">"series"</span>: tn, <span class="st">"unpooled"</span>: eu.<span class="bu">round</span>(<span class="dv">3</span>),</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"hierarchical"</span>: eh.<span class="bu">round</span>(<span class="dv">3</span>),</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"held_out_truth"</span>: truth_f.<span class="bu">round</span>(<span class="dv">3</span>)}).to_string(index<span class="op">=</span><span class="va">False</span>))</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>r_u <span class="op">=</span> np.sqrt(np.nanmean((eu <span class="op">-</span> truth_f) <span class="op">**</span> <span class="dv">2</span>))</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>r_h <span class="op">=</span> np.sqrt(np.nanmean((eh <span class="op">-</span> truth_f) <span class="op">**</span> <span class="dv">2</span>))</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">  RMSE vs truth:  unpooled </span><span class="sc">{</span>r_u<span class="sc">:.3f}</span><span class="ss">   hierarchical </span><span class="sc">{</span>r_h<span class="sc">:.3f}</span><span class="ss">"</span></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"   (</span><span class="sc">{</span>r_u <span class="op">/</span> r_h<span class="sc">:.1f}</span><span class="ss">x better)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>That is borrowing strength, and now it is real.</strong> The same code, the same priors, the same diagnostics — and the thin series are estimated well because the other five exist. The only thing that changed was which series were allowed into the hierarchy.</p>
<div id="19e090d7" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ---- your turn: uncomment and fill in the comparison ----</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="co"># print("30-series pooling improved RMSE by ___%")   # &lt;- from Step 3's two numbers</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="co"># print("FOODS-only pooling improved RMSE by ___%")  # &lt;- from the two above</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Walkthrough
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<pre><code>10 FOODS series | 5 thinned to 8 weeks
train 1,425 rows | held-out 1,345 rows</code></pre>
<p>Same code. Same priors. Same thinning trick — every other series cut to 8 weeks. The <strong>only</strong> change is which series are allowed into the hierarchy.</p>
<pre><code>       mean     sd hdi94_lb hdi94_ub ess_bulk ess_tail r_hat
mu_b  0.077  0.035    0.016     0.15     1315     1619  1.00
sd_b  0.066  0.038    0.012     0.15      756     1016  1.00</code></pre>
<p><code>mu_b</code> is <strong>0.077</strong> — a real SNAP effect, where before it was 0.011. And <code>sd_b</code> is <strong>0.066</strong>, where before it was 0.008. Eight times larger.</p>
<p>That second number is the interesting one. The model now says stores genuinely differ from one another, because on a defensible group they do. The earlier 0.008 was not a finding about stores; it was an artifact of asking about the wrong group.</p>
<pre><code>              unpooled spread   after pooling   mean move
  thin (8w)       0.108           0.010          0.120
  full (277w)     0.055           0.038          0.015

  ratio: thin moved 8.2x further</code></pre>
<p>Compare the middle column with Step 2’s. There, <strong>everything</strong> collapsed — thin spread went to 0.000, full to 0.001. Here the thin series collapse to 0.010 but the full series <strong>keep most of their spread</strong>: 0.055 down to 0.038, about seventy percent retained.</p>
<p>That is what partial pooling is supposed to look like. The model discarded variation that 8 weeks could not support, and kept variation that 277 weeks could. In Step 2 it discarded everything, which should have been the tell.</p>
<pre><code>    series  unpooled  hierarchical  held_out_truth
CA_1_FOODS     0.292         0.097           0.087
CA_3_FOODS     0.103         0.080           0.102
TX_1_FOODS     0.052         0.074           0.082
TX_3_FOODS     0.211         0.090           0.072
WI_2_FOODS     0.338         0.101           0.207

  RMSE vs truth:  unpooled 0.126   hierarchical 0.049   (2.6x better)</code></pre>
<p>Now read the middle column against the last one. 0.097 against 0.087. 0.080 against 0.102. 0.090 against 0.072. These are <em>close</em>, and each one came from a series with <strong>eight weeks of data.</strong> RMSE against the truth: 0.126 unpooled, <strong>0.049</strong> hierarchical. Two and a half times better.</p>
<p><strong>That is borrowing strength, and now it is real.</strong> Same code, same priors, same diagnostics — and the thin series are estimated well because the other five exist. The only thing that changed was which series were allowed into the hierarchy.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Try it
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<p>Fill in the comparison in the last cell: what percentage did pooling improve RMSE in Step 3, and what percentage here?</p>
</div>
</div>
</div>
</section>
<section id="step-6-the-trap-in-the-code" class="level2" data-number="13.8">
<h2 data-number="13.8" class="anchored" data-anchor-id="step-6-the-trap-in-the-code"><span class="header-section-number">13.8</span> Step 6 — The trap in the code</h2>
<p>One more failure, and this one <em>is</em> mechanical. The natural way to write the hierarchy reads exactly like the equation:</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>b <span class="op">=</span> pm.Normal(<span class="st">"b"</span>, mu_b, sd_b, shape<span class="op">=</span>J)   <span class="co"># the centred form</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Fit it that way and watch the diagnostics.</p>
<div id="548b66e3" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>idata_cent <span class="op">=</span> fit(train_f, <span class="st">"hier"</span>, Jf, centred<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Diagnostics"</span>)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>diag(idata_cent, <span class="st">"centred"</span>)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>diag(idata_hf, <span class="st">"non-centred"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Same model. Same data. Same answer, if you could sample it — but the centred form makes the sampler walk a funnel: when <code>sd_b</code> is small the <code>b_j</code> must crowd into a narrow neck, and a sampler tuned for the wide part cannot get in.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Which alarm fired
</div>
</div>
<div class="callout-body-container callout-body">
<p>Look at the two columns. <span class="math inline">\(\hat{R}\)</span> is near the threshold and ESS clears 400 — on those two numbers alone you might have shipped it. The divergence count is unambiguous.</p>
<p>On hierarchical models, divergences are the sensitive instrument. Do not wait for <span class="math inline">\(\hat{R}\)</span>.</p>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Walkthrough
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>One more failure, and this one <strong>is</strong> mechanical rather than conceptual.</p>
<p>The natural way to write a hierarchy reads exactly like the equation: <code>b = pm.Normal("b", mu_b, sd_b, shape=J)</code>. Everybody writes it that way first. It is called the centred form.</p>
<pre><code>Diagnostics
  centred        r_hat 1.044  ess   413  divergences  127
  non-centred    r_hat 1.002  ess  1728  divergences    1</code></pre>
<p>Same model. Same data. The same posterior, if you could sample it — but the centred form makes the sampler walk a <strong>funnel</strong>: when <code>sd_b</code> is small the individual <code>b_j</code> must crowd into a narrow neck, and a sampler tuned for the wide part of the funnel cannot get into the neck. Now read the three numbers as three different <em>kinds</em> of warning, because that is the lesson. <strong>ESS passes.</strong> 413, thirteen over the threshold. You would not look twice.</p>
<p><strong>R-hat fails</strong> — 1.044 against 1.01. But be honest about what happens in practice when a number is a little over a line: people rerun it, or call it close enough, or decide the threshold is conservative.</p>
<p><strong>127 divergences against a threshold of exactly zero.</strong> There is no version of “close to zero” that gets you to a hundred and twenty-seven. It admits no conversation.</p>
<p>So the rule: on hierarchical models, <strong>divergences fire first and least ambiguously.</strong> Do not wait for R-hat to decide for you.</p>
</div>
</div>
</div>
</section>
<section id="before-you-leave" class="level2" data-number="13.9">
<h2 data-number="13.9" class="anchored" data-anchor-id="before-you-leave"><span class="header-section-number">13.9</span> Before you leave</h2>
<blockquote class="blockquote">
<p><strong>Discuss (the failure):</strong> Step 2’s model had clean diagnostics, textbook shrinkage, and a defensible-sounding conclusion. Step 3 showed it was wrong. What kind of check caught it, and why could no amount of sampler diagnostics have done so?</p>
<p><strong>Discuss (the assumption):</strong> You are asked to pool weekly demand across the ten stores in one chain. Name one variable that, if it differed across those stores, would break exchangeability the way category did here — and say how you would handle it without abandoning the hierarchy.</p>
<p><strong>Discuss (the judgement):</strong> In Step 5, <code>sd_b</code> came out around 0.07 — stores genuinely differ. The unpooled fit put the range at roughly 5% to 33%. Given both numbers, what do you actually recommend the business do for the next SNAP week?</p>
<p><strong>Discuss (the thread):</strong> This is the sixth time this semester that a model has been improved by pulling estimates toward a common value. Name the other five, and say what is different about the shrinkage strength here.</p>
</blockquote>
<hr>
<p><em>Solutions posted to Canvas after class.</em></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Walkthrough
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Try it
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<p>Four questions for the board.</p>
<p><strong>The failure.</strong> Step 2 had clean diagnostics, textbook shrinkage and a defensible conclusion. Step 3 showed it was wrong. What kind of check caught it, and why could no amount of sampler diagnostics have done so? model never saw can audit the model.*</p>
<p><strong>The assumption.</strong> You are asked to pool weekly demand across the ten stores in one chain. Name one variable that, if it differed across those stores, would break exchangeability the way category did here — and say how you would handle it <strong>without</strong> abandoning the hierarchy.</p>
<p>as a predictor, or nest the hierarchy — stores within regions — rather than giving up on pooling.*</p>
<p><strong>The judgement.</strong> In Step 5, <code>sd_b</code> came out around 0.066, so stores genuinely differ. The unpooled fit put the range at roughly 5% to 33%. Given both numbers, what do you actually recommend the business do for the next SNAP week?</p>
<p><strong>The thread.</strong> This is the sixth time this semester a model improved by pulling estimates toward a common value. Name the other five, and say what is different about the shrinkage strength here.</p>
<p>and the difference is that here the strength is* estimated from the data <em>rather than chosen by you and tuned on a validation set. <code>sd_b</code> is the shrinkage parameter, and the model infers it.</em></p>
<p>Solutions for the coded parts go up on Canvas after the deadline. Next week: Bayesian linear regression — and a preprocessing step you have used all semester that silently destroys the answer.</p>
</div>
</div>
</div>
</section>
<section id="what-your-run-should-produce" class="level2" data-number="13.10">
<h2 data-number="13.10" class="anchored" data-anchor-id="what-your-run-should-produce"><span class="header-section-number">13.10</span> What your run should produce</h2>
<p>Your numbers will differ where a model is stochastic; these are the values this lab produces on the pinned environment.</p>
<p><code>random_seed=42</code> throughout; six fits, whole lab ≈ 3 minutes.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Quantity</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Panel</td>
<td>30 series · 8,310 rows · <strong>22.1%</strong> high-SNAP weeks</td>
</tr>
<tr class="even">
<td>Split</td>
<td>train 5,620 · held-out 2,690 · 10 thin (8 wks) + 20 full</td>
</tr>
<tr class="odd">
<td><strong>Step 2</strong> diagnostics</td>
<td>unpooled 1.004 / 6,637 / 0 · hierarchical 1.001 / 5,203 / <strong>0</strong> — all clean</td>
</tr>
<tr class="even">
<td>Step 2 shrinkage</td>
<td>thin 0.104 → <strong>0.000</strong> (move 0.110) · full 0.012 → 0.001 (move 0.010) · ratio <strong>11.5×</strong></td>
</tr>
<tr class="odd">
<td>Step 2 hierarchy</td>
<td><code>mu_b</code> <strong>0.011</strong> · <code>sd_b</code> <strong>0.008</strong> ← implausibly small; the substantive tell</td>
</tr>
<tr class="even">
<td><strong>Step 3</strong> grading</td>
<td>hierarchical reports <strong>0.011 for all ten</strong>; held-out truth averages <strong>0.089</strong></td>
</tr>
<tr class="odd">
<td>Step 3 RMSE</td>
<td>unpooled 0.102 · hierarchical 0.097 — pooling bought <strong>~5%</strong></td>
</tr>
<tr class="even">
<td><strong>Step 4</strong> by category</td>
<td>FOODS <strong>+0.089</strong> (sd 0.058) · HOBBIES +0.006 · HOUSEHOLD +0.011</td>
</tr>
<tr class="odd">
<td>Step 4 thinning</td>
<td><code>j % 3 == 0</code> selects <strong>all ten FOODS series</strong></td>
</tr>
<tr class="even">
<td><strong>Step 5</strong> hierarchy</td>
<td><code>mu_b</code> <strong>0.077</strong> [0.016, 0.150] · <code>sd_b</code> <strong>0.066</strong> — 8× Step 2’s</td>
</tr>
<tr class="odd">
<td>Step 5 shrinkage</td>
<td>thin 0.108 → 0.010 · full 0.055 → <strong>0.038</strong> (70% retained) · ratio <strong>8.2×</strong></td>
</tr>
<tr class="even">
<td>Step 5 grading</td>
<td>unpooled 0.126 · hierarchical <strong>0.049</strong> — <strong>2.6× better</strong></td>
</tr>
<tr class="odd">
<td><strong>Step 6</strong> centred</td>
<td>R-hat <strong>1.044</strong> · ESS 413 · divergences <strong>127</strong></td>
</tr>
<tr class="even">
<td>Step 6 non-centred</td>
<td>R-hat 1.002 · ESS 1,728 · divergences <strong>1</strong></td>
</tr>
</tbody>
</table>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/Lecture11_Part1_lab.html" class="pagination-link" aria-label="Lab 11 Part 1: Structural Time Series — and Two Ways to Get the Interval Wrong">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Lab 11 Part 1: Structural Time Series — and Two Ways to Get the Interval Wrong</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/Lecture12_lab.html" class="pagination-link" aria-label="Lab 12: Elasticity — What the Coefficient Means, and What It Costs to Get Wrong">
        <span class="nav-page-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Lab 12: Elasticity — What the Coefficient Means, and What It Costs to Get Wrong</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>